import photoAccessHelper from '@ohos.file.photoAccessHelper';

declare let _v0: photoAccessHelper.Album; _v0.addAssets([]);
declare let _v1: photoAccessHelper.Album; _v1.removeAssets([]);
declare let _v2: photoAccessHelper.PhotoAccessHelper; _v2.createDeleteRequest([]);
declare let _v3: photoAccessHelper.PhotoAsset; _v3.close(0);
declare let _v4: photoAccessHelper.PhotoAsset; _v4.getReadOnlyFd();
