import image from '@ohos.multimedia.image';

let _v0: image.GetImagePropertyOptions;
declare let _v1: image.GetImagePropertyOptions; _v1.defaultValue;
declare let _v2: image.GetImagePropertyOptions; _v2.index;
declare let _v3: image.ImagePacker; _v3.packing;
declare let _v4: image.ImageSource; _v4.getImageProperty('');
declare let _v5: image.ImageSource; _v5.modifyImageProperty('', '');
image.createImageCreator(0, 0, 0, 0);
image.createImageReceiver(0, 0, 0, 0);
