import url from '@ohos.url';

declare let _v0: url.URL; _v0.searchParams;
url.URLSearchParams;
// @ohos.url.url.URLSearchParams.[Symbol.iterator]: bracket-notation member '[Symbol.iterator]' (scanner limitation); usage omitted
declare let _v1: url.URLSearchParams; _v1.append('', '');
declare let _v2: url.URLSearchParams; _v2.delete('');
declare let _v3: url.URLSearchParams; _v3.entries();
declare let _v4: url.URLSearchParams; _v4.forEach(() => {});
declare let _v5: url.URLSearchParams; _v5.get('');
declare let _v6: url.URLSearchParams; _v6.getAll('');
declare let _v7: url.URLSearchParams; _v7.has('');
declare let _v8: url.URLSearchParams; _v8.keys();
declare let _v9: url.URLSearchParams; _v9.set('', '');
declare let _v10: url.URLSearchParams; _v10.sort();
declare let _v11: url.URLSearchParams; _v11.toString();
declare let _v12: url.URLSearchParams; _v12.values();
