import Notification from '@system.notification';
import { ActionResult, ShowNotificationOptions } from '@system.notification';

let _v0: ActionResult;
let _v1: ShowNotificationOptions;
let _v2: Notification;
declare let _v3: ActionResult; _v3.abilityName;
declare let _v4: ActionResult; _v4.bundleName;
declare let _v5: ShowNotificationOptions; _v5.clickAction;
declare let _v6: ShowNotificationOptions; _v6.contentText;
declare let _v7: ShowNotificationOptions; _v7.contentTitle;
Notification.show();
declare let _v8: ActionResult; _v8.uri;
