import Package from '@system.package';
import { CheckPackageHasInstalledOptions, CheckPackageHasInstalledResponse } from '@system.package';

let _v0: CheckPackageHasInstalledResponse;
let _v1: CheckPackageHasInstalledOptions;
let _v2: Package;
declare let _v3: CheckPackageHasInstalledOptions; _v3.bundleName;
declare let _v4: CheckPackageHasInstalledOptions; _v4.complete;
declare let _v5: CheckPackageHasInstalledOptions; _v5.fail;
Package.hasInstalled({ bundleName: '' });
declare let _v6: CheckPackageHasInstalledResponse; _v6.result;
declare let _v7: CheckPackageHasInstalledOptions; _v7.success;
