// Auto-generated by scripts/gen-deprecated-usage.mjs — do not edit.
// Kit: @ohos.application.Want
// Deprecated symbols: 10 (compilable real-usage corpus; expect TS 6385/6387).
// Generated: 2026-08-15T18:18:26.091Z

import Want from '@ohos.application.Want';

// Deprecated symbol usages.
// since 9; useinstead @ohos.app.ability.Want.
let _v0: Want = {} as Want;
// since 9; useinstead @ohos.app.ability.Want.abilityName
let _v1: Want = {} as Want; const _v2 = _v1.abilityName;
// since 9; useinstead @ohos.app.ability.Want.action
let _v3: Want = {} as Want; const _v4 = _v3.action;
// since 9; useinstead @ohos.app.ability.Want.bundleName
let _v5: Want = {} as Want; const _v6 = _v5.bundleName;
// since 9; useinstead @ohos.app.ability.Want.deviceId
let _v7: Want = {} as Want; const _v8 = _v7.deviceId;
// since 9; useinstead @ohos.app.ability.Want.entities
let _v9: Want = {} as Want; const _v10 = _v9.entities;
// since 9; useinstead @ohos.app.ability.Want.flags
let _v11: Want = {} as Want; const _v12 = _v11.flags;
// since 9; useinstead @ohos.app.ability.Want.parameters
let _v13: Want = {} as Want; const _v14 = _v13.parameters;
// since 9; useinstead @ohos.app.ability.Want.type
let _v15: Want = {} as Want; const _v16 = _v15.type;
// since 9; useinstead @ohos.app.ability.Want.uri
let _v17: Want = {} as Want; const _v18 = _v17.uri;
