// Auto-generated by scripts/gen-deprecated-usage.mjs — do not edit.
// Kit: @ohos.wifiManagerExt
// Deprecated symbols: 3 (compilable real-usage corpus; expect TS 6385/6387).
// Generated: 2026-08-15T18:18:26.091Z

import wifiManagerExt from '@ohos.wifiManagerExt';

// Deprecated symbol usages.
// since 10; useinstead none
wifiManagerExt.disableHotspot();
// since 10; useinstead none
wifiManagerExt.enableHotspot();
// since 10; useinstead none
wifiManagerExt.setPowerMode(({} as any));
