// Auto-generated by scripts/gen-deprecated-usage.mjs — do not edit.
// Kit: @ohos.resourceManager
// Deprecated symbols: 31 (compilable real-usage corpus; expect TS 6385/6387).
// Generated: 2026-08-15T18:18:26.091Z

import resourceManager from '@ohos.resourceManager';

// Deprecated symbol usages.
// since 9; useinstead @ohos.base.
let _v0: resourceManager.AsyncCallback<any> = {} as resourceManager.AsyncCallback<any>;
// since 9; useinstead @ohos.resourceManager.closeRawFd
let _v1: resourceManager.ResourceManager = {} as resourceManager.ResourceManager; _v1.closeRawFileDescriptor('');
// since 20; useinstead @ohos.resourceManager.getBoolean
let _v2: resourceManager.ResourceManager = {} as resourceManager.ResourceManager; _v2.getBoolean(({} as any));
// since 20; useinstead @ohos.resourceManager.getColor
let _v3: resourceManager.ResourceManager = {} as resourceManager.ResourceManager; _v3.getColor(({} as any));
// since 20; useinstead @ohos.resourceManager.getColorSync
let _v4: resourceManager.ResourceManager = {} as resourceManager.ResourceManager; _v4.getColorSync(({} as any));
// since 20; useinstead @ohos.resourceManager.getDoublePluralStringValueSync
let _v5: resourceManager.ResourceManager = {} as resourceManager.ResourceManager; _v5.getDoublePluralStringValueSync(({} as any), 0);
// since 20; useinstead @ohos.resourceManager.getDrawableDescriptor
let _v6: resourceManager.ResourceManager = {} as resourceManager.ResourceManager; _v6.getDrawableDescriptor(({} as any));
// since 20; useinstead @ohos.resourceManager.getIntPluralStringValueSync
let _v7: resourceManager.ResourceManager = {} as resourceManager.ResourceManager; _v7.getIntPluralStringValueSync(({} as any), 0);
// since 9; useinstead @ohos.resourceManager.getMediaContent
let _v8: resourceManager.ResourceManager = {} as resourceManager.ResourceManager; _v8.getMedia(0);
// since 9; useinstead @ohos.resourceManager.getMediaContentBase64
let _v9: resourceManager.ResourceManager = {} as resourceManager.ResourceManager; _v9.getMediaBase64(0);
// since 20; useinstead @ohos.resourceManager.getMediaContent
let _v10: resourceManager.ResourceManager = {} as resourceManager.ResourceManager; _v10.getMediaContent(({} as any));
// since 20; useinstead @ohos.resourceManager.getMediaContentBase64
let _v11: resourceManager.ResourceManager = {} as resourceManager.ResourceManager; _v11.getMediaContentBase64(({} as any));
// since 20; useinstead @ohos.resourceManager.getMediaContentBase64Sync
let _v12: resourceManager.ResourceManager = {} as resourceManager.ResourceManager; _v12.getMediaContentBase64Sync(({} as any));
// since 20; useinstead @ohos.resourceManager.getMediaContentSync
let _v13: resourceManager.ResourceManager = {} as resourceManager.ResourceManager; _v13.getMediaContentSync(({} as any));
// since 20; useinstead @ohos.resourceManager.getNumber
let _v14: resourceManager.ResourceManager = {} as resourceManager.ResourceManager; _v14.getNumber(({} as any));
// since 9; useinstead @ohos.resourceManager.getPluralStringValue
let _v15: resourceManager.ResourceManager = {} as resourceManager.ResourceManager; _v15.getPluralString(0, 0);
// since 18; useinstead @ohos.resourceManager.getIntPluralStringByNameSync
let _v16: resourceManager.ResourceManager = {} as resourceManager.ResourceManager; _v16.getPluralStringByName('', 0);
// since 18; useinstead @ohos.resourceManager.getIntPluralStringByNameSync
let _v17: resourceManager.ResourceManager = {} as resourceManager.ResourceManager; _v17.getPluralStringByNameSync('', 0);
// since 18; useinstead @ohos.resourceManager.getIntPluralStringValueSync
let _v18: resourceManager.ResourceManager = {} as resourceManager.ResourceManager; _v18.getPluralStringValue(({} as any), 0);
// since 18; useinstead @ohos.resourceManager.getIntPluralStringValueSync
let _v19: resourceManager.ResourceManager = {} as resourceManager.ResourceManager; _v19.getPluralStringValueSync(0, 0);
// since 9; useinstead @ohos.resourceManager.getRawFileContent
let _v20: resourceManager.ResourceManager = {} as resourceManager.ResourceManager; _v20.getRawFile('');
// since 9; useinstead @ohos.resourceManager.getRawFd
let _v21: resourceManager.ResourceManager = {} as resourceManager.ResourceManager; _v21.getRawFileDescriptor('');
// since 9; useinstead @ohos.resourceManager.getStringValue
let _v22: resourceManager.ResourceManager = {} as resourceManager.ResourceManager; _v22.getString(0);
// since 9; useinstead @ohos.resourceManager.getStringArrayValue
let _v23: resourceManager.ResourceManager = {} as resourceManager.ResourceManager; _v23.getStringArray(0);
// since 20; useinstead @ohos.resourceManager.getStringArrayValue
let _v24: resourceManager.ResourceManager = {} as resourceManager.ResourceManager; _v24.getStringArrayValue(({} as any));
// since 20; useinstead @ohos.resourceManager.getStringArrayValueSync
let _v25: resourceManager.ResourceManager = {} as resourceManager.ResourceManager; _v25.getStringArrayValueSync(({} as any));
// since 20; useinstead @ohos.resourceManager.getStringSync
let _v26: resourceManager.ResourceManager = {} as resourceManager.ResourceManager; _v26.getStringSync(({} as any));
// since 20; useinstead @ohos.resourceManager.getStringValue
let _v27: resourceManager.ResourceManager = {} as resourceManager.ResourceManager; _v27.getStringValue(({} as any));
// since 20; useinstead @ohos.resourceManager.getSymbol
let _v28: resourceManager.ResourceManager = {} as resourceManager.ResourceManager; _v28.getSymbol(({} as any));
// since 12; useinstead none
let _v29: resourceManager.ResourceManager = {} as resourceManager.ResourceManager; _v29.release();
// since 20; useinstead @ohos.resourceManager.getSysResourceManager
resourceManager.getSystemResourceManager();
