// Auto-generated by scripts/gen-deprecated-usage.mjs — do not edit.
// Kit: @ohos.arkui.componentUtils
// Deprecated symbols: 1 (compilable real-usage corpus; expect TS 6385/6387).
// Generated: 2026-08-15T18:18:26.091Z

import componentUtils from '@ohos.arkui.componentUtils';

// Deprecated symbol usages.
// since 18; useinstead @ohos.arkui.UIContext.ComponentUtils.getRectangleById
componentUtils.getRectangleById('');
