// Auto-generated by scripts/gen-deprecated-usage.mjs — do not edit.
// Kit: @ohos.file.fs
// Deprecated symbols: 1 (compilable real-usage corpus; expect TS 6385/6387).
// Generated: 2026-08-15T18:18:26.091Z

import fileIo from '@ohos.file.fs';

// Deprecated symbol usages.
// since 24; useinstead none
let _v0: fileIo.TaskSignal = {} as fileIo.TaskSignal; _v0.onCancel();
