// Auto-generated by scripts/gen-deprecated-usage.mjs — do not edit.
// Kit: @ohos.util.Vector
// Deprecated symbols: 31 (compilable real-usage corpus; expect TS 6385/6387).
// Generated: 2026-08-15T18:18:26.091Z

import Vector from '@ohos.util.Vector';

// Deprecated symbol usages.
// since 9; useinstead @ohos.util.ArrayList.
let _v0: Vector<any> = {} as Vector<any>;
// since 9; useinstead none
// @ohos.util.Vector.Vector.[Symbol.iterator]: bracket-notation member '[Symbol.iterator]' (scanner limitation); usage omitted
// since 9; useinstead none
let _v1: Vector<any> = {} as Vector<any>; _v1.add(({} as any));
// since 9; useinstead none
let _v2: Vector<any> = {} as Vector<any>; _v2.clear();
// since 9; useinstead none
let _v3: Vector<any> = {} as Vector<any>; _v3.clone();
// since 9; useinstead none
let _v4: Vector<any> = {} as Vector<any>; _v4.convertToArray();
// since 9; useinstead none
let _v5: Vector<any> = {} as Vector<any>; _v5.copyToArray([]);
// since 9; useinstead none
let _v6: Vector<any> = {} as Vector<any>; _v6.forEach(() => {});
// since 9; useinstead none
let _v7: Vector<any> = {} as Vector<any>; _v7.get(0);
// since 9; useinstead none
let _v8: Vector<any> = {} as Vector<any>; _v8.getCapacity();
// since 9; useinstead none
let _v9: Vector<any> = {} as Vector<any>; _v9.getFirstElement();
// since 9; useinstead none
let _v10: Vector<any> = {} as Vector<any>; _v10.getIndexFrom(({} as any), 0);
// since 9; useinstead none
let _v11: Vector<any> = {} as Vector<any>; _v11.getIndexOf(({} as any));
// since 9; useinstead none
let _v12: Vector<any> = {} as Vector<any>; _v12.getLastElement();
// since 9; useinstead none
let _v13: Vector<any> = {} as Vector<any>; _v13.getLastIndexFrom(({} as any), 0);
// since 9; useinstead none
let _v14: Vector<any> = {} as Vector<any>; _v14.getLastIndexOf(({} as any));
// since 9; useinstead none
let _v15: Vector<any> = {} as Vector<any>; _v15.has(({} as any));
// since 9; useinstead none
let _v16: Vector<any> = {} as Vector<any>; _v16.increaseCapacityTo(0);
// since 9; useinstead none
let _v17: Vector<any> = {} as Vector<any>; _v17.insert(({} as any), 0);
// since 9; useinstead none
let _v18: Vector<any> = {} as Vector<any>; _v18.isEmpty();
// since 9; useinstead none
let _v19: Vector<any> = {} as Vector<any>; const _v20 = _v19.length;
// since 9; useinstead none
let _v21: Vector<any> = {} as Vector<any>; _v21.remove(({} as any));
// since 9; useinstead none
let _v22: Vector<any> = {} as Vector<any>; _v22.removeByIndex(0);
// since 9; useinstead none
let _v23: Vector<any> = {} as Vector<any>; _v23.removeByRange(0, 0);
// since 9; useinstead none
let _v24: Vector<any> = {} as Vector<any>; _v24.replaceAllElements(() => {});
// since 9; useinstead none
let _v25: Vector<any> = {} as Vector<any>; _v25.set(0, ({} as any));
// since 9; useinstead none
let _v26: Vector<any> = {} as Vector<any>; _v26.setLength(0);
// since 9; useinstead none
let _v27: Vector<any> = {} as Vector<any>; _v27.sort();
// since 9; useinstead none
let _v28: Vector<any> = {} as Vector<any>; _v28.subVector(0, 0);
// since 9; useinstead none
let _v29: Vector<any> = {} as Vector<any>; _v29.toString();
// since 9; useinstead none
let _v30: Vector<any> = {} as Vector<any>; _v30.trimToCurrentLength();
