// Auto-generated by scripts/gen-deprecated-usage.mjs — do not edit.
// Kit: @ohos.bluetooth
// Deprecated symbols: 315 (compilable real-usage corpus; expect TS 6385/6387).
// Generated: 2026-08-15T18:18:26.091Z

import bluetooth from '@ohos.bluetooth';

// Deprecated symbol usages.
// since 9; useinstead @ohos.bluetoothManager.
// @ohos.bluetooth.bluetooth: module-move (kit-level); covered by the import line
// since 9; useinstead @ohos.bluetoothManager.BLE
// @ohos.bluetooth.BLE: type-only namespace; no value usage; omitted
// since 9; useinstead @ohos.bluetoothManager.A2dpSourceProfile
let _v0: bluetooth.A2dpSourceProfile = {} as bluetooth.A2dpSourceProfile;
// since 9; useinstead @ohos.bluetoothManager.A2dpSourceProfile.connect
let _v1: bluetooth.A2dpSourceProfile = {} as bluetooth.A2dpSourceProfile; _v1.connect('');
// since 9; useinstead @ohos.bluetoothManager.A2dpSourceProfile.disconnect
let _v2: bluetooth.A2dpSourceProfile = {} as bluetooth.A2dpSourceProfile; _v2.disconnect('');
// since 9; useinstead @ohos.bluetoothManager.A2dpSourceProfile.getPlayingState
let _v3: bluetooth.A2dpSourceProfile = {} as bluetooth.A2dpSourceProfile; _v3.getPlayingState('');
// since 9; useinstead @ohos.bluetoothManager.A2dpSourceProfile.off
let _v4: bluetooth.A2dpSourceProfile = {} as bluetooth.A2dpSourceProfile; _v4.off('connectionStateChange');
// since 9; useinstead @ohos.bluetoothManager.A2dpSourceProfile.on
let _v5: bluetooth.A2dpSourceProfile = {} as bluetooth.A2dpSourceProfile; _v5.on('connectionStateChange', () => {});
// since 9; useinstead @ohos.bluetoothManager.AdvertiseData
let _v6: bluetooth.AdvertiseData = {} as bluetooth.AdvertiseData;
// since 9; useinstead @ohos.bluetoothManager.AdvertiseData.manufactureData
let _v7: bluetooth.AdvertiseData = {} as bluetooth.AdvertiseData; const _v8 = _v7.manufactureData;
// since 9; useinstead @ohos.bluetoothManager.AdvertiseData.serviceData
let _v9: bluetooth.AdvertiseData = {} as bluetooth.AdvertiseData; const _v10 = _v9.serviceData;
// since 9; useinstead @ohos.bluetoothManager.AdvertiseData.serviceUuids
let _v11: bluetooth.AdvertiseData = {} as bluetooth.AdvertiseData; const _v12 = _v11.serviceUuids;
// since 9; useinstead @ohos.bluetoothManager.AdvertiseSetting
let _v13: bluetooth.AdvertiseSetting = {} as bluetooth.AdvertiseSetting;
// since 9; useinstead @ohos.bluetoothManager.AdvertiseSetting.connectable
let _v14: bluetooth.AdvertiseSetting = {} as bluetooth.AdvertiseSetting; const _v15 = _v14.connectable;
// since 9; useinstead @ohos.bluetoothManager.AdvertiseSetting.interval
let _v16: bluetooth.AdvertiseSetting = {} as bluetooth.AdvertiseSetting; const _v17 = _v16.interval;
// since 9; useinstead @ohos.bluetoothManager.AdvertiseSetting.txPower
let _v18: bluetooth.AdvertiseSetting = {} as bluetooth.AdvertiseSetting; const _v19 = _v18.txPower;
// since 9; useinstead @ohos.bluetoothManager.BLE.createGattClientDevice
bluetooth.BLE.createGattClientDevice('');
// since 9; useinstead @ohos.bluetoothManager.BLE.createGattServer
bluetooth.BLE.createGattServer();
// since 9; useinstead @ohos.bluetoothManager.BLE.getConnectedBLEDevices
bluetooth.BLE.getConnectedBLEDevices();
// since 9; useinstead @ohos.bluetoothManager.BLE.off
bluetooth.BLE.off('BLEDeviceFind');
// since 9; useinstead @ohos.bluetoothManager.BLE.on
bluetooth.BLE.on('BLEDeviceFind', () => {});
// since 9; useinstead @ohos.bluetoothManager.BLE.startBLEScan
bluetooth.BLE.startBLEScan([]);
// since 9; useinstead @ohos.bluetoothManager.BLE.stopBLEScan
bluetooth.BLE.stopBLEScan();
// since 9; useinstead @ohos.bluetoothManager.BLECharacteristic
let _v20: bluetooth.BLECharacteristic = {} as bluetooth.BLECharacteristic;
// since 9; useinstead @ohos.bluetoothManager.BLECharacteristic.characteristicUuid
let _v21: bluetooth.BLECharacteristic = {} as bluetooth.BLECharacteristic; const _v22 = _v21.characteristicUuid;
// since 9; useinstead @ohos.bluetoothManager.BLECharacteristic.characteristicValue
let _v23: bluetooth.BLECharacteristic = {} as bluetooth.BLECharacteristic; const _v24 = _v23.characteristicValue;
// since 9; useinstead @ohos.bluetoothManager.BLECharacteristic.descriptors
let _v25: bluetooth.BLECharacteristic = {} as bluetooth.BLECharacteristic; const _v26 = _v25.descriptors;
// since 9; useinstead @ohos.bluetoothManager.BLECharacteristic.serviceUuid
let _v27: bluetooth.BLECharacteristic = {} as bluetooth.BLECharacteristic; const _v28 = _v27.serviceUuid;
// since 9; useinstead @ohos.bluetoothManager.BLEConnectChangedState
let _v29: bluetooth.BLEConnectChangedState = {} as bluetooth.BLEConnectChangedState;
// since 9; useinstead @ohos.bluetoothManager.BLEConnectChangedState.deviceId
let _v30: bluetooth.BLEConnectChangedState = {} as bluetooth.BLEConnectChangedState; const _v31 = _v30.deviceId;
// since 9; useinstead @ohos.bluetoothManager.BLEConnectChangedState.state
let _v32: bluetooth.BLEConnectChangedState = {} as bluetooth.BLEConnectChangedState; const _v33 = _v32.state;
// since 9; useinstead @ohos.bluetoothManager.BLEDescriptor
let _v34: bluetooth.BLEDescriptor = {} as bluetooth.BLEDescriptor;
// since 9; useinstead @ohos.bluetoothManager.BLEDescriptor.characteristicUuid
let _v35: bluetooth.BLEDescriptor = {} as bluetooth.BLEDescriptor; const _v36 = _v35.characteristicUuid;
// since 9; useinstead @ohos.bluetoothManager.BLEDescriptor.descriptorUuid
let _v37: bluetooth.BLEDescriptor = {} as bluetooth.BLEDescriptor; const _v38 = _v37.descriptorUuid;
// since 9; useinstead @ohos.bluetoothManager.BLEDescriptor.descriptorValue
let _v39: bluetooth.BLEDescriptor = {} as bluetooth.BLEDescriptor; const _v40 = _v39.descriptorValue;
// since 9; useinstead @ohos.bluetoothManager.BLEDescriptor.serviceUuid
let _v41: bluetooth.BLEDescriptor = {} as bluetooth.BLEDescriptor; const _v42 = _v41.serviceUuid;
// since 9; useinstead @ohos.bluetoothManager.BaseProfile
let _v43: bluetooth.BaseProfile = {} as bluetooth.BaseProfile;
// since 9; useinstead @ohos.bluetoothManager.BaseProfile.getConnectionDevices
let _v44: bluetooth.BaseProfile = {} as bluetooth.BaseProfile; _v44.getConnectionDevices();
// since 9; useinstead @ohos.bluetoothManager.BaseProfile.getDeviceState
let _v45: bluetooth.BaseProfile = {} as bluetooth.BaseProfile; _v45.getDeviceState('');
// since 9; useinstead @ohos.bluetoothManager.BluetoothState
const _v46 = bluetooth.BluetoothState;
// since 9; useinstead @ohos.bluetoothManager.BluetoothState.STATE_BLE_ON
const _v47 = bluetooth.BluetoothState.STATE_BLE_ON;
// since 9; useinstead @ohos.bluetoothManager.BluetoothState.STATE_BLE_TURNING_OFF
const _v48 = bluetooth.BluetoothState.STATE_BLE_TURNING_OFF;
// since 9; useinstead @ohos.bluetoothManager.BluetoothState.STATE_BLE_TURNING_ON
const _v49 = bluetooth.BluetoothState.STATE_BLE_TURNING_ON;
// since 9; useinstead @ohos.bluetoothManager.BluetoothState.STATE_OFF
const _v50 = bluetooth.BluetoothState.STATE_OFF;
// since 9; useinstead @ohos.bluetoothManager.BluetoothState.STATE_ON
const _v51 = bluetooth.BluetoothState.STATE_ON;
// since 9; useinstead @ohos.bluetoothManager.BluetoothState.STATE_TURNING_OFF
const _v52 = bluetooth.BluetoothState.STATE_TURNING_OFF;
// since 9; useinstead @ohos.bluetoothManager.BluetoothState.STATE_TURNING_ON
const _v53 = bluetooth.BluetoothState.STATE_TURNING_ON;
// since 9; useinstead @ohos.bluetoothManager.BondState
const _v54 = bluetooth.BondState;
// since 9; useinstead @ohos.bluetoothManager.BondState.BOND_STATE_BONDED
const _v55 = bluetooth.BondState.BOND_STATE_BONDED;
// since 9; useinstead @ohos.bluetoothManager.BondState.BOND_STATE_BONDING
const _v56 = bluetooth.BondState.BOND_STATE_BONDING;
// since 9; useinstead @ohos.bluetoothManager.BondState.BOND_STATE_INVALID
const _v57 = bluetooth.BondState.BOND_STATE_INVALID;
// since 9; useinstead @ohos.bluetoothManager.BondStateParam
let _v58: bluetooth.BondStateParam = {} as bluetooth.BondStateParam;
// since 9; useinstead @ohos.bluetoothManager.BondStateParam.deviceId
let _v59: bluetooth.BondStateParam = {} as bluetooth.BondStateParam; const _v60 = _v59.deviceId;
// since 9; useinstead @ohos.bluetoothManager.BondStateParam.state
let _v61: bluetooth.BondStateParam = {} as bluetooth.BondStateParam; const _v62 = _v61.state;
// since 9; useinstead @ohos.bluetoothManager.CharacteristicReadRequest
let _v63: bluetooth.CharacteristicReadReq = {} as bluetooth.CharacteristicReadReq;
// since 9; useinstead @ohos.bluetoothManager.CharacteristicReadRequest.characteristicUuid
let _v64: bluetooth.CharacteristicReadReq = {} as bluetooth.CharacteristicReadReq; const _v65 = _v64.characteristicUuid;
// since 9; useinstead @ohos.bluetoothManager.CharacteristicReadRequest.deviceId
let _v66: bluetooth.CharacteristicReadReq = {} as bluetooth.CharacteristicReadReq; const _v67 = _v66.deviceId;
// since 9; useinstead @ohos.bluetoothManager.CharacteristicReadRequest.offset
let _v68: bluetooth.CharacteristicReadReq = {} as bluetooth.CharacteristicReadReq; const _v69 = _v68.offset;
// since 9; useinstead @ohos.bluetoothManager.CharacteristicReadRequest.serviceUuid
let _v70: bluetooth.CharacteristicReadReq = {} as bluetooth.CharacteristicReadReq; const _v71 = _v70.serviceUuid;
// since 9; useinstead @ohos.bluetoothManager.CharacteristicReadRequest.transId
let _v72: bluetooth.CharacteristicReadReq = {} as bluetooth.CharacteristicReadReq; const _v73 = _v72.transId;
// since 9; useinstead @ohos.bluetoothManager.CharacteristicWriteRequest
let _v74: bluetooth.CharacteristicWriteReq = {} as bluetooth.CharacteristicWriteReq;
// since 9; useinstead @ohos.bluetoothManager.CharacteristicWriteRequest.characteristicUuid
let _v75: bluetooth.CharacteristicWriteReq = {} as bluetooth.CharacteristicWriteReq; const _v76 = _v75.characteristicUuid;
// since 9; useinstead @ohos.bluetoothManager.CharacteristicWriteRequest.deviceId
let _v77: bluetooth.CharacteristicWriteReq = {} as bluetooth.CharacteristicWriteReq; const _v78 = _v77.deviceId;
// since 9; useinstead @ohos.bluetoothManager.CharacteristicWriteRequest.isPrep
let _v79: bluetooth.CharacteristicWriteReq = {} as bluetooth.CharacteristicWriteReq; const _v80 = _v79.isPrep;
// since 9; useinstead @ohos.bluetoothManager.CharacteristicWriteRequest.needRsp
let _v81: bluetooth.CharacteristicWriteReq = {} as bluetooth.CharacteristicWriteReq; const _v82 = _v81.needRsp;
// since 9; useinstead @ohos.bluetoothManager.CharacteristicWriteRequest.offset
let _v83: bluetooth.CharacteristicWriteReq = {} as bluetooth.CharacteristicWriteReq; const _v84 = _v83.offset;
// since 9; useinstead @ohos.bluetoothManager.CharacteristicWriteRequest.serviceUuid
let _v85: bluetooth.CharacteristicWriteReq = {} as bluetooth.CharacteristicWriteReq; const _v86 = _v85.serviceUuid;
// since 9; useinstead @ohos.bluetoothManager.CharacteristicWriteRequest.transId
let _v87: bluetooth.CharacteristicWriteReq = {} as bluetooth.CharacteristicWriteReq; const _v88 = _v87.transId;
// since 9; useinstead @ohos.bluetoothManager.CharacteristicWriteRequest.value
let _v89: bluetooth.CharacteristicWriteReq = {} as bluetooth.CharacteristicWriteReq; const _v90 = _v89.value;
// since 9; useinstead @ohos.bluetoothManager.DescriptorReadRequest
let _v91: bluetooth.DescriptorReadReq = {} as bluetooth.DescriptorReadReq;
// since 9; useinstead @ohos.bluetoothManager.DescriptorReadRequest.characteristicUuid
let _v92: bluetooth.DescriptorReadReq = {} as bluetooth.DescriptorReadReq; const _v93 = _v92.characteristicUuid;
// since 9; useinstead @ohos.bluetoothManager.DescriptorReadRequest.descriptorUuid
let _v94: bluetooth.DescriptorReadReq = {} as bluetooth.DescriptorReadReq; const _v95 = _v94.descriptorUuid;
// since 9; useinstead @ohos.bluetoothManager.DescriptorReadRequest.deviceId
let _v96: bluetooth.DescriptorReadReq = {} as bluetooth.DescriptorReadReq; const _v97 = _v96.deviceId;
// since 9; useinstead @ohos.bluetoothManager.DescriptorReadRequest.offset
let _v98: bluetooth.DescriptorReadReq = {} as bluetooth.DescriptorReadReq; const _v99 = _v98.offset;
// since 9; useinstead @ohos.bluetoothManager.DescriptorReadRequest.serviceUuid
let _v100: bluetooth.DescriptorReadReq = {} as bluetooth.DescriptorReadReq; const _v101 = _v100.serviceUuid;
// since 9; useinstead @ohos.bluetoothManager.DescriptorReadRequest.transId
let _v102: bluetooth.DescriptorReadReq = {} as bluetooth.DescriptorReadReq; const _v103 = _v102.transId;
// since 9; useinstead @ohos.bluetoothManager.DescriptorWriteRequest
let _v104: bluetooth.DescriptorWriteReq = {} as bluetooth.DescriptorWriteReq;
// since 9; useinstead @ohos.bluetoothManager.DescriptorWriteRequest.characteristicUuid
let _v105: bluetooth.DescriptorWriteReq = {} as bluetooth.DescriptorWriteReq; const _v106 = _v105.characteristicUuid;
// since 9; useinstead @ohos.bluetoothManager.DescriptorWriteRequest.descriptorUuid
let _v107: bluetooth.DescriptorWriteReq = {} as bluetooth.DescriptorWriteReq; const _v108 = _v107.descriptorUuid;
// since 9; useinstead @ohos.bluetoothManager.DescriptorWriteRequest.deviceId
let _v109: bluetooth.DescriptorWriteReq = {} as bluetooth.DescriptorWriteReq; const _v110 = _v109.deviceId;
// since 9; useinstead @ohos.bluetoothManager.DescriptorWriteRequest.isPrep
let _v111: bluetooth.DescriptorWriteReq = {} as bluetooth.DescriptorWriteReq; const _v112 = _v111.isPrep;
// since 9; useinstead @ohos.bluetoothManager.DescriptorWriteRequest.needRsp
let _v113: bluetooth.DescriptorWriteReq = {} as bluetooth.DescriptorWriteReq; const _v114 = _v113.needRsp;
// since 9; useinstead @ohos.bluetoothManager.DescriptorWriteRequest.offset
let _v115: bluetooth.DescriptorWriteReq = {} as bluetooth.DescriptorWriteReq; const _v116 = _v115.offset;
// since 9; useinstead @ohos.bluetoothManager.DescriptorWriteRequest.serviceUuid
let _v117: bluetooth.DescriptorWriteReq = {} as bluetooth.DescriptorWriteReq; const _v118 = _v117.serviceUuid;
// since 9; useinstead @ohos.bluetoothManager.DescriptorWriteRequest.transId
let _v119: bluetooth.DescriptorWriteReq = {} as bluetooth.DescriptorWriteReq; const _v120 = _v119.transId;
// since 9; useinstead @ohos.bluetoothManager.DescriptorWriteRequest.value
let _v121: bluetooth.DescriptorWriteReq = {} as bluetooth.DescriptorWriteReq; const _v122 = _v121.value;
// since 9; useinstead @ohos.bluetoothManager.DeviceClass
let _v123: bluetooth.DeviceClass = {} as bluetooth.DeviceClass;
// since 9; useinstead @ohos.bluetoothManager.DeviceClass.classOfDevice
let _v124: bluetooth.DeviceClass = {} as bluetooth.DeviceClass; const _v125 = _v124.classOfDevice;
// since 9; useinstead @ohos.bluetoothManager.DeviceClass.majorClass
let _v126: bluetooth.DeviceClass = {} as bluetooth.DeviceClass; const _v127 = _v126.majorClass;
// since 9; useinstead @ohos.bluetoothManager.DeviceClass.majorMinorClass
let _v128: bluetooth.DeviceClass = {} as bluetooth.DeviceClass; const _v129 = _v128.majorMinorClass;
// since 9; useinstead @ohos.bluetoothManager.GattClientDevice
let _v130: bluetooth.GattClientDevice = {} as bluetooth.GattClientDevice;
// since 9; useinstead @ohos.bluetoothManager.GattClientDevice.close
let _v131: bluetooth.GattClientDevice = {} as bluetooth.GattClientDevice; _v131.close();
// since 9; useinstead @ohos.bluetoothManager.GattClientDevice.connect
let _v132: bluetooth.GattClientDevice = {} as bluetooth.GattClientDevice; _v132.connect();
// since 9; useinstead @ohos.bluetoothManager.GattClientDevice.disconnect
let _v133: bluetooth.GattClientDevice = {} as bluetooth.GattClientDevice; _v133.disconnect();
// since 9; useinstead @ohos.bluetoothManager.GattClientDevice.getDeviceName
let _v134: bluetooth.GattClientDevice = {} as bluetooth.GattClientDevice; _v134.getDeviceName();
// since 9; useinstead @ohos.bluetoothManager.GattClientDevice.getRssiValue
let _v135: bluetooth.GattClientDevice = {} as bluetooth.GattClientDevice; _v135.getRssiValue();
// since 9; useinstead @ohos.bluetoothManager.GattClientDevice.getServices
let _v136: bluetooth.GattClientDevice = {} as bluetooth.GattClientDevice; _v136.getServices();
// since 9; useinstead @ohos.bluetoothManager.GattClientDevice.off
let _v137: bluetooth.GattClientDevice = {} as bluetooth.GattClientDevice; _v137.off('BLECharacteristicChange');
// since 9; useinstead @ohos.bluetoothManager.GattClientDevice.on
let _v138: bluetooth.GattClientDevice = {} as bluetooth.GattClientDevice; _v138.on('BLECharacteristicChange', () => {});
// since 9; useinstead @ohos.bluetoothManager.GattClientDevice.readCharacteristicValue
let _v139: bluetooth.GattClientDevice = {} as bluetooth.GattClientDevice; _v139.readCharacteristicValue(({} as any));
// since 9; useinstead @ohos.bluetoothManager.GattClientDevice.readDescriptorValue
let _v140: bluetooth.GattClientDevice = {} as bluetooth.GattClientDevice; _v140.readDescriptorValue(({} as any));
// since 9; useinstead @ohos.bluetoothManager.GattClientDevice.setBLEMtuSize
let _v141: bluetooth.GattClientDevice = {} as bluetooth.GattClientDevice; _v141.setBLEMtuSize(0);
// since 9; useinstead @ohos.bluetoothManager.GattClientDevice.setNotifyCharacteristicChanged
let _v142: bluetooth.GattClientDevice = {} as bluetooth.GattClientDevice; _v142.setNotifyCharacteristicChanged(({} as any), false);
// since 9; useinstead @ohos.bluetoothManager.GattClientDevice.writeCharacteristicValue
let _v143: bluetooth.GattClientDevice = {} as bluetooth.GattClientDevice; _v143.writeCharacteristicValue(({} as any));
// since 9; useinstead @ohos.bluetoothManager.GattClientDevice.writeDescriptorValue
let _v144: bluetooth.GattClientDevice = {} as bluetooth.GattClientDevice; _v144.writeDescriptorValue(({} as any));
// since 9; useinstead @ohos.bluetoothManager.GattServer
let _v145: bluetooth.GattServer = {} as bluetooth.GattServer;
// since 9; useinstead @ohos.bluetoothManager.GattServer.addService
let _v146: bluetooth.GattServer = {} as bluetooth.GattServer; _v146.addService(({} as any));
// since 9; useinstead @ohos.bluetoothManager.GattServer.close
let _v147: bluetooth.GattServer = {} as bluetooth.GattServer; _v147.close();
// since 9; useinstead @ohos.bluetoothManager.GattServer.notifyCharacteristicChanged
let _v148: bluetooth.GattServer = {} as bluetooth.GattServer; _v148.notifyCharacteristicChanged('', ({} as any));
// since 9; useinstead @ohos.bluetoothManager.GattServer.off
let _v149: bluetooth.GattServer = {} as bluetooth.GattServer; _v149.off('characteristicRead');
// since 9; useinstead @ohos.bluetoothManager.GattServer.on
let _v150: bluetooth.GattServer = {} as bluetooth.GattServer; _v150.on('characteristicRead', () => {});
// since 9; useinstead @ohos.bluetoothManager.GattServer.removeService
let _v151: bluetooth.GattServer = {} as bluetooth.GattServer; _v151.removeService('');
// since 9; useinstead @ohos.bluetoothManager.GattServer.sendResponse
let _v152: bluetooth.GattServer = {} as bluetooth.GattServer; _v152.sendResponse(({} as any));
// since 9; useinstead @ohos.bluetoothManager.GattServer.startAdvertising
let _v153: bluetooth.GattServer = {} as bluetooth.GattServer; _v153.startAdvertising(({} as any), ({} as any));
// since 9; useinstead @ohos.bluetoothManager.GattServer.stopAdvertising
let _v154: bluetooth.GattServer = {} as bluetooth.GattServer; _v154.stopAdvertising();
// since 9; useinstead @ohos.bluetoothManager.GattService
let _v155: bluetooth.GattService = {} as bluetooth.GattService;
// since 9; useinstead @ohos.bluetoothManager.GattService.characteristics
let _v156: bluetooth.GattService = {} as bluetooth.GattService; const _v157 = _v156.characteristics;
// since 9; useinstead @ohos.bluetoothManager.GattService.includeServices
let _v158: bluetooth.GattService = {} as bluetooth.GattService; const _v159 = _v158.includeServices;
// since 9; useinstead @ohos.bluetoothManager.GattService.isPrimary
let _v160: bluetooth.GattService = {} as bluetooth.GattService; const _v161 = _v160.isPrimary;
// since 9; useinstead @ohos.bluetoothManager.GattService.serviceUuid
let _v162: bluetooth.GattService = {} as bluetooth.GattService; const _v163 = _v162.serviceUuid;
// since 9; useinstead @ohos.bluetoothManager.HandsFreeAudioGatewayProfile
let _v164: bluetooth.HandsFreeAudioGatewayProfile = {} as bluetooth.HandsFreeAudioGatewayProfile;
// since 9; useinstead @ohos.bluetoothManager.HandsFreeAudioGatewayProfile.connect
let _v165: bluetooth.HandsFreeAudioGatewayProfile = {} as bluetooth.HandsFreeAudioGatewayProfile; _v165.connect('');
// since 9; useinstead @ohos.bluetoothManager.HandsFreeAudioGatewayProfile.disconnect
let _v166: bluetooth.HandsFreeAudioGatewayProfile = {} as bluetooth.HandsFreeAudioGatewayProfile; _v166.disconnect('');
// since 9; useinstead @ohos.bluetoothManager.HandsFreeAudioGatewayProfile.off
let _v167: bluetooth.HandsFreeAudioGatewayProfile = {} as bluetooth.HandsFreeAudioGatewayProfile; _v167.off('connectionStateChange');
// since 9; useinstead @ohos.bluetoothManager.HandsFreeAudioGatewayProfile.on
let _v168: bluetooth.HandsFreeAudioGatewayProfile = {} as bluetooth.HandsFreeAudioGatewayProfile; _v168.on('connectionStateChange', () => {});
// since 9; useinstead @ohos.bluetoothManager.MajorClass
const _v169 = bluetooth.MajorClass;
// since 9; useinstead @ohos.bluetoothManager.MajorClass.MAJOR_AUDIO_VIDEO
const _v170 = bluetooth.MajorClass.MAJOR_AUDIO_VIDEO;
// since 9; useinstead @ohos.bluetoothManager.MajorClass.MAJOR_COMPUTER
const _v171 = bluetooth.MajorClass.MAJOR_COMPUTER;
// since 9; useinstead @ohos.bluetoothManager.MajorClass.MAJOR_HEALTH
const _v172 = bluetooth.MajorClass.MAJOR_HEALTH;
// since 9; useinstead @ohos.bluetoothManager.MajorClass.MAJOR_IMAGING
const _v173 = bluetooth.MajorClass.MAJOR_IMAGING;
// since 9; useinstead @ohos.bluetoothManager.MajorClass.MAJOR_MISC
const _v174 = bluetooth.MajorClass.MAJOR_MISC;
// since 9; useinstead @ohos.bluetoothManager.MajorClass.MAJOR_NETWORKING
const _v175 = bluetooth.MajorClass.MAJOR_NETWORKING;
// since 9; useinstead @ohos.bluetoothManager.MajorClass.MAJOR_PERIPHERAL
const _v176 = bluetooth.MajorClass.MAJOR_PERIPHERAL;
// since 9; useinstead @ohos.bluetoothManager.MajorClass.MAJOR_PHONE
const _v177 = bluetooth.MajorClass.MAJOR_PHONE;
// since 9; useinstead @ohos.bluetoothManager.MajorClass.MAJOR_TOY
const _v178 = bluetooth.MajorClass.MAJOR_TOY;
// since 9; useinstead @ohos.bluetoothManager.MajorClass.MAJOR_UNCATEGORIZED
const _v179 = bluetooth.MajorClass.MAJOR_UNCATEGORIZED;
// since 9; useinstead @ohos.bluetoothManager.MajorClass.MAJOR_WEARABLE
const _v180 = bluetooth.MajorClass.MAJOR_WEARABLE;
// since 9; useinstead @ohos.bluetoothManager.MajorMinorClass
const _v181 = bluetooth.MajorMinorClass;
// since 9; useinstead @ohos.bluetoothManager.MajorMinorClass.AUDIO_VIDEO_CAMCORDER
const _v182 = bluetooth.MajorMinorClass.AUDIO_VIDEO_CAMCORDER;
// since 9; useinstead @ohos.bluetoothManager.MajorMinorClass.AUDIO_VIDEO_CAR_AUDIO
const _v183 = bluetooth.MajorMinorClass.AUDIO_VIDEO_CAR_AUDIO;
// since 9; useinstead @ohos.bluetoothManager.MajorMinorClass.AUDIO_VIDEO_HANDSFREE
const _v184 = bluetooth.MajorMinorClass.AUDIO_VIDEO_HANDSFREE;
// since 9; useinstead @ohos.bluetoothManager.MajorMinorClass.AUDIO_VIDEO_HEADPHONES
const _v185 = bluetooth.MajorMinorClass.AUDIO_VIDEO_HEADPHONES;
// since 9; useinstead @ohos.bluetoothManager.MajorMinorClass.AUDIO_VIDEO_HIFI_AUDIO
const _v186 = bluetooth.MajorMinorClass.AUDIO_VIDEO_HIFI_AUDIO;
// since 9; useinstead @ohos.bluetoothManager.MajorMinorClass.AUDIO_VIDEO_LOUDSPEAKER
const _v187 = bluetooth.MajorMinorClass.AUDIO_VIDEO_LOUDSPEAKER;
// since 9; useinstead @ohos.bluetoothManager.MajorMinorClass.AUDIO_VIDEO_MICROPHONE
const _v188 = bluetooth.MajorMinorClass.AUDIO_VIDEO_MICROPHONE;
// since 9; useinstead @ohos.bluetoothManager.MajorMinorClass.AUDIO_VIDEO_PORTABLE_AUDIO
const _v189 = bluetooth.MajorMinorClass.AUDIO_VIDEO_PORTABLE_AUDIO;
// since 9; useinstead @ohos.bluetoothManager.MajorMinorClass.AUDIO_VIDEO_SET_TOP_BOX
const _v190 = bluetooth.MajorMinorClass.AUDIO_VIDEO_SET_TOP_BOX;
// since 9; useinstead @ohos.bluetoothManager.MajorMinorClass.AUDIO_VIDEO_UNCATEGORIZED
const _v191 = bluetooth.MajorMinorClass.AUDIO_VIDEO_UNCATEGORIZED;
// since 9; useinstead @ohos.bluetoothManager.MajorMinorClass.AUDIO_VIDEO_VCR
const _v192 = bluetooth.MajorMinorClass.AUDIO_VIDEO_VCR;
// since 9; useinstead @ohos.bluetoothManager.MajorMinorClass.AUDIO_VIDEO_VIDEO_CAMERA
const _v193 = bluetooth.MajorMinorClass.AUDIO_VIDEO_VIDEO_CAMERA;
// since 9; useinstead @ohos.bluetoothManager.MajorMinorClass.AUDIO_VIDEO_VIDEO_CONFERENCING
const _v194 = bluetooth.MajorMinorClass.AUDIO_VIDEO_VIDEO_CONFERENCING;
// since 9; useinstead @ohos.bluetoothManager.MajorMinorClass.AUDIO_VIDEO_VIDEO_DISPLAY_AND_LOUDSPEAKER
const _v195 = bluetooth.MajorMinorClass.AUDIO_VIDEO_VIDEO_DISPLAY_AND_LOUDSPEAKER;
// since 9; useinstead @ohos.bluetoothManager.MajorMinorClass.AUDIO_VIDEO_VIDEO_GAMING_TOY
const _v196 = bluetooth.MajorMinorClass.AUDIO_VIDEO_VIDEO_GAMING_TOY;
// since 9; useinstead @ohos.bluetoothManager.MajorMinorClass.AUDIO_VIDEO_VIDEO_MONITOR
const _v197 = bluetooth.MajorMinorClass.AUDIO_VIDEO_VIDEO_MONITOR;
// since 9; useinstead @ohos.bluetoothManager.MajorMinorClass.AUDIO_VIDEO_WEARABLE_HEADSET
const _v198 = bluetooth.MajorMinorClass.AUDIO_VIDEO_WEARABLE_HEADSET;
// since 9; useinstead @ohos.bluetoothManager.MajorMinorClass.COMPUTER_DESKTOP
const _v199 = bluetooth.MajorMinorClass.COMPUTER_DESKTOP;
// since 9; useinstead @ohos.bluetoothManager.MajorMinorClass.COMPUTER_HANDHELD_PC_PDA
const _v200 = bluetooth.MajorMinorClass.COMPUTER_HANDHELD_PC_PDA;
// since 9; useinstead @ohos.bluetoothManager.MajorMinorClass.COMPUTER_LAPTOP
const _v201 = bluetooth.MajorMinorClass.COMPUTER_LAPTOP;
// since 9; useinstead @ohos.bluetoothManager.MajorMinorClass.COMPUTER_PALM_SIZE_PC_PDA
const _v202 = bluetooth.MajorMinorClass.COMPUTER_PALM_SIZE_PC_PDA;
// since 9; useinstead @ohos.bluetoothManager.MajorMinorClass.COMPUTER_SERVER
const _v203 = bluetooth.MajorMinorClass.COMPUTER_SERVER;
// since 9; useinstead @ohos.bluetoothManager.MajorMinorClass.COMPUTER_TABLET
const _v204 = bluetooth.MajorMinorClass.COMPUTER_TABLET;
// since 9; useinstead @ohos.bluetoothManager.MajorMinorClass.COMPUTER_UNCATEGORIZED
const _v205 = bluetooth.MajorMinorClass.COMPUTER_UNCATEGORIZED;
// since 9; useinstead @ohos.bluetoothManager.MajorMinorClass.COMPUTER_WEARABLE
const _v206 = bluetooth.MajorMinorClass.COMPUTER_WEARABLE;
// since 9; useinstead @ohos.bluetoothManager.MajorMinorClass.HEALTH_ANKLE_PROSTHESIS
const _v207 = bluetooth.MajorMinorClass.HEALTH_ANKLE_PROSTHESIS;
// since 9; useinstead @ohos.bluetoothManager.MajorMinorClass.HEALTH_BLOOD_PRESSURE
const _v208 = bluetooth.MajorMinorClass.HEALTH_BLOOD_PRESSURE;
// since 9; useinstead @ohos.bluetoothManager.MajorMinorClass.HEALTH_BODY_COMPOSITION_ANALYZER
const _v209 = bluetooth.MajorMinorClass.HEALTH_BODY_COMPOSITION_ANALYZER;
// since 9; useinstead @ohos.bluetoothManager.MajorMinorClass.HEALTH_DATA_DISPLAY
const _v210 = bluetooth.MajorMinorClass.HEALTH_DATA_DISPLAY;
// since 9; useinstead @ohos.bluetoothManager.MajorMinorClass.HEALTH_GENERIC_HEALTH_MANAGER
const _v211 = bluetooth.MajorMinorClass.HEALTH_GENERIC_HEALTH_MANAGER;
// since 9; useinstead @ohos.bluetoothManager.MajorMinorClass.HEALTH_GLUCOSE
const _v212 = bluetooth.MajorMinorClass.HEALTH_GLUCOSE;
// since 9; useinstead @ohos.bluetoothManager.MajorMinorClass.HEALTH_KNEE_PROSTHESIS
const _v213 = bluetooth.MajorMinorClass.HEALTH_KNEE_PROSTHESIS;
// since 9; useinstead @ohos.bluetoothManager.MajorMinorClass.HEALTH_MEDICATION_MONITOR
const _v214 = bluetooth.MajorMinorClass.HEALTH_MEDICATION_MONITOR;
// since 9; useinstead @ohos.bluetoothManager.MajorMinorClass.HEALTH_PEAK_FLOW_MOITOR
const _v215 = bluetooth.MajorMinorClass.HEALTH_PEAK_FLOW_MOITOR;
// since 9; useinstead @ohos.bluetoothManager.MajorMinorClass.HEALTH_PERSONAL_MOBILITY_DEVICE
const _v216 = bluetooth.MajorMinorClass.HEALTH_PERSONAL_MOBILITY_DEVICE;
// since 9; useinstead @ohos.bluetoothManager.MajorMinorClass.HEALTH_PULSE_OXIMETER
const _v217 = bluetooth.MajorMinorClass.HEALTH_PULSE_OXIMETER;
// since 9; useinstead @ohos.bluetoothManager.MajorMinorClass.HEALTH_PULSE_RATE
const _v218 = bluetooth.MajorMinorClass.HEALTH_PULSE_RATE;
// since 9; useinstead @ohos.bluetoothManager.MajorMinorClass.HEALTH_STEP_COUNTER
const _v219 = bluetooth.MajorMinorClass.HEALTH_STEP_COUNTER;
// since 9; useinstead @ohos.bluetoothManager.MajorMinorClass.HEALTH_THERMOMETER
const _v220 = bluetooth.MajorMinorClass.HEALTH_THERMOMETER;
// since 9; useinstead @ohos.bluetoothManager.MajorMinorClass.HEALTH_UNCATEGORIZED
const _v221 = bluetooth.MajorMinorClass.HEALTH_UNCATEGORIZED;
// since 9; useinstead @ohos.bluetoothManager.MajorMinorClass.HEALTH_WEIGHING
const _v222 = bluetooth.MajorMinorClass.HEALTH_WEIGHING;
// since 9; useinstead @ohos.bluetoothManager.MajorMinorClass.IMAGING_CAMERA
const _v223 = bluetooth.MajorMinorClass.IMAGING_CAMERA;
// since 9; useinstead @ohos.bluetoothManager.MajorMinorClass.IMAGING_DISPLAY
const _v224 = bluetooth.MajorMinorClass.IMAGING_DISPLAY;
// since 9; useinstead @ohos.bluetoothManager.MajorMinorClass.IMAGING_PRINTER
const _v225 = bluetooth.MajorMinorClass.IMAGING_PRINTER;
// since 9; useinstead @ohos.bluetoothManager.MajorMinorClass.IMAGING_SCANNER
const _v226 = bluetooth.MajorMinorClass.IMAGING_SCANNER;
// since 9; useinstead @ohos.bluetoothManager.MajorMinorClass.IMAGING_UNCATEGORIZED
const _v227 = bluetooth.MajorMinorClass.IMAGING_UNCATEGORIZED;
// since 9; useinstead @ohos.bluetoothManager.MajorMinorClass.NETWORK_17_TO_33_UTILIZED
const _v228 = bluetooth.MajorMinorClass.NETWORK_17_TO_33_UTILIZED;
// since 9; useinstead @ohos.bluetoothManager.MajorMinorClass.NETWORK_1_TO_17_UTILIZED
const _v229 = bluetooth.MajorMinorClass.NETWORK_1_TO_17_UTILIZED;
// since 9; useinstead @ohos.bluetoothManager.MajorMinorClass.NETWORK_33_TO_50_UTILIZED
const _v230 = bluetooth.MajorMinorClass.NETWORK_33_TO_50_UTILIZED;
// since 9; useinstead @ohos.bluetoothManager.MajorMinorClass.NETWORK_60_TO_67_UTILIZED
const _v231 = bluetooth.MajorMinorClass.NETWORK_60_TO_67_UTILIZED;
// since 9; useinstead @ohos.bluetoothManager.MajorMinorClass.NETWORK_67_TO_83_UTILIZED
const _v232 = bluetooth.MajorMinorClass.NETWORK_67_TO_83_UTILIZED;
// since 9; useinstead @ohos.bluetoothManager.MajorMinorClass.NETWORK_83_TO_99_UTILIZED
const _v233 = bluetooth.MajorMinorClass.NETWORK_83_TO_99_UTILIZED;
// since 9; useinstead @ohos.bluetoothManager.MajorMinorClass.NETWORK_FULLY_AVAILABLE
const _v234 = bluetooth.MajorMinorClass.NETWORK_FULLY_AVAILABLE;
// since 9; useinstead @ohos.bluetoothManager.MajorMinorClass.NETWORK_NO_SERVICE
const _v235 = bluetooth.MajorMinorClass.NETWORK_NO_SERVICE;
// since 9; useinstead @ohos.bluetoothManager.MajorMinorClass.PERIPHERAL_CARD_READER
const _v236 = bluetooth.MajorMinorClass.PERIPHERAL_CARD_READER;
// since 9; useinstead @ohos.bluetoothManager.MajorMinorClass.PERIPHERAL_DIGITAL_PEN
const _v237 = bluetooth.MajorMinorClass.PERIPHERAL_DIGITAL_PEN;
// since 9; useinstead @ohos.bluetoothManager.MajorMinorClass.PERIPHERAL_DIGITIZER_TABLET
const _v238 = bluetooth.MajorMinorClass.PERIPHERAL_DIGITIZER_TABLET;
// since 9; useinstead @ohos.bluetoothManager.MajorMinorClass.PERIPHERAL_GAMEPAD
const _v239 = bluetooth.MajorMinorClass.PERIPHERAL_GAMEPAD;
// since 9; useinstead @ohos.bluetoothManager.MajorMinorClass.PERIPHERAL_GESTURAL_INPUT
const _v240 = bluetooth.MajorMinorClass.PERIPHERAL_GESTURAL_INPUT;
// since 9; useinstead @ohos.bluetoothManager.MajorMinorClass.PERIPHERAL_JOYSTICK
const _v241 = bluetooth.MajorMinorClass.PERIPHERAL_JOYSTICK;
// since 9; useinstead @ohos.bluetoothManager.MajorMinorClass.PERIPHERAL_KEYBOARD
const _v242 = bluetooth.MajorMinorClass.PERIPHERAL_KEYBOARD;
// since 9; useinstead @ohos.bluetoothManager.MajorMinorClass.PERIPHERAL_KEYBOARD_POINTING
const _v243 = bluetooth.MajorMinorClass.PERIPHERAL_KEYBOARD_POINTING;
// since 9; useinstead @ohos.bluetoothManager.MajorMinorClass.PERIPHERAL_NON_KEYBOARD_NON_POINTING
const _v244 = bluetooth.MajorMinorClass.PERIPHERAL_NON_KEYBOARD_NON_POINTING;
// since 9; useinstead @ohos.bluetoothManager.MajorMinorClass.PERIPHERAL_POINTING_DEVICE
const _v245 = bluetooth.MajorMinorClass.PERIPHERAL_POINTING_DEVICE;
// since 9; useinstead @ohos.bluetoothManager.MajorMinorClass.PERIPHERAL_REMOTE_CONTROL
const _v246 = bluetooth.MajorMinorClass.PERIPHERAL_REMOTE_CONTROL;
// since 9; useinstead @ohos.bluetoothManager.MajorMinorClass.PERIPHERAL_SCANNER_RFID
const _v247 = bluetooth.MajorMinorClass.PERIPHERAL_SCANNER_RFID;
// since 9; useinstead @ohos.bluetoothManager.MajorMinorClass.PERIPHERAL_SENSING_DEVICE
const _v248 = bluetooth.MajorMinorClass.PERIPHERAL_SENSING_DEVICE;
// since 9; useinstead @ohos.bluetoothManager.MajorMinorClass.PERIPHERAL_UNCATEGORIZED
const _v249 = bluetooth.MajorMinorClass.PERIPHERAL_UNCATEGORIZED;
// since 9; useinstead @ohos.bluetoothManager.MajorMinorClass.PHONE_CELLULAR
const _v250 = bluetooth.MajorMinorClass.PHONE_CELLULAR;
// since 9; useinstead @ohos.bluetoothManager.MajorMinorClass.PHONE_CORDLESS
const _v251 = bluetooth.MajorMinorClass.PHONE_CORDLESS;
// since 9; useinstead @ohos.bluetoothManager.MajorMinorClass.PHONE_ISDN
const _v252 = bluetooth.MajorMinorClass.PHONE_ISDN;
// since 9; useinstead @ohos.bluetoothManager.MajorMinorClass.PHONE_MODEM_OR_GATEWAY
const _v253 = bluetooth.MajorMinorClass.PHONE_MODEM_OR_GATEWAY;
// since 9; useinstead @ohos.bluetoothManager.MajorMinorClass.PHONE_SMART
const _v254 = bluetooth.MajorMinorClass.PHONE_SMART;
// since 9; useinstead @ohos.bluetoothManager.MajorMinorClass.PHONE_UNCATEGORIZED
const _v255 = bluetooth.MajorMinorClass.PHONE_UNCATEGORIZED;
// since 9; useinstead @ohos.bluetoothManager.MajorMinorClass.TOY_CONTROLLER
const _v256 = bluetooth.MajorMinorClass.TOY_CONTROLLER;
// since 9; useinstead @ohos.bluetoothManager.MajorMinorClass.TOY_DOLL_ACTION_FIGURE
const _v257 = bluetooth.MajorMinorClass.TOY_DOLL_ACTION_FIGURE;
// since 9; useinstead @ohos.bluetoothManager.MajorMinorClass.TOY_GAME
const _v258 = bluetooth.MajorMinorClass.TOY_GAME;
// since 9; useinstead @ohos.bluetoothManager.MajorMinorClass.TOY_ROBOT
const _v259 = bluetooth.MajorMinorClass.TOY_ROBOT;
// since 9; useinstead @ohos.bluetoothManager.MajorMinorClass.TOY_UNCATEGORIZED
const _v260 = bluetooth.MajorMinorClass.TOY_UNCATEGORIZED;
// since 9; useinstead @ohos.bluetoothManager.MajorMinorClass.TOY_VEHICLE
const _v261 = bluetooth.MajorMinorClass.TOY_VEHICLE;
// since 9; useinstead @ohos.bluetoothManager.MajorMinorClass.WEARABLE_GLASSES
const _v262 = bluetooth.MajorMinorClass.WEARABLE_GLASSES;
// since 9; useinstead @ohos.bluetoothManager.MajorMinorClass.WEARABLE_HELMET
const _v263 = bluetooth.MajorMinorClass.WEARABLE_HELMET;
// since 9; useinstead @ohos.bluetoothManager.MajorMinorClass.WEARABLE_JACKET
const _v264 = bluetooth.MajorMinorClass.WEARABLE_JACKET;
// since 9; useinstead @ohos.bluetoothManager.MajorMinorClass.WEARABLE_PAGER
const _v265 = bluetooth.MajorMinorClass.WEARABLE_PAGER;
// since 9; useinstead @ohos.bluetoothManager.MajorMinorClass.WEARABLE_UNCATEGORIZED
const _v266 = bluetooth.MajorMinorClass.WEARABLE_UNCATEGORIZED;
// since 9; useinstead @ohos.bluetoothManager.MajorMinorClass.WEARABLE_WRIST_WATCH
const _v267 = bluetooth.MajorMinorClass.WEARABLE_WRIST_WATCH;
// since 9; useinstead @ohos.bluetoothManager.ManufactureData
let _v268: bluetooth.ManufactureData = {} as bluetooth.ManufactureData;
// since 9; useinstead @ohos.bluetoothManager.ManufactureData.manufactureId
let _v269: bluetooth.ManufactureData = {} as bluetooth.ManufactureData; const _v270 = _v269.manufactureId;
// since 9; useinstead @ohos.bluetoothManager.ManufactureData.manufactureValue
let _v271: bluetooth.ManufactureData = {} as bluetooth.ManufactureData; const _v272 = _v271.manufactureValue;
// since 9; useinstead @ohos.bluetoothManager.MatchMode
const _v273 = bluetooth.MatchMode;
// since 9; useinstead @ohos.bluetoothManager.MatchMode.MATCH_MODE_AGGRESSIVE
const _v274 = bluetooth.MatchMode.MATCH_MODE_AGGRESSIVE;
// since 9; useinstead @ohos.bluetoothManager.MatchMode.MATCH_MODE_STICKY
const _v275 = bluetooth.MatchMode.MATCH_MODE_STICKY;
// since 9; useinstead @ohos.bluetoothManager.NotifyCharacteristic
let _v276: bluetooth.NotifyCharacteristic = {} as bluetooth.NotifyCharacteristic;
// since 9; useinstead @ohos.bluetoothManager.NotifyCharacteristic.characteristicUuid
let _v277: bluetooth.NotifyCharacteristic = {} as bluetooth.NotifyCharacteristic; const _v278 = _v277.characteristicUuid;
// since 9; useinstead @ohos.bluetoothManager.NotifyCharacteristic.characteristicValue
let _v279: bluetooth.NotifyCharacteristic = {} as bluetooth.NotifyCharacteristic; const _v280 = _v279.characteristicValue;
// since 9; useinstead @ohos.bluetoothManager.NotifyCharacteristic.confirm
let _v281: bluetooth.NotifyCharacteristic = {} as bluetooth.NotifyCharacteristic; const _v282 = _v281.confirm;
// since 9; useinstead @ohos.bluetoothManager.NotifyCharacteristic.serviceUuid
let _v283: bluetooth.NotifyCharacteristic = {} as bluetooth.NotifyCharacteristic; const _v284 = _v283.serviceUuid;
// since 9; useinstead @ohos.bluetoothManager.PinRequiredParam
let _v285: bluetooth.PinRequiredParam = {} as bluetooth.PinRequiredParam;
// since 9; useinstead @ohos.bluetoothManager.PinRequiredParam.deviceId
let _v286: bluetooth.PinRequiredParam = {} as bluetooth.PinRequiredParam; const _v287 = _v286.deviceId;
// since 9; useinstead @ohos.bluetoothManager.PinRequiredParam.pinCode
let _v288: bluetooth.PinRequiredParam = {} as bluetooth.PinRequiredParam; const _v289 = _v288.pinCode;
// since 9; useinstead @ohos.bluetoothManager.PlayingState
const _v290 = bluetooth.PlayingState;
// since 9; useinstead @ohos.bluetoothManager.PlayingState.STATE_NOT_PLAYING
const _v291 = bluetooth.PlayingState.STATE_NOT_PLAYING;
// since 9; useinstead @ohos.bluetoothManager.PlayingState.STATE_PLAYING
const _v292 = bluetooth.PlayingState.STATE_PLAYING;
// since 9; useinstead @ohos.bluetoothManager.ProfileConnectionState
const _v293 = bluetooth.ProfileConnectionState;
// since 9; useinstead @ohos.bluetoothManager.ProfileConnectionState.STATE_CONNECTED
const _v294 = bluetooth.ProfileConnectionState.STATE_CONNECTED;
// since 9; useinstead @ohos.bluetoothManager.ProfileConnectionState.STATE_CONNECTING
const _v295 = bluetooth.ProfileConnectionState.STATE_CONNECTING;
// since 9; useinstead @ohos.bluetoothManager.ProfileConnectionState.STATE_DISCONNECTED
const _v296 = bluetooth.ProfileConnectionState.STATE_DISCONNECTED;
// since 9; useinstead @ohos.bluetoothManager.ProfileConnectionState.STATE_DISCONNECTING
const _v297 = bluetooth.ProfileConnectionState.STATE_DISCONNECTING;
// since 9; useinstead @ohos.bluetoothManager.ProfileId
const _v298 = bluetooth.ProfileId;
// since 9; useinstead @ohos.bluetoothManager.ProfileId.PROFILE_A2DP_SOURCE
const _v299 = bluetooth.ProfileId.PROFILE_A2DP_SOURCE;
// since 9; useinstead @ohos.bluetoothManager.ProfileId.PROFILE_HANDS_FREE_AUDIO_GATEWAY
const _v300 = bluetooth.ProfileId.PROFILE_HANDS_FREE_AUDIO_GATEWAY;
// since 9; useinstead @ohos.bluetoothManager.ScanDuty
const _v301 = bluetooth.ScanDuty;
// since 9; useinstead @ohos.bluetoothManager.ScanDuty.SCAN_MODE_BALANCED
const _v302 = bluetooth.ScanDuty.SCAN_MODE_BALANCED;
// since 9; useinstead @ohos.bluetoothManager.ScanDuty.SCAN_MODE_LOW_LATENCY
const _v303 = bluetooth.ScanDuty.SCAN_MODE_LOW_LATENCY;
// since 9; useinstead @ohos.bluetoothManager.ScanDuty.SCAN_MODE_LOW_POWER
const _v304 = bluetooth.ScanDuty.SCAN_MODE_LOW_POWER;
// since 9; useinstead @ohos.bluetoothManager.ScanFilter
let _v305: bluetooth.ScanFilter = {} as bluetooth.ScanFilter;
// since 9; useinstead @ohos.bluetoothManager.ScanFilter.deviceId
let _v306: bluetooth.ScanFilter = {} as bluetooth.ScanFilter; const _v307 = _v306.deviceId;
// since 9; useinstead @ohos.bluetoothManager.ScanFilter.name
let _v308: bluetooth.ScanFilter = {} as bluetooth.ScanFilter; const _v309 = _v308.name;
// since 9; useinstead @ohos.bluetoothManager.ScanFilter.serviceUuid
let _v310: bluetooth.ScanFilter = {} as bluetooth.ScanFilter; const _v311 = _v310.serviceUuid;
// since 9; useinstead @ohos.bluetoothManager.ScanMode
const _v312 = bluetooth.ScanMode;
// since 9; useinstead @ohos.bluetoothManager.ScanMode.SCAN_MODE_CONNECTABLE
const _v313 = bluetooth.ScanMode.SCAN_MODE_CONNECTABLE;
// since 9; useinstead @ohos.bluetoothManager.ScanMode.SCAN_MODE_CONNECTABLE_GENERAL_DISCOVERABLE
const _v314 = bluetooth.ScanMode.SCAN_MODE_CONNECTABLE_GENERAL_DISCOVERABLE;
// since 9; useinstead @ohos.bluetoothManager.ScanMode.SCAN_MODE_CONNECTABLE_LIMITED_DISCOVERABLE
const _v315 = bluetooth.ScanMode.SCAN_MODE_CONNECTABLE_LIMITED_DISCOVERABLE;
// since 9; useinstead @ohos.bluetoothManager.ScanMode.SCAN_MODE_GENERAL_DISCOVERABLE
const _v316 = bluetooth.ScanMode.SCAN_MODE_GENERAL_DISCOVERABLE;
// since 9; useinstead @ohos.bluetoothManager.ScanMode.SCAN_MODE_LIMITED_DISCOVERABLE
const _v317 = bluetooth.ScanMode.SCAN_MODE_LIMITED_DISCOVERABLE;
// since 9; useinstead @ohos.bluetoothManager.ScanMode.SCAN_MODE_NONE
const _v318 = bluetooth.ScanMode.SCAN_MODE_NONE;
// since 9; useinstead @ohos.bluetoothManager.ScanOptions
let _v319: bluetooth.ScanOptions = {} as bluetooth.ScanOptions;
// since 9; useinstead @ohos.bluetoothManager.ScanOptions.dutyMode
let _v320: bluetooth.ScanOptions = {} as bluetooth.ScanOptions; const _v321 = _v320.dutyMode;
// since 9; useinstead @ohos.bluetoothManager.ScanOptions.interval
let _v322: bluetooth.ScanOptions = {} as bluetooth.ScanOptions; const _v323 = _v322.interval;
// since 9; useinstead @ohos.bluetoothManager.ScanOptions.matchMode
let _v324: bluetooth.ScanOptions = {} as bluetooth.ScanOptions; const _v325 = _v324.matchMode;
// since 9; useinstead @ohos.bluetoothManager.ScanResult
let _v326: bluetooth.ScanResult = {} as bluetooth.ScanResult;
// since 9; useinstead @ohos.bluetoothManager.ScanResult.data
let _v327: bluetooth.ScanResult = {} as bluetooth.ScanResult; const _v328 = _v327.data;
// since 9; useinstead @ohos.bluetoothManager.ScanResult.deviceId
let _v329: bluetooth.ScanResult = {} as bluetooth.ScanResult; const _v330 = _v329.deviceId;
// since 9; useinstead @ohos.bluetoothManager.ScanResult.rssi
let _v331: bluetooth.ScanResult = {} as bluetooth.ScanResult; const _v332 = _v331.rssi;
// since 9; useinstead @ohos.bluetoothManager.ServerResponse
let _v333: bluetooth.ServerResponse = {} as bluetooth.ServerResponse;
// since 9; useinstead @ohos.bluetoothManager.ServerResponse.deviceId
let _v334: bluetooth.ServerResponse = {} as bluetooth.ServerResponse; const _v335 = _v334.deviceId;
// since 9; useinstead @ohos.bluetoothManager.ServerResponse.offset
let _v336: bluetooth.ServerResponse = {} as bluetooth.ServerResponse; const _v337 = _v336.offset;
// since 9; useinstead @ohos.bluetoothManager.ServerResponse.status
let _v338: bluetooth.ServerResponse = {} as bluetooth.ServerResponse; const _v339 = _v338.status;
// since 9; useinstead @ohos.bluetoothManager.ServerResponse.transId
let _v340: bluetooth.ServerResponse = {} as bluetooth.ServerResponse; const _v341 = _v340.transId;
// since 9; useinstead @ohos.bluetoothManager.ServerResponse.value
let _v342: bluetooth.ServerResponse = {} as bluetooth.ServerResponse; const _v343 = _v342.value;
// since 9; useinstead @ohos.bluetoothManager.ServiceData
let _v344: bluetooth.ServiceData = {} as bluetooth.ServiceData;
// since 9; useinstead @ohos.bluetoothManager.ServiceData.serviceUuid
let _v345: bluetooth.ServiceData = {} as bluetooth.ServiceData; const _v346 = _v345.serviceUuid;
// since 9; useinstead @ohos.bluetoothManager.ServiceData.serviceValue
let _v347: bluetooth.ServiceData = {} as bluetooth.ServiceData; const _v348 = _v347.serviceValue;
// since 9; useinstead @ohos.bluetoothManager.SppOption
let _v349: bluetooth.SppOption = {} as bluetooth.SppOption;
// since 9; useinstead @ohos.bluetoothManager.SppOption.secure
let _v350: bluetooth.SppOption = {} as bluetooth.SppOption; const _v351 = _v350.secure;
// since 9; useinstead @ohos.bluetoothManager.SppOption.type
let _v352: bluetooth.SppOption = {} as bluetooth.SppOption; const _v353 = _v352.type;
// since 9; useinstead @ohos.bluetoothManager.SppOption.uuid
let _v354: bluetooth.SppOption = {} as bluetooth.SppOption; const _v355 = _v354.uuid;
// since 9; useinstead @ohos.bluetoothManager.SppType
const _v356 = bluetooth.SppType;
// since 9; useinstead @ohos.bluetoothManager.SppType.SPP_RFCOMM
const _v357 = bluetooth.SppType.SPP_RFCOMM;
// since 9; useinstead @ohos.bluetoothManager.StateChangeParam
let _v358: bluetooth.StateChangeParam = {} as bluetooth.StateChangeParam;
// since 9; useinstead @ohos.bluetoothManager.StateChangeParam.deviceId
let _v359: bluetooth.StateChangeParam = {} as bluetooth.StateChangeParam; const _v360 = _v359.deviceId;
// since 9; useinstead @ohos.bluetoothManager.StateChangeParam.state
let _v361: bluetooth.StateChangeParam = {} as bluetooth.StateChangeParam; const _v362 = _v361.state;
// since 9; useinstead @ohos.bluetoothManager.disableBluetooth
bluetooth.disableBluetooth();
// since 9; useinstead @ohos.bluetoothManager.enableBluetooth
bluetooth.enableBluetooth();
// since 9; useinstead @ohos.bluetoothManager.getBluetoothScanMode
bluetooth.getBluetoothScanMode();
// since 9; useinstead @ohos.bluetoothManager.getBtConnectionState
bluetooth.getBtConnectionState();
// since 9; useinstead @ohos.bluetoothManager.getLocalName
bluetooth.getLocalName();
// since 9; useinstead @ohos.bluetoothManager.getPairedDevices
bluetooth.getPairedDevices();
// since 9; useinstead @ohos.bluetoothManager.getProfileInstance
bluetooth.getProfile(({} as any));
// since 9; useinstead @ohos.bluetoothManager.getProfileConnectionState
bluetooth.getProfileConnState(({} as any));
// since 9; useinstead @ohos.bluetoothManager.getRemoteDeviceClass
bluetooth.getRemoteDeviceClass('');
// since 9; useinstead @ohos.bluetoothManager.getRemoteDeviceName
bluetooth.getRemoteDeviceName('');
// since 9; useinstead @ohos.bluetoothManager.getState
bluetooth.getState();
// since 9; useinstead @ohos.bluetoothManager.off
bluetooth.off('bluetoothDeviceFind');
// since 9; useinstead @ohos.bluetoothManager.on
bluetooth.on('bluetoothDeviceFind', () => {});
// since 9; useinstead @ohos.bluetoothManager.pairDevice
bluetooth.pairDevice('');
// since 9; useinstead @ohos.bluetoothManager.setBluetoothScanMode
bluetooth.setBluetoothScanMode(({} as any), 0);
// since 9; useinstead @ohos.bluetoothManager.setDevicePairingConfirmation
bluetooth.setDevicePairingConfirmation('', false);
// since 9; useinstead @ohos.bluetoothManager.setLocalName
bluetooth.setLocalName('');
// since 9; useinstead @ohos.bluetoothManager.sppAccept
bluetooth.sppAccept(0, () => {});
// since 9; useinstead @ohos.bluetoothManager.sppCloseClientSocket
bluetooth.sppCloseClientSocket(0);
// since 9; useinstead @ohos.bluetoothManager.sppCloseServerSocket
bluetooth.sppCloseServerSocket(0);
// since 9; useinstead @ohos.bluetoothManager.sppConnect
bluetooth.sppConnect('', ({} as any), () => {});
// since 9; useinstead @ohos.bluetoothManager.sppListen
bluetooth.sppListen('', ({} as any), () => {});
// since 9; useinstead @ohos.bluetoothManager.sppWrite
bluetooth.sppWrite(0, ({} as any));
// since 9; useinstead @ohos.bluetoothManager.startBluetoothDiscovery
bluetooth.startBluetoothDiscovery();
// since 9; useinstead @ohos.bluetoothManager.stopBluetoothDiscovery
bluetooth.stopBluetoothDiscovery();
