// Auto-generated by scripts/gen-deprecated-usage.mjs — do not edit.
// Kit: @ohos.secureElement
// Deprecated symbols: 1 (compilable real-usage corpus; expect TS 6385/6387).
// Generated: 2026-08-15T18:18:26.091Z

import omapi from '@ohos.secureElement';

// Deprecated symbol usages.
// since 12; useinstead @ohos.secureElement.createService
omapi.newSEService('serviceState', () => {});
