// Auto-generated by scripts/gen-deprecated-usage.mjs — do not edit.
// Kit: @ohos.commonEventManager
// Deprecated symbols: 38 (compilable real-usage corpus; expect TS 6385/6387).
// Generated: 2026-08-15T18:18:26.091Z

import commonEventManager from '@ohos.commonEventManager';

// Deprecated symbol usages.
// since 20; useinstead none
const _v0 = commonEventManager.Support.COMMON_EVENT_BLUETOOTH_A2DPSINK_AUDIO_STATE_UPDATE;
// since 20; useinstead none
const _v1 = commonEventManager.Support.COMMON_EVENT_BLUETOOTH_A2DPSINK_CONNECT_STATE_UPDATE;
// since 20; useinstead none
const _v2 = commonEventManager.Support.COMMON_EVENT_BLUETOOTH_A2DPSINK_PLAYING_STATE_UPDATE;
// since 20; useinstead @ohos.commonEventManager.Support.COMMON_EVENT_BLUETOOTH_A2DPSOURCE_AVRCP_CONNECT_STATE_CHANGE
const _v3 = commonEventManager.Support.COMMON_EVENT_BLUETOOTH_A2DPSOURCE_AVRCP_CONNECT_STATE_UPDATE;
// since 20; useinstead @ohos.commonEventManager.Support.COMMON_EVENT_BLUETOOTH_A2DPSOURCE_CODEC_VALUE_CHANGE
const _v4 = commonEventManager.Support.COMMON_EVENT_BLUETOOTH_A2DPSOURCE_CODEC_VALUE_UPDATE;
// since 20; useinstead @ohos.commonEventManager.Support.COMMON_EVENT_BLUETOOTH_A2DPSOURCE_CONNECT_STATE_CHANGE
const _v5 = commonEventManager.Support.COMMON_EVENT_BLUETOOTH_A2DPSOURCE_CONNECT_STATE_UPDATE;
// since 20; useinstead none
const _v6 = commonEventManager.Support.COMMON_EVENT_BLUETOOTH_A2DPSOURCE_CURRENT_DEVICE_UPDATE;
// since 20; useinstead none
const _v7 = commonEventManager.Support.COMMON_EVENT_BLUETOOTH_A2DPSOURCE_PLAYING_STATE_UPDATE;
// since 20; useinstead none
const _v8 = commonEventManager.Support.COMMON_EVENT_BLUETOOTH_HANDSFREEUNIT_AG_CALL_STATE_UPDATE;
// since 20; useinstead none
const _v9 = commonEventManager.Support.COMMON_EVENT_BLUETOOTH_HANDSFREEUNIT_AG_COMMON_EVENT;
// since 20; useinstead none
const _v10 = commonEventManager.Support.COMMON_EVENT_BLUETOOTH_HANDSFREEUNIT_AUDIO_STATE_UPDATE;
// since 20; useinstead none
const _v11 = commonEventManager.Support.COMMON_EVENT_BLUETOOTH_HANDSFREEUNIT_CONNECT_STATE_UPDATE;
// since 20; useinstead none
const _v12 = commonEventManager.Support.COMMON_EVENT_BLUETOOTH_HANDSFREE_AG_AUDIO_STATE_UPDATE;
// since 20; useinstead @ohos.commonEventManager.Support.COMMON_EVENT_BLUETOOTH_HANDSFREE_AG_CONNECT_STATE_CHANGE
const _v13 = commonEventManager.Support.COMMON_EVENT_BLUETOOTH_HANDSFREE_AG_CONNECT_STATE_UPDATE;
// since 20; useinstead none
const _v14 = commonEventManager.Support.COMMON_EVENT_BLUETOOTH_HANDSFREE_AG_CURRENT_DEVICE_UPDATE;
// since 20; useinstead none
const _v15 = commonEventManager.Support.COMMON_EVENT_BLUETOOTH_HOST_DISCOVERY_FINISHED;
// since 20; useinstead none
const _v16 = commonEventManager.Support.COMMON_EVENT_BLUETOOTH_HOST_DISCOVERY_STARTED;
// since 20; useinstead none
const _v17 = commonEventManager.Support.COMMON_EVENT_BLUETOOTH_HOST_NAME_UPDATE;
// since 20; useinstead none
const _v18 = commonEventManager.Support.COMMON_EVENT_BLUETOOTH_HOST_REQ_DISABLE;
// since 20; useinstead none
const _v19 = commonEventManager.Support.COMMON_EVENT_BLUETOOTH_HOST_REQ_DISCOVERABLE;
// since 20; useinstead none
const _v20 = commonEventManager.Support.COMMON_EVENT_BLUETOOTH_HOST_REQ_ENABLE;
// since 20; useinstead none
const _v21 = commonEventManager.Support.COMMON_EVENT_BLUETOOTH_HOST_SCAN_MODE_UPDATE;
// since 20; useinstead none
const _v22 = commonEventManager.Support.COMMON_EVENT_BLUETOOTH_HOST_STATE_UPDATE;
// since 20; useinstead @ohos.commonEventManager.Support.COMMON_EVENT_BLUETOOTH_REMOTEDEVICE_ACL_STATE_CHANGE
const _v23 = commonEventManager.Support.COMMON_EVENT_BLUETOOTH_REMOTEDEVICE_ACL_CONNECTED;
// since 20; useinstead @ohos.commonEventManager.Support.COMMON_EVENT_BLUETOOTH_REMOTEDEVICE_ACL_STATE_CHANGE
const _v24 = commonEventManager.Support.COMMON_EVENT_BLUETOOTH_REMOTEDEVICE_ACL_DISCONNECTED;
// since 20; useinstead none
const _v25 = commonEventManager.Support.COMMON_EVENT_BLUETOOTH_REMOTEDEVICE_BATTERY_VALUE_UPDATE;
// since 20; useinstead none
const _v26 = commonEventManager.Support.COMMON_EVENT_BLUETOOTH_REMOTEDEVICE_CLASS_VALUE_UPDATE;
// since 20; useinstead none
const _v27 = commonEventManager.Support.COMMON_EVENT_BLUETOOTH_REMOTEDEVICE_CONNECT_CANCEL;
// since 20; useinstead none
const _v28 = commonEventManager.Support.COMMON_EVENT_BLUETOOTH_REMOTEDEVICE_CONNECT_REPLY;
// since 20; useinstead none
const _v29 = commonEventManager.Support.COMMON_EVENT_BLUETOOTH_REMOTEDEVICE_CONNECT_REQ;
// since 20; useinstead none
const _v30 = commonEventManager.Support.COMMON_EVENT_BLUETOOTH_REMOTEDEVICE_DISCOVERED;
// since 20; useinstead none
const _v31 = commonEventManager.Support.COMMON_EVENT_BLUETOOTH_REMOTEDEVICE_NAME_UPDATE;
// since 20; useinstead none
const _v32 = commonEventManager.Support.COMMON_EVENT_BLUETOOTH_REMOTEDEVICE_PAIRING_CANCEL;
// since 20; useinstead none
const _v33 = commonEventManager.Support.COMMON_EVENT_BLUETOOTH_REMOTEDEVICE_PAIRING_REQ;
// since 20; useinstead @ohos.commonEventManager.Support.COMMON_EVENT_BLUETOOTH_REMOTEDEVICE_PAIR_STATE_CHANGE
const _v34 = commonEventManager.Support.COMMON_EVENT_BLUETOOTH_REMOTEDEVICE_PAIR_STATE;
// since 20; useinstead none
const _v35 = commonEventManager.Support.COMMON_EVENT_BLUETOOTH_REMOTEDEVICE_SDP_RESULT;
// since 20; useinstead none
const _v36 = commonEventManager.Support.COMMON_EVENT_BLUETOOTH_REMOTEDEVICE_UUID_VALUE;
// since 10; useinstead none
const _v37 = commonEventManager.Support.COMMON_EVENT_USER_PRESENT;
