// Auto-generated by scripts/gen-deprecated-usage.mjs — do not edit.
// Kit: @ohos.effectKit
// Deprecated symbols: 1 (compilable real-usage corpus; expect TS 6385/6387).
// Generated: 2026-08-15T18:18:26.091Z

import effectKit from '@ohos.effectKit';

// Deprecated symbol usages.
// since 11; useinstead @ohos.effectKit.Filter.getEffectPixelMap
let _v0: effectKit.Filter = {} as effectKit.Filter; _v0.getPixelMap();
