// Auto-generated by scripts/gen-deprecated-usage.mjs — do not edit.
// Kit: @ohos.multimedia.avsession
// Deprecated symbols: 2 (compilable real-usage corpus; expect TS 6385/6387).
// Generated: 2026-08-15T18:18:26.091Z

import avSession from '@ohos.multimedia.avsession';

// Deprecated symbol usages.
// since 20; useinstead @ohos.multimedia.avsession.AVSession.off
let _v0: avSession.AVSession = {} as avSession.AVSession; _v0.off('playFromAssetId');
// since 20; useinstead @ohos.multimedia.avsession.AVSession.on
let _v1: avSession.AVSession = {} as avSession.AVSession; _v1.on('playFromAssetId', () => {});
