// Auto-generated by scripts/gen-deprecated-usage.mjs — do not edit.
// Kit: @ohos.abilityAccessCtrl
// Deprecated symbols: 2 (compilable real-usage corpus; expect TS 6385/6387).
// Generated: 2026-08-15T18:18:26.091Z

import abilityAccessCtrl from '@ohos.abilityAccessCtrl';
import { Context } from '@ohos.abilityAccessCtrl';

// Deprecated symbol usages.
// since 9; useinstead @ohos.abilityAccessCtrl.AtManager.checkAccessToken
let _v0: abilityAccessCtrl.AtManager = {} as abilityAccessCtrl.AtManager; _v0.verifyAccessToken(0, '');
// since 12; useinstead @ohos.app.ability.application.createModuleContext
let _v1: Context = {} as Context; _v1.createModuleContext('');
