// Auto-generated by scripts/gen-deprecated-usage.mjs — do not edit.
// Kit: @ohos.contact
// Deprecated symbols: 14 (compilable real-usage corpus; expect TS 6385/6387).
// Generated: 2026-08-15T18:18:26.091Z

import contact from '@ohos.contact';

// Deprecated symbol usages.
// since 10; useinstead @ohos.contact.addContact.addContact
contact.addContact(({} as any));
// since 10; useinstead @ohos.contact.deleteContact.deleteContact
contact.deleteContact('');
// since 10; useinstead @ohos.contact.isLocalContact.isLocalContact
contact.isLocalContact(0);
// since 10; useinstead @ohos.contact.isMyCard.isMyCard
contact.isMyCard(0);
// since 10; useinstead @ohos.contact.queryContact.queryContact
contact.queryContact('');
// since 10; useinstead @ohos.contact.queryContacts.queryContacts
contact.queryContacts();
// since 10; useinstead @ohos.contact.queryContactsByEmail.queryContactsByEmail
contact.queryContactsByEmail('');
// since 10; useinstead @ohos.contact.queryContactsByPhoneNumber.queryContactsByPhoneNumber
contact.queryContactsByPhoneNumber('');
// since 10; useinstead @ohos.contact.queryGroups.queryGroups
contact.queryGroups();
// since 10; useinstead @ohos.contact.queryHolders.queryHolders
contact.queryHolders();
// since 10; useinstead @ohos.contact.queryKey.queryKey
contact.queryKey(0);
// since 10; useinstead @ohos.contact.queryMyCard.queryMyCard
contact.queryMyCard();
// since 10; useinstead @ohos.contact.selectContact.selectContacts
contact.selectContact();
// since 10; useinstead @ohos.contact.updateContact.updateContact
contact.updateContact(({} as any));
