// Auto-generated by scripts/gen-deprecated-usage.mjs — do not edit.
// Kit: @ohos.account.distributedAccount
// Deprecated symbols: 2 (compilable real-usage corpus; expect TS 6385/6387).
// Generated: 2026-08-15T18:18:26.091Z

import distributedAccount from '@ohos.account.distributedAccount';

// Deprecated symbol usages.
// since 9; useinstead @ohos.account.distributedAccount.DistributedAccountAbility.getOsAccountDistributedInfo
let _v0: distributedAccount.DistributedAccountAbility = {} as distributedAccount.DistributedAccountAbility; _v0.queryOsAccountDistributedInfo();
// since 9; useinstead @ohos.account.distributedAccount.DistributedAccountAbility.setOsAccountDistributedInfo
let _v1: distributedAccount.DistributedAccountAbility = {} as distributedAccount.DistributedAccountAbility; _v1.updateOsAccountDistributedInfo(({} as any));
