// Auto-generated by scripts/gen-deprecated-usage.mjs — do not edit.
// Kit: @ohos.telephony.call
// Deprecated symbols: 1 (compilable real-usage corpus; expect TS 6385/6387).
// Generated: 2026-08-15T18:18:26.091Z

import call from '@ohos.telephony.call';

// Deprecated symbol usages.
// since 9; useinstead @ohos.telephony.call.dialCall
call.dial('');
