// Auto-generated by scripts/gen-deprecated-usage.mjs — do not edit.
// Kit: @ohos.app.ability.wantAgent
// Deprecated symbols: 2 (compilable real-usage corpus; expect TS 6385/6387).
// Generated: 2026-08-15T18:18:26.091Z

import wantAgent from '@ohos.app.ability.wantAgent';

// Deprecated symbol usages.
// since 11; useinstead @ohos.app.ability.wantAgent.actionType
let _v0: wantAgent.WantAgentInfo = {} as wantAgent.WantAgentInfo; const _v1 = _v0.operationType;
// since 11; useinstead @ohos.app.ability.wantAgent.actionFlags
let _v2: wantAgent.WantAgentInfo = {} as wantAgent.WantAgentInfo; const _v3 = _v2.wantAgentFlags;
