// Auto-generated by scripts/gen-deprecated-usage.mjs — do not edit.
// Kit: @ohos.arkui.dragController
// Deprecated symbols: 3 (compilable real-usage corpus; expect TS 6385/6387).
// Generated: 2026-08-15T18:18:26.091Z

import dragController from '@ohos.arkui.dragController';

// Deprecated symbol usages.
// since 18; useinstead @ohos.arkui.UIContext.DragController.createDragAction
dragController.createDragAction([], ({} as any));
// since 18; useinstead @ohos.arkui.UIContext.DragController.executeDrag
dragController.executeDrag(({} as any), ({} as any));
// since 18; useinstead @ohos.arkui.UIContext.DragController.getDragPreview
dragController.getDragPreview();
