// Auto-generated by scripts/gen-deprecated-usage.mjs — do not edit.
// Kit: @ohos.measure
// Deprecated symbols: 2 (compilable real-usage corpus; expect TS 6385/6387).
// Generated: 2026-08-15T18:18:26.091Z

import MeasureText from '@ohos.measure';

// Deprecated symbol usages.
// since 18; useinstead @ohos.arkui.UIContext.MeasureUtils.measureText
MeasureText.measureText(({} as any));
// since 18; useinstead @ohos.arkui.UIContext.MeasureUtils.measureTextSize
MeasureText.measureTextSize(({} as any));
