// Auto-generated by scripts/gen-deprecated-usage.mjs — do not edit.
// Kit: @ohos.arkui.componentSnapshot
// Deprecated symbols: 2 (compilable real-usage corpus; expect TS 6385/6387).
// Generated: 2026-08-15T18:18:26.091Z

import componentSnapshot from '@ohos.arkui.componentSnapshot';

// Deprecated symbol usages.
// since 18; useinstead @ohos.arkui.UIContext.ComponentSnapshot.createFromBuilder
componentSnapshot.createFromBuilder(({} as any));
// since 18; useinstead @ohos.arkui.UIContext.ComponentSnapshot.get
componentSnapshot.get('');
