// Auto-generated by scripts/gen-deprecated-usage.mjs — do not edit.
// Kit: @ohos.telephony.radio
// Deprecated symbols: 1 (compilable real-usage corpus; expect TS 6385/6387).
// Generated: 2026-08-15T18:18:26.091Z

import radio from '@ohos.telephony.radio';

// Deprecated symbol usages.
// since 9; useinstead @ohos.telephony.radio.isNRSupported
radio.isNrSupported();
