// Auto-generated by scripts/gen-deprecated-usage.mjs — do not edit.
// Kit: @ohos.xml
// Deprecated symbols: 1 (compilable real-usage corpus; expect TS 6385/6387).
// Generated: 2026-08-15T18:18:26.091Z

import xml from '@ohos.xml';

// Deprecated symbol usages.
// since 14; useinstead @ohos.xml.XmlPullParser.parseXml
let _v0: xml.XmlPullParser = {} as xml.XmlPullParser; _v0.parse(({} as any));
