// Auto-generated by scripts/gen-deprecated-usage.mjs — do not edit.
// Kit: @ohos.data.rdb
// Deprecated symbols: 84 (compilable real-usage corpus; expect TS 6385/6387).
// Generated: 2026-08-15T18:18:26.091Z

import rdb from '@ohos.data.rdb';

// Deprecated symbol usages.
// since 9; useinstead @ohos.data.relationalStore.
// @ohos.data.rdb.rdb: module-move (kit-level); covered by the import line
// since 9; useinstead @ohos.data.relationalStore.ResultSet
let _v0: rdb.ResultSet = {} as rdb.ResultSet;
// since 9; useinstead @ohos.data.relationalStore.RdbPredicates
const _v1 = rdb.RdbPredicates;
// since 9; useinstead @ohos.data.relationalStore.RdbPredicates.and
let _v2: rdb.RdbPredicates = {} as rdb.RdbPredicates; _v2.and();
// since 9; useinstead @ohos.data.relationalStore.RdbPredicates.beginWrap
let _v3: rdb.RdbPredicates = {} as rdb.RdbPredicates; _v3.beginWrap();
// since 9; useinstead @ohos.data.relationalStore.RdbPredicates.beginsWith
let _v4: rdb.RdbPredicates = {} as rdb.RdbPredicates; _v4.beginsWith('', '');
// since 9; useinstead @ohos.data.relationalStore.RdbPredicates.between
let _v5: rdb.RdbPredicates = {} as rdb.RdbPredicates; _v5.between('', ({} as any), ({} as any));
// since 9; useinstead @ohos.data.relationalStore.RdbPredicates.contains
let _v6: rdb.RdbPredicates = {} as rdb.RdbPredicates; _v6.contains('', '');
// since 9; useinstead @ohos.data.relationalStore.RdbPredicates.distinct
let _v7: rdb.RdbPredicates = {} as rdb.RdbPredicates; _v7.distinct();
// since 9; useinstead @ohos.data.relationalStore.RdbPredicates.endWrap
let _v8: rdb.RdbPredicates = {} as rdb.RdbPredicates; _v8.endWrap();
// since 9; useinstead @ohos.data.relationalStore.RdbPredicates.endsWith
let _v9: rdb.RdbPredicates = {} as rdb.RdbPredicates; _v9.endsWith('', '');
// since 9; useinstead @ohos.data.relationalStore.RdbPredicates.equalTo
let _v10: rdb.RdbPredicates = {} as rdb.RdbPredicates; _v10.equalTo('', ({} as any));
// since 9; useinstead @ohos.data.relationalStore.RdbPredicates.glob
let _v11: rdb.RdbPredicates = {} as rdb.RdbPredicates; _v11.glob('', '');
// since 9; useinstead @ohos.data.relationalStore.RdbPredicates.greaterThan
let _v12: rdb.RdbPredicates = {} as rdb.RdbPredicates; _v12.greaterThan('', ({} as any));
// since 9; useinstead @ohos.data.relationalStore.RdbPredicates.greaterThanOrEqualTo
let _v13: rdb.RdbPredicates = {} as rdb.RdbPredicates; _v13.greaterThanOrEqualTo('', ({} as any));
// since 9; useinstead @ohos.data.relationalStore.RdbPredicates.groupBy
let _v14: rdb.RdbPredicates = {} as rdb.RdbPredicates; _v14.groupBy([]);
// since 9; useinstead @ohos.data.relationalStore.RdbPredicates.in
let _v15: rdb.RdbPredicates = {} as rdb.RdbPredicates; _v15.in('', []);
// since 9; useinstead @ohos.data.relationalStore.RdbPredicates.inAllDevices
let _v16: rdb.RdbPredicates = {} as rdb.RdbPredicates; _v16.inAllDevices();
// since 9; useinstead @ohos.data.relationalStore.RdbPredicates.inDevices
let _v17: rdb.RdbPredicates = {} as rdb.RdbPredicates; _v17.inDevices([]);
// since 9; useinstead @ohos.data.relationalStore.RdbPredicates.indexedBy
let _v18: rdb.RdbPredicates = {} as rdb.RdbPredicates; _v18.indexedBy('');
// since 9; useinstead @ohos.data.relationalStore.RdbPredicates.isNotNull
let _v19: rdb.RdbPredicates = {} as rdb.RdbPredicates; _v19.isNotNull('');
// since 9; useinstead @ohos.data.relationalStore.RdbPredicates.isNull
let _v20: rdb.RdbPredicates = {} as rdb.RdbPredicates; _v20.isNull('');
// since 9; useinstead @ohos.data.relationalStore.RdbPredicates.lessThan
let _v21: rdb.RdbPredicates = {} as rdb.RdbPredicates; _v21.lessThan('', ({} as any));
// since 9; useinstead @ohos.data.relationalStore.RdbPredicates.lessThanOrEqualTo
let _v22: rdb.RdbPredicates = {} as rdb.RdbPredicates; _v22.lessThanOrEqualTo('', ({} as any));
// since 9; useinstead @ohos.data.relationalStore.RdbPredicates.like
let _v23: rdb.RdbPredicates = {} as rdb.RdbPredicates; _v23.like('', '');
// since 9; useinstead @ohos.data.relationalStore.RdbPredicates.limitAs
let _v24: rdb.RdbPredicates = {} as rdb.RdbPredicates; _v24.limitAs(0);
// since 9; useinstead @ohos.data.relationalStore.RdbPredicates.notBetween
let _v25: rdb.RdbPredicates = {} as rdb.RdbPredicates; _v25.notBetween('', ({} as any), ({} as any));
// since 9; useinstead @ohos.data.relationalStore.RdbPredicates.notEqualTo
let _v26: rdb.RdbPredicates = {} as rdb.RdbPredicates; _v26.notEqualTo('', ({} as any));
// since 9; useinstead @ohos.data.relationalStore.RdbPredicates.notIn
let _v27: rdb.RdbPredicates = {} as rdb.RdbPredicates; _v27.notIn('', []);
// since 9; useinstead @ohos.data.relationalStore.RdbPredicates.offsetAs
let _v28: rdb.RdbPredicates = {} as rdb.RdbPredicates; _v28.offsetAs(0);
// since 9; useinstead @ohos.data.relationalStore.RdbPredicates.or
let _v29: rdb.RdbPredicates = {} as rdb.RdbPredicates; _v29.or();
// since 9; useinstead @ohos.data.relationalStore.RdbPredicates.orderByAsc
let _v30: rdb.RdbPredicates = {} as rdb.RdbPredicates; _v30.orderByAsc('');
// since 9; useinstead @ohos.data.relationalStore.RdbPredicates.orderByDesc
let _v31: rdb.RdbPredicates = {} as rdb.RdbPredicates; _v31.orderByDesc('');
// since 9; useinstead @ohos.data.relationalStore.RdbStore
let _v32: rdb.RdbStore = {} as rdb.RdbStore;
// since 9; useinstead @ohos.data.relationalStore.RdbStore.batchInsert
let _v33: rdb.RdbStore = {} as rdb.RdbStore; _v33.batchInsert('', []);
// since 9; useinstead @ohos.data.relationalStore.RdbStore.beginTransaction
let _v34: rdb.RdbStore = {} as rdb.RdbStore; _v34.beginTransaction();
// since 9; useinstead @ohos.data.relationalStore.RdbStore.commit
let _v35: rdb.RdbStore = {} as rdb.RdbStore; _v35.commit();
// since 9; useinstead @ohos.data.relationalStore.RdbStore.delete
let _v36: rdb.RdbStore = {} as rdb.RdbStore; _v36.delete(({} as any));
// since 9; useinstead @ohos.data.relationalStore.RdbStore.executeSql
let _v37: rdb.RdbStore = {} as rdb.RdbStore; _v37.executeSql('');
// since 9; useinstead @ohos.data.relationalStore.RdbStore.insert
let _v38: rdb.RdbStore = {} as rdb.RdbStore; _v38.insert('', ({} as any));
// since 9; useinstead @ohos.data.relationalStore.RdbStore.obtainDistributedTableName
let _v39: rdb.RdbStore = {} as rdb.RdbStore; _v39.obtainDistributedTableName('', '');
// since 9; useinstead @ohos.data.relationalStore.RdbStore.off
let _v40: rdb.RdbStore = {} as rdb.RdbStore; _v40.off('dataChange', ({} as any), () => {});
// since 9; useinstead @ohos.data.relationalStore.RdbStore.on
let _v41: rdb.RdbStore = {} as rdb.RdbStore; _v41.on('dataChange', ({} as any), () => {});
// since 9; useinstead @ohos.data.relationalStore.RdbStore.query
let _v42: rdb.RdbStore = {} as rdb.RdbStore; _v42.query(({} as any));
// since 9; useinstead @ohos.data.relationalStore.RdbStore.querySql
let _v43: rdb.RdbStore = {} as rdb.RdbStore; _v43.querySql('');
// since 9; useinstead @ohos.data.relationalStore.RdbStore.rollBack
let _v44: rdb.RdbStore = {} as rdb.RdbStore; _v44.rollBack();
// since 9; useinstead @ohos.data.relationalStore.RdbStore.setDistributedTables
let _v45: rdb.RdbStore = {} as rdb.RdbStore; _v45.setDistributedTables([]);
// since 9; useinstead @ohos.data.relationalStore.RdbStore.sync
let _v46: rdb.RdbStore = {} as rdb.RdbStore; _v46.sync(({} as any), ({} as any));
// since 9; useinstead @ohos.data.relationalStore.RdbStore.update
let _v47: rdb.RdbStore = {} as rdb.RdbStore; _v47.update(({} as any), ({} as any));
// since 9; useinstead none
let _v48: rdb.ResultSet = {} as rdb.ResultSet;
// since 9; useinstead @ohos.data.relationalStore.StoreConfig
let _v49: rdb.StoreConfig = {} as rdb.StoreConfig;
// since 9; useinstead @ohos.data.relationalStore.StoreConfig
let _v50: rdb.StoreConfig = {} as rdb.StoreConfig; const _v51 = _v50.name;
// since 9; useinstead @ohos.data.relationalStore.SubscribeType
const _v52 = rdb.SubscribeType;
// since 9; useinstead @ohos.data.relationalStore.SubscribeType.SUBSCRIBE_TYPE_REMOTE
const _v53 = rdb.SubscribeType.SUBSCRIBE_TYPE_REMOTE;
// since 9; useinstead @ohos.data.relationalStore.SyncMode
const _v54 = rdb.SyncMode;
// since 9; useinstead @ohos.data.relationalStore.SyncMode.SYNC_MODE_PULL
const _v55 = rdb.SyncMode.SYNC_MODE_PULL;
// since 9; useinstead @ohos.data.relationalStore.SyncMode.SYNC_MODE_PUSH
const _v56 = rdb.SyncMode.SYNC_MODE_PUSH;
// since 9; useinstead @ohos.data.relationalStore.ValueType
let _v57: rdb.ValueType = {} as rdb.ValueType;
// since 9; useinstead @ohos.data.relationalStore.ValuesBucket
let _v58: rdb.ValuesBucket = {} as rdb.ValuesBucket;
// since 9; useinstead @ohos.data.relationalStore.ResultSet.close
let _v59: rdb.ResultSet = {} as rdb.ResultSet; _v59.close();
// since 9; useinstead @ohos.data.relationalStore.ResultSet.columnCount
let _v60: rdb.ResultSet = {} as rdb.ResultSet; const _v61 = _v60.columnCount;
// since 9; useinstead @ohos.data.relationalStore.ResultSet.columnNames
let _v62: rdb.ResultSet = {} as rdb.ResultSet; const _v63 = _v62.columnNames;
// since 9; useinstead @ohos.data.relationalStore.deleteRdbStore
rdb.deleteRdbStore(({} as any), '');
// since 9; useinstead @ohos.data.relationalStore.ResultSet.getBlob
let _v64: rdb.ResultSet = {} as rdb.ResultSet; _v64.getBlob(0);
// since 9; useinstead @ohos.data.relationalStore.ResultSet.getColumnIndex
let _v65: rdb.ResultSet = {} as rdb.ResultSet; _v65.getColumnIndex('');
// since 9; useinstead @ohos.data.relationalStore.ResultSet.getColumnName
let _v66: rdb.ResultSet = {} as rdb.ResultSet; _v66.getColumnName(0);
// since 9; useinstead @ohos.data.relationalStore.ResultSet.getDouble
let _v67: rdb.ResultSet = {} as rdb.ResultSet; _v67.getDouble(0);
// since 9; useinstead @ohos.data.relationalStore.ResultSet.getLong
let _v68: rdb.ResultSet = {} as rdb.ResultSet; _v68.getLong(0);
// since 9; useinstead @ohos.data.relationalStore.getRdbStore
rdb.getRdbStore(({} as any), ({} as any), 0);
// since 9; useinstead @ohos.data.relationalStore.ResultSet.getString
let _v69: rdb.ResultSet = {} as rdb.ResultSet; _v69.getString(0);
// since 9; useinstead @ohos.data.relationalStore.ResultSet.goTo
let _v70: rdb.ResultSet = {} as rdb.ResultSet; _v70.goTo(0);
// since 9; useinstead @ohos.data.relationalStore.ResultSet.goToFirstRow
let _v71: rdb.ResultSet = {} as rdb.ResultSet; _v71.goToFirstRow();
// since 9; useinstead @ohos.data.relationalStore.ResultSet.goToLastRow
let _v72: rdb.ResultSet = {} as rdb.ResultSet; _v72.goToLastRow();
// since 9; useinstead @ohos.data.relationalStore.ResultSet.goToNextRow
let _v73: rdb.ResultSet = {} as rdb.ResultSet; _v73.goToNextRow();
// since 9; useinstead @ohos.data.relationalStore.ResultSet.goToPreviousRow
let _v74: rdb.ResultSet = {} as rdb.ResultSet; _v74.goToPreviousRow();
// since 9; useinstead @ohos.data.relationalStore.ResultSet.goToRow
let _v75: rdb.ResultSet = {} as rdb.ResultSet; _v75.goToRow(0);
// since 9; useinstead @ohos.data.relationalStore.ResultSet.isAtFirstRow
let _v76: rdb.ResultSet = {} as rdb.ResultSet; const _v77 = _v76.isAtFirstRow;
// since 9; useinstead @ohos.data.relationalStore.ResultSet.isAtLastRow
let _v78: rdb.ResultSet = {} as rdb.ResultSet; const _v79 = _v78.isAtLastRow;
// since 9; useinstead @ohos.data.relationalStore.ResultSet.isClosed
let _v80: rdb.ResultSet = {} as rdb.ResultSet; const _v81 = _v80.isClosed;
// since 9; useinstead @ohos.data.relationalStore.ResultSet.isColumnNull
let _v82: rdb.ResultSet = {} as rdb.ResultSet; _v82.isColumnNull(0);
// since 9; useinstead @ohos.data.relationalStore.ResultSet.isEnded
let _v83: rdb.ResultSet = {} as rdb.ResultSet; const _v84 = _v83.isEnded;
// since 9; useinstead @ohos.data.relationalStore.ResultSet.isStarted
let _v85: rdb.ResultSet = {} as rdb.ResultSet; const _v86 = _v85.isStarted;
// since 9; useinstead @ohos.data.relationalStore.ResultSet.rowCount
let _v87: rdb.ResultSet = {} as rdb.ResultSet; const _v88 = _v87.rowCount;
// since 9; useinstead @ohos.data.relationalStore.ResultSet.rowIndex
let _v89: rdb.ResultSet = {} as rdb.ResultSet; const _v90 = _v89.rowIndex;
