// Auto-generated by scripts/gen-deprecated-usage.mjs — do not edit.
// Kit: @ohos.thermal
// Deprecated symbols: 3 (compilable real-usage corpus; expect TS 6385/6387).
// Generated: 2026-08-15T18:18:26.091Z

import thermal from '@ohos.thermal';

// Deprecated symbol usages.
// since 9; useinstead @ohos.thermal.getLevel
thermal.getThermalLevel();
// since 9; useinstead @ohos.thermal.registerThermalLevelCallback
thermal.subscribeThermalLevel(() => {});
// since 9; useinstead @ohos.thermal.unregisterThermalLevelCallback
thermal.unsubscribeThermalLevel();
