// Auto-generated by scripts/gen-deprecated-usage.mjs — do not edit.
// Kit: @ohos.ability.featureAbility
// Deprecated symbols: 3 (compilable real-usage corpus; expect TS 6385/6387).
// Generated: 2026-08-15T18:18:26.091Z

import featureAbility from '@ohos.ability.featureAbility';

// Deprecated symbol usages.
// since 7; useinstead none
let _v0: featureAbility.Context = {} as featureAbility.Context; _v0.getExternalCacheDir();
// since 9; useinstead @ohos.window.WindowStage.setShowOnLockScreen
let _v1: featureAbility.Context = {} as featureAbility.Context; _v1.setShowOnLockScreen(false);
// since 12; useinstead @ohos.window.Window.setWakeUpScreen
let _v2: featureAbility.Context = {} as featureAbility.Context; _v2.setWakeUpScreen(false);
