// Auto-generated by scripts/gen-deprecated-usage.mjs — do not edit.
// Kit: @ohos.account.osAccount
// Deprecated symbols: 23 (compilable real-usage corpus; expect TS 6385/6387).
// Generated: 2026-08-15T18:18:26.091Z

import osAccount from '@ohos.account.osAccount';

// Deprecated symbol usages.
// since 11; useinstead none
let _v0: osAccount.AccountManager = {} as osAccount.AccountManager; _v0.checkOsAccountActivated(0);
// since 11; useinstead none
let _v1: osAccount.AccountManager = {} as osAccount.AccountManager; _v1.checkOsAccountConstraintEnabled(0, '');
// since 11; useinstead none
let _v2: osAccount.AccountManager = {} as osAccount.AccountManager; _v2.checkOsAccountVerified();
// since 9; useinstead @ohos.account.osAccount.AccountManager.getOsAccountCount
let _v3: osAccount.AccountManager = {} as osAccount.AccountManager; _v3.getCreatedOsAccountsCount();
// since 11; useinstead none
let _v4: osAccount.AccountManager = {} as osAccount.AccountManager; _v4.getCurrentOsAccount();
// since 9; useinstead @ohos.account.osAccount.AccountManager.queryDistributedVirtualDeviceId
let _v5: osAccount.AccountManager = {} as osAccount.AccountManager; _v5.getDistributedVirtualDeviceId();
// since 9; useinstead @ohos.account.osAccount.AccountManager.getOsAccountConstraints
let _v6: osAccount.AccountManager = {} as osAccount.AccountManager; _v6.getOsAccountAllConstraints(0);
// since 11; useinstead none
let _v7: osAccount.AccountManager = {} as osAccount.AccountManager; _v7.getOsAccountConstraints(0);
// since 9; useinstead @ohos.account.osAccount.AccountManager.getOsAccountLocalIdForSerialNumber
let _v8: osAccount.AccountManager = {} as osAccount.AccountManager; _v8.getOsAccountLocalIdBySerialNumber(0);
// since 9; useinstead @ohos.account.osAccount.AccountManager.getOsAccountLocalIdForDomain
let _v9: osAccount.AccountManager = {} as osAccount.AccountManager; _v9.getOsAccountLocalIdFromDomain(({} as any));
// since 9; useinstead @ohos.account.osAccount.AccountManager.getOsAccountLocalId
let _v10: osAccount.AccountManager = {} as osAccount.AccountManager; _v10.getOsAccountLocalIdFromProcess();
// since 9; useinstead @ohos.account.osAccount.AccountManager.getOsAccountLocalIdForUid
let _v11: osAccount.AccountManager = {} as osAccount.AccountManager; _v11.getOsAccountLocalIdFromUid(0);
// since 9; useinstead @ohos.account.osAccount.AccountManager.getOsAccountType
let _v12: osAccount.AccountManager = {} as osAccount.AccountManager; _v12.getOsAccountTypeFromProcess();
// since 9; useinstead @ohos.account.osAccount.AccountManager.getSerialNumberForOsAccountLocalId
let _v13: osAccount.AccountManager = {} as osAccount.AccountManager; _v13.getSerialNumberByOsAccountLocalId(0);
// since 9; useinstead @ohos.account.osAccount.AccountManager.checkMultiOsAccountEnabled
let _v14: osAccount.AccountManager = {} as osAccount.AccountManager; _v14.isMultiOsAccountEnable();
// since 9; useinstead @ohos.account.osAccount.AccountManager.checkOsAccountActivated
let _v15: osAccount.AccountManager = {} as osAccount.AccountManager; _v15.isOsAccountActived(0);
// since 9; useinstead @ohos.account.osAccount.AccountManager.checkOsAccountConstraintEnabled
let _v16: osAccount.AccountManager = {} as osAccount.AccountManager; _v16.isOsAccountConstraintEnable(0, '');
// since 9; useinstead @ohos.account.osAccount.AccountManager.checkOsAccountVerified
let _v17: osAccount.AccountManager = {} as osAccount.AccountManager; _v17.isOsAccountVerified();
// since 9; useinstead @ohos.account.osAccount.AccountManager.checkOsAccountTestable
let _v18: osAccount.AccountManager = {} as osAccount.AccountManager; _v18.isTestOsAccount();
// since 9; useinstead @ohos.account.osAccount.AccountManager.getActivatedOsAccountLocalIds
let _v19: osAccount.AccountManager = {} as osAccount.AccountManager; _v19.queryActivatedOsAccountIds();
// since 9; useinstead @ohos.account.osAccount.AccountManager.getCurrentOsAccount
let _v20: osAccount.AccountManager = {} as osAccount.AccountManager; _v20.queryCurrentOsAccount();
// since 11; useinstead @ohos.account.osAccount.OsAccountInfo.isActivated
let _v21: osAccount.OsAccountInfo = {} as osAccount.OsAccountInfo; const _v22 = _v21.isActived;
// since 11; useinstead @ohos.account.osAccount.OsAccountInfo.isUnlocked
let _v23: osAccount.OsAccountInfo = {} as osAccount.OsAccountInfo; const _v24 = _v23.isVerified;
