// Auto-generated by scripts/gen-deprecated-usage.mjs — do not edit.
// Kit: @ohos.prompt
// Deprecated symbols: 22 (compilable real-usage corpus; expect TS 6385/6387).
// Generated: 2026-08-15T18:18:26.091Z

import prompt from '@ohos.prompt';

// Deprecated symbol usages.
// since 9; useinstead @ohos.promptAction.
// @ohos.prompt.prompt: module-move (kit-level); covered by the import line
// since 9; useinstead @ohos.promptAction.ActionMenuOptions
let _v0: prompt.ActionMenuOptions = {} as prompt.ActionMenuOptions;
// since 9; useinstead @ohos.promptAction.ActionMenuOptions.buttons
let _v1: prompt.ActionMenuOptions = {} as prompt.ActionMenuOptions; const _v2 = _v1.buttons;
// since 9; useinstead @ohos.promptAction.ActionMenuOptions.title
let _v3: prompt.ActionMenuOptions = {} as prompt.ActionMenuOptions; const _v4 = _v3.title;
// since 9; useinstead @ohos.promptAction.ActionMenuSuccessResponse
let _v5: prompt.ActionMenuSuccessResponse = {} as prompt.ActionMenuSuccessResponse;
// since 9; useinstead @ohos.promptAction.ActionMenuSuccessResponse.index
let _v6: prompt.ActionMenuSuccessResponse = {} as prompt.ActionMenuSuccessResponse; const _v7 = _v6.index;
// since 9; useinstead @ohos.promptAction.Button
let _v8: prompt.Button = {} as prompt.Button;
// since 9; useinstead @ohos.promptAction.Button.color
let _v9: prompt.Button = {} as prompt.Button; const _v10 = _v9.color;
// since 9; useinstead @ohos.promptAction.Button.text
let _v11: prompt.Button = {} as prompt.Button; const _v12 = _v11.text;
// since 9; useinstead @ohos.promptAction.ShowDialogOptions
let _v13: prompt.ShowDialogOptions = {} as prompt.ShowDialogOptions;
// since 9; useinstead @ohos.promptAction.ShowDialogOptions.buttons
let _v14: prompt.ShowDialogOptions = {} as prompt.ShowDialogOptions; const _v15 = _v14.buttons;
// since 9; useinstead @ohos.promptAction.ShowDialogOptions.message
let _v16: prompt.ShowDialogOptions = {} as prompt.ShowDialogOptions; const _v17 = _v16.message;
// since 9; useinstead @ohos.promptAction.ShowDialogOptions.title
let _v18: prompt.ShowDialogOptions = {} as prompt.ShowDialogOptions; const _v19 = _v18.title;
// since 9; useinstead @ohos.promptAction.ShowDialogSuccessResponse
let _v20: prompt.ShowDialogSuccessResponse = {} as prompt.ShowDialogSuccessResponse;
// since 9; useinstead @ohos.promptAction.ShowDialogSuccessResponse.index
let _v21: prompt.ShowDialogSuccessResponse = {} as prompt.ShowDialogSuccessResponse; const _v22 = _v21.index;
// since 9; useinstead @ohos.promptAction.ShowToastOptions
let _v23: prompt.ShowToastOptions = {} as prompt.ShowToastOptions;
// since 9; useinstead @ohos.promptAction.ShowToastOptions.bottom
let _v24: prompt.ShowToastOptions = {} as prompt.ShowToastOptions; const _v25 = _v24.bottom;
// since 9; useinstead @ohos.promptAction.ShowToastOptions.duration
let _v26: prompt.ShowToastOptions = {} as prompt.ShowToastOptions; const _v27 = _v26.duration;
// since 9; useinstead @ohos.promptAction.ShowToastOptions.message
let _v28: prompt.ShowToastOptions = {} as prompt.ShowToastOptions; const _v29 = _v28.message;
// since 9; useinstead @ohos.arkui.UIContext.PromptAction.showActionMenu
prompt.showActionMenu(({} as any));
// since 9; useinstead @ohos.arkui.UIContext.PromptAction.showDialog
prompt.showDialog(({} as any));
// since 9; useinstead @ohos.arkui.UIContext.PromptAction.showToast
prompt.showToast(({} as any));
