// Auto-generated by scripts/gen-deprecated-usage.mjs — do not edit.
// Kit: @ohos.telephony.sms
// Deprecated symbols: 1 (compilable real-usage corpus; expect TS 6385/6387).
// Generated: 2026-08-15T18:18:26.091Z

import sms from '@ohos.telephony.sms';

// Deprecated symbol usages.
// since 10; useinstead @ohos.telephony.sms.sendShortMessage
sms.sendMessage(({} as any));
