// Auto-generated by scripts/gen-deprecated-usage.mjs — do not edit.
// Kit: @ohos.ability.wantConstant
// Deprecated symbols: 48 (compilable real-usage corpus; expect TS 6385/6387).
// Generated: 2026-08-15T18:18:26.091Z

import wantConstant from '@ohos.ability.wantConstant';

// Deprecated symbol usages.
// since 9; useinstead @ohos.app.ability.wantConstant.
// @ohos.ability.wantConstant.wantConstant: module-move (kit-level); covered by the import line
// since 9; useinstead none
const _v0 = wantConstant.Action;
// since 9; useinstead none
const _v1 = wantConstant.Action.ACTION_APPLICATION_DETAILS_SETTINGS;
// since 9; useinstead none
const _v2 = wantConstant.Action.ACTION_APP_ACCOUNT_OAUTH;
// since 9; useinstead none
const _v3 = wantConstant.Action.ACTION_CHOOSE;
// since 9; useinstead none
const _v4 = wantConstant.Action.ACTION_DIAL;
// since 9; useinstead none
const _v5 = wantConstant.Action.ACTION_DISMISS_ALARM;
// since 9; useinstead none
const _v6 = wantConstant.Action.ACTION_DISMISS_TIMER;
// since 9; useinstead none
const _v7 = wantConstant.Action.ACTION_EDIT_DATA;
// since 9; useinstead none
const _v8 = wantConstant.Action.ACTION_FILE_SELECT;
// since 9; useinstead none
const _v9 = wantConstant.Action.ACTION_HOME;
// since 9; useinstead none
const _v10 = wantConstant.Action.ACTION_IMAGE_CAPTURE;
// since 9; useinstead none
const _v11 = wantConstant.Action.ACTION_MANAGE_APPLICATIONS_SETTINGS;
// since 9; useinstead none
const _v12 = wantConstant.Action.ACTION_SCAN_MEDIA_FILE;
// since 9; useinstead none
const _v13 = wantConstant.Action.ACTION_SEARCH;
// since 9; useinstead none
const _v14 = wantConstant.Action.ACTION_SELECT;
// since 9; useinstead none
const _v15 = wantConstant.Action.ACTION_SEND_DATA;
// since 9; useinstead none
const _v16 = wantConstant.Action.ACTION_SEND_MULTIPLE_DATA;
// since 9; useinstead none
const _v17 = wantConstant.Action.ACTION_SEND_SMS;
// since 9; useinstead none
const _v18 = wantConstant.Action.ACTION_SET_ALARM;
// since 9; useinstead none
const _v19 = wantConstant.Action.ACTION_SHOW_ALARMS;
// since 9; useinstead none
const _v20 = wantConstant.Action.ACTION_SNOOZE_ALARM;
// since 9; useinstead none
const _v21 = wantConstant.Action.ACTION_VIDEO_CAPTURE;
// since 9; useinstead none
const _v22 = wantConstant.Action.ACTION_VIEW_DATA;
// since 9; useinstead none
const _v23 = wantConstant.Action.ACTION_WIRELESS_SETTINGS;
// since 9; useinstead none
const _v24 = wantConstant.Action.INTENT_PARAMS_INTENT;
// since 9; useinstead none
const _v25 = wantConstant.Action.INTENT_PARAMS_TITLE;
// since 9; useinstead none
const _v26 = wantConstant.Action.PARAMS_STREAM;
// since 9; useinstead none
const _v27 = wantConstant.Entity;
// since 9; useinstead none
const _v28 = wantConstant.Entity.ENTITY_BROWSABLE;
// since 9; useinstead none
const _v29 = wantConstant.Entity.ENTITY_DEFAULT;
// since 9; useinstead none
const _v30 = wantConstant.Entity.ENTITY_HOME;
// since 9; useinstead none
const _v31 = wantConstant.Entity.ENTITY_VIDEO;
// since 9; useinstead none
const _v32 = wantConstant.Entity.ENTITY_VOICE;
// since 9; useinstead @ohos.app.ability.wantConstant.Flags
const _v33 = wantConstant.Flags;
// since 9; useinstead none
const _v34 = wantConstant.Flags.FLAG_ABILITYSLICE_MULTI_DEVICE;
// since 9; useinstead none
const _v35 = wantConstant.Flags.FLAG_ABILITY_CLEAR_MISSION;
// since 9; useinstead none
const _v36 = wantConstant.Flags.FLAG_ABILITY_CONTINUATION;
// since 9; useinstead none
const _v37 = wantConstant.Flags.FLAG_ABILITY_FORM_ENABLED;
// since 9; useinstead none
const _v38 = wantConstant.Flags.FLAG_ABILITY_FORWARD_RESULT;
// since 9; useinstead none
const _v39 = wantConstant.Flags.FLAG_ABILITY_MISSION_TOP;
// since 9; useinstead none
const _v40 = wantConstant.Flags.FLAG_ABILITY_NEW_MISSION;
// since 9; useinstead @ohos.app.ability.wantConstant.Flags.FLAG_AUTH_READ_URI_PERMISSION
const _v41 = wantConstant.Flags.FLAG_AUTH_READ_URI_PERMISSION;
// since 9; useinstead @ohos.app.ability.wantConstant.Flags.FLAG_AUTH_WRITE_URI_PERMISSION
const _v42 = wantConstant.Flags.FLAG_AUTH_WRITE_URI_PERMISSION;
// since 9; useinstead @ohos.app.ability.wantConstant.Flags.FLAG_INSTALL_ON_DEMAND
const _v43 = wantConstant.Flags.FLAG_INSTALL_ON_DEMAND;
// since 9; useinstead none
const _v44 = wantConstant.Flags.FLAG_INSTALL_WITH_BACKGROUND_MODE;
// since 9; useinstead none
const _v45 = wantConstant.Flags.FLAG_NOT_OHOS_COMPONENT;
// since 9; useinstead none
const _v46 = wantConstant.Flags.FLAG_START_FOREGROUND_ABILITY;
