// Auto-generated by scripts/gen-deprecated-usage.mjs — do not edit.
// Kit: @ohos.statfs
// Deprecated symbols: 3 (compilable real-usage corpus; expect TS 6385/6387).
// Generated: 2026-08-15T18:18:26.091Z

import Statfs from '@ohos.statfs';

// Deprecated symbol usages.
// since 9; useinstead @ohos.file.statvfs.statfs
// @ohos.statfs.Statfs: module-move (kit-level); covered by the import line
// since 9; useinstead @ohos.file.statvfs.getFreeSize
Statfs.getFreeBytes('');
// since 9; useinstead @ohos.file.statvfs.getTotalSize
Statfs.getTotalBytes('');
