// Auto-generated by scripts/gen-deprecated-usage.mjs — do not edit.
// Kit: @ohos.screenLock
// Deprecated symbols: 3 (compilable real-usage corpus; expect TS 6385/6387).
// Generated: 2026-08-15T18:18:26.091Z

import screenLock from '@ohos.screenLock';

// Deprecated symbol usages.
// since 9; useinstead none
screenLock.isScreenLocked();
// since 9; useinstead none
screenLock.isSecureMode();
// since 9; useinstead none
screenLock.unlockScreen();
