// Auto-generated by scripts/gen-deprecated-usage.mjs — do not edit.
// Kit: @ohos.rpc
// Deprecated symbols: 108 (compilable real-usage corpus; expect TS 6385/6387).
// Generated: 2026-08-15T18:18:26.091Z

import rpc from '@ohos.rpc';

// Deprecated symbol usages.
// since 9; useinstead @ohos.rpc.Ashmem.create
rpc.Ashmem.createAshmem('', 0);
// since 9; useinstead @ohos.rpc.Ashmem.create
rpc.Ashmem.createAshmemFromExisting(({} as any));
// since 9; useinstead @ohos.rpc.Ashmem.mapTypedAshmem
let _v0: rpc.Ashmem = {} as rpc.Ashmem; _v0.mapAshmem(0);
// since 9; useinstead @ohos.rpc.Ashmem.mapReadWriteAshmem
let _v1: rpc.Ashmem = {} as rpc.Ashmem; _v1.mapReadAndWriteAshmem();
// since 9; useinstead @ohos.rpc.Ashmem.mapReadonlyAshmem
let _v2: rpc.Ashmem = {} as rpc.Ashmem; _v2.mapReadOnlyAshmem();
// since 11; useinstead @ohos.rpc.Ashmem.readDataFromAshmem
let _v3: rpc.Ashmem = {} as rpc.Ashmem; _v3.readAshmem(0, 0);
// since 9; useinstead @ohos.rpc.Ashmem.readAshmem
let _v4: rpc.Ashmem = {} as rpc.Ashmem; _v4.readFromAshmem(0, 0);
// since 9; useinstead @ohos.rpc.Ashmem.setProtectionType
let _v5: rpc.Ashmem = {} as rpc.Ashmem; _v5.setProtection(0);
// since 11; useinstead @ohos.rpc.Ashmem.writeDataToAshmem
let _v6: rpc.Ashmem = {} as rpc.Ashmem; _v6.writeAshmem([], 0, 0);
// since 9; useinstead @ohos.rpc.Ashmem.writeAshmem
let _v7: rpc.Ashmem = {} as rpc.Ashmem; _v7.writeToAshmem([], 0, 0);
// since 9; useinstead @ohos.rpc.IPCSkeleton.flushCmdBuffer
rpc.IPCSkeleton.flushCommands(({} as any));
// since 9; useinstead @ohos.rpc.IPCSkeleton.restoreCallingIdentity
rpc.IPCSkeleton.setCallingIdentity('');
// since 9; useinstead @ohos.rpc.IRemoteObject.registerDeathRecipient
let _v8: rpc.IRemoteObject = {} as rpc.IRemoteObject; _v8.addDeathRecipient(({} as any), 0);
// since 9; useinstead @ohos.rpc.IRemoteObject.getDescriptor
let _v9: rpc.IRemoteObject = {} as rpc.IRemoteObject; _v9.getInterfaceDescriptor();
// since 9; useinstead @ohos.rpc.IRemoteObject.getLocalInterface
let _v10: rpc.IRemoteObject = {} as rpc.IRemoteObject; _v10.queryLocalInterface('');
// since 9; useinstead @ohos.rpc.IRemoteObject.unregisterDeathRecipient
let _v11: rpc.IRemoteObject = {} as rpc.IRemoteObject; _v11.removeDeathRecipient(({} as any), 0);
// since 9; useinstead @ohos.rpc.IRemoteObject.sendMessageRequest
let _v12: rpc.IRemoteObject = {} as rpc.IRemoteObject; _v12.sendRequest(0, ({} as any), ({} as any), ({} as any));
// since 9; useinstead @ohos.rpc.MessageSequence
const _v13 = rpc.MessageParcel;
// since 9; useinstead @ohos.rpc.MessageSequence.closeFileDescriptor
rpc.MessageParcel.closeFileDescriptor(0);
// since 9; useinstead @ohos.rpc.MessageSequence.containFileDescriptors
let _v14: rpc.MessageParcel = {} as rpc.MessageParcel; _v14.containFileDescriptors();
// since 9; useinstead @ohos.rpc.MessageSequence.create
rpc.MessageParcel.create();
// since 9; useinstead @ohos.rpc.MessageSequence.dupFileDescriptor
rpc.MessageParcel.dupFileDescriptor(0);
// since 9; useinstead @ohos.rpc.MessageSequence.getCapacity
let _v15: rpc.MessageParcel = {} as rpc.MessageParcel; _v15.getCapacity();
// since 9; useinstead @ohos.rpc.MessageSequence.getRawDataCapacity
let _v16: rpc.MessageParcel = {} as rpc.MessageParcel; _v16.getRawDataCapacity();
// since 9; useinstead @ohos.rpc.MessageSequence.getReadPosition
let _v17: rpc.MessageParcel = {} as rpc.MessageParcel; _v17.getReadPosition();
// since 9; useinstead @ohos.rpc.MessageSequence.getReadableBytes
let _v18: rpc.MessageParcel = {} as rpc.MessageParcel; _v18.getReadableBytes();
// since 9; useinstead @ohos.rpc.MessageSequence.getSize
let _v19: rpc.MessageParcel = {} as rpc.MessageParcel; _v19.getSize();
// since 9; useinstead @ohos.rpc.MessageSequence.getWritableBytes
let _v20: rpc.MessageParcel = {} as rpc.MessageParcel; _v20.getWritableBytes();
// since 9; useinstead @ohos.rpc.MessageSequence.getWritePosition
let _v21: rpc.MessageParcel = {} as rpc.MessageParcel; _v21.getWritePosition();
// since 9; useinstead @ohos.rpc.MessageSequence.readAshmem
let _v22: rpc.MessageParcel = {} as rpc.MessageParcel; _v22.readAshmem();
// since 9; useinstead @ohos.rpc.MessageSequence.readBoolean
let _v23: rpc.MessageParcel = {} as rpc.MessageParcel; _v23.readBoolean();
// since 9; useinstead @ohos.rpc.MessageSequence.readBooleanArray
let _v24: rpc.MessageParcel = {} as rpc.MessageParcel; _v24.readBooleanArray();
// since 9; useinstead @ohos.rpc.MessageSequence.readByte
let _v25: rpc.MessageParcel = {} as rpc.MessageParcel; _v25.readByte();
// since 9; useinstead @ohos.rpc.MessageSequence.readByteArray
let _v26: rpc.MessageParcel = {} as rpc.MessageParcel; _v26.readByteArray();
// since 9; useinstead @ohos.rpc.MessageSequence.readChar
let _v27: rpc.MessageParcel = {} as rpc.MessageParcel; _v27.readChar();
// since 9; useinstead @ohos.rpc.MessageSequence.readCharArray
let _v28: rpc.MessageParcel = {} as rpc.MessageParcel; _v28.readCharArray();
// since 9; useinstead @ohos.rpc.MessageSequence.readDouble
let _v29: rpc.MessageParcel = {} as rpc.MessageParcel; _v29.readDouble();
// since 9; useinstead @ohos.rpc.MessageSequence.readDoubleArray
let _v30: rpc.MessageParcel = {} as rpc.MessageParcel; _v30.readDoubleArray();
// since 9; useinstead @ohos.rpc.MessageSequence.readException
let _v31: rpc.MessageParcel = {} as rpc.MessageParcel; _v31.readException();
// since 9; useinstead @ohos.rpc.MessageSequence.readFileDescriptor
let _v32: rpc.MessageParcel = {} as rpc.MessageParcel; _v32.readFileDescriptor();
// since 9; useinstead @ohos.rpc.MessageSequence.readFloat
let _v33: rpc.MessageParcel = {} as rpc.MessageParcel; _v33.readFloat();
// since 9; useinstead @ohos.rpc.MessageSequence.readFloatArray
let _v34: rpc.MessageParcel = {} as rpc.MessageParcel; _v34.readFloatArray();
// since 9; useinstead @ohos.rpc.MessageSequence.readInt
let _v35: rpc.MessageParcel = {} as rpc.MessageParcel; _v35.readInt();
// since 9; useinstead @ohos.rpc.MessageSequence.readIntArray
let _v36: rpc.MessageParcel = {} as rpc.MessageParcel; _v36.readIntArray();
// since 9; useinstead @ohos.rpc.MessageSequence.readInterfaceToken
let _v37: rpc.MessageParcel = {} as rpc.MessageParcel; _v37.readInterfaceToken();
// since 9; useinstead @ohos.rpc.MessageSequence.readLong
let _v38: rpc.MessageParcel = {} as rpc.MessageParcel; _v38.readLong();
// since 9; useinstead @ohos.rpc.MessageSequence.readLongArray
let _v39: rpc.MessageParcel = {} as rpc.MessageParcel; _v39.readLongArray();
// since 9; useinstead @ohos.rpc.MessageSequence.readRawData
let _v40: rpc.MessageParcel = {} as rpc.MessageParcel; _v40.readRawData(0);
// since 9; useinstead @ohos.rpc.MessageSequence.readRemoteObject
let _v41: rpc.MessageParcel = {} as rpc.MessageParcel; _v41.readRemoteObject();
// since 9; useinstead @ohos.rpc.MessageSequence.readRemoteObjectArray
let _v42: rpc.MessageParcel = {} as rpc.MessageParcel; _v42.readRemoteObjectArray();
// since 9; useinstead @ohos.rpc.MessageSequence.readParcelable
let _v43: rpc.MessageParcel = {} as rpc.MessageParcel; _v43.readSequenceable(({} as any));
// since 9; useinstead @ohos.rpc.MessageSequence.readParcelableArray
let _v44: rpc.MessageParcel = {} as rpc.MessageParcel; _v44.readSequenceableArray([]);
// since 9; useinstead @ohos.rpc.MessageSequence.readShort
let _v45: rpc.MessageParcel = {} as rpc.MessageParcel; _v45.readShort();
// since 9; useinstead @ohos.rpc.MessageSequence.readShortArray
let _v46: rpc.MessageParcel = {} as rpc.MessageParcel; _v46.readShortArray();
// since 9; useinstead @ohos.rpc.MessageSequence.readString
let _v47: rpc.MessageParcel = {} as rpc.MessageParcel; _v47.readString();
// since 9; useinstead @ohos.rpc.MessageSequence.readStringArray
let _v48: rpc.MessageParcel = {} as rpc.MessageParcel; _v48.readStringArray();
// since 9; useinstead @ohos.rpc.MessageSequence.reclaim
let _v49: rpc.MessageParcel = {} as rpc.MessageParcel; _v49.reclaim();
// since 9; useinstead @ohos.rpc.MessageSequence.rewindRead
let _v50: rpc.MessageParcel = {} as rpc.MessageParcel; _v50.rewindRead(0);
// since 9; useinstead @ohos.rpc.MessageSequence.rewindWrite
let _v51: rpc.MessageParcel = {} as rpc.MessageParcel; _v51.rewindWrite(0);
// since 9; useinstead @ohos.rpc.MessageSequence.setCapacity
let _v52: rpc.MessageParcel = {} as rpc.MessageParcel; _v52.setCapacity(0);
// since 9; useinstead @ohos.rpc.MessageSequence.setSize
let _v53: rpc.MessageParcel = {} as rpc.MessageParcel; _v53.setSize(0);
// since 9; useinstead @ohos.rpc.MessageSequence.writeAshmem
let _v54: rpc.MessageParcel = {} as rpc.MessageParcel; _v54.writeAshmem(({} as any));
// since 9; useinstead @ohos.rpc.MessageSequence.writeBoolean
let _v55: rpc.MessageParcel = {} as rpc.MessageParcel; _v55.writeBoolean(false);
// since 9; useinstead @ohos.rpc.MessageSequence.writeBooleanArray
let _v56: rpc.MessageParcel = {} as rpc.MessageParcel; _v56.writeBooleanArray([]);
// since 9; useinstead @ohos.rpc.MessageSequence.writeByte
let _v57: rpc.MessageParcel = {} as rpc.MessageParcel; _v57.writeByte(0);
// since 9; useinstead @ohos.rpc.MessageSequence.writeByteArray
let _v58: rpc.MessageParcel = {} as rpc.MessageParcel; _v58.writeByteArray([]);
// since 9; useinstead @ohos.rpc.MessageSequence.writeChar
let _v59: rpc.MessageParcel = {} as rpc.MessageParcel; _v59.writeChar(0);
// since 9; useinstead @ohos.rpc.MessageSequence.writeCharArray
let _v60: rpc.MessageParcel = {} as rpc.MessageParcel; _v60.writeCharArray([]);
// since 9; useinstead @ohos.rpc.MessageSequence.writeDouble
let _v61: rpc.MessageParcel = {} as rpc.MessageParcel; _v61.writeDouble(0);
// since 9; useinstead @ohos.rpc.MessageSequence.writeDoubleArray
let _v62: rpc.MessageParcel = {} as rpc.MessageParcel; _v62.writeDoubleArray([]);
// since 9; useinstead @ohos.rpc.MessageSequence.writeFileDescriptor
let _v63: rpc.MessageParcel = {} as rpc.MessageParcel; _v63.writeFileDescriptor(0);
// since 9; useinstead @ohos.rpc.MessageSequence.writeFloat
let _v64: rpc.MessageParcel = {} as rpc.MessageParcel; _v64.writeFloat(0);
// since 9; useinstead @ohos.rpc.MessageSequence.writeFloatArray
let _v65: rpc.MessageParcel = {} as rpc.MessageParcel; _v65.writeFloatArray([]);
// since 9; useinstead @ohos.rpc.MessageSequence.writeInt
let _v66: rpc.MessageParcel = {} as rpc.MessageParcel; _v66.writeInt(0);
// since 9; useinstead @ohos.rpc.MessageSequence.writeIntArray
let _v67: rpc.MessageParcel = {} as rpc.MessageParcel; _v67.writeIntArray([]);
// since 9; useinstead @ohos.rpc.MessageSequence.writeInterfaceToken
let _v68: rpc.MessageParcel = {} as rpc.MessageParcel; _v68.writeInterfaceToken('');
// since 9; useinstead @ohos.rpc.MessageSequence.writeLong
let _v69: rpc.MessageParcel = {} as rpc.MessageParcel; _v69.writeLong(0);
// since 9; useinstead @ohos.rpc.MessageSequence.writeLongArray
let _v70: rpc.MessageParcel = {} as rpc.MessageParcel; _v70.writeLongArray([]);
// since 9; useinstead @ohos.rpc.MessageSequence.writeNoException
let _v71: rpc.MessageParcel = {} as rpc.MessageParcel; _v71.writeNoException();
// since 9; useinstead @ohos.rpc.MessageSequence.writeRawData
let _v72: rpc.MessageParcel = {} as rpc.MessageParcel; _v72.writeRawData([], 0);
// since 9; useinstead @ohos.rpc.MessageSequence.writeRemoteObject
let _v73: rpc.MessageParcel = {} as rpc.MessageParcel; _v73.writeRemoteObject(({} as any));
// since 9; useinstead @ohos.rpc.MessageSequence.writeRemoteObjectArray
let _v74: rpc.MessageParcel = {} as rpc.MessageParcel; _v74.writeRemoteObjectArray([]);
// since 9; useinstead @ohos.rpc.MessageSequence.writeParcelable
let _v75: rpc.MessageParcel = {} as rpc.MessageParcel; _v75.writeSequenceable(({} as any));
// since 9; useinstead @ohos.rpc.MessageSequence.writeParcelableArray
let _v76: rpc.MessageParcel = {} as rpc.MessageParcel; _v76.writeSequenceableArray([]);
// since 9; useinstead @ohos.rpc.MessageSequence.writeShort
let _v77: rpc.MessageParcel = {} as rpc.MessageParcel; _v77.writeShort(0);
// since 9; useinstead @ohos.rpc.MessageSequence.writeShortArray
let _v78: rpc.MessageParcel = {} as rpc.MessageParcel; _v78.writeShortArray([]);
// since 9; useinstead @ohos.rpc.MessageSequence.writeString
let _v79: rpc.MessageParcel = {} as rpc.MessageParcel; _v79.writeString('');
// since 9; useinstead @ohos.rpc.MessageSequence.writeStringArray
let _v80: rpc.MessageParcel = {} as rpc.MessageParcel; _v80.writeStringArray([]);
// since 11; useinstead @ohos.rpc.MessageSequence.readRawDataBuffer
let _v81: rpc.MessageSequence = {} as rpc.MessageSequence; _v81.readRawData(0);
// since 11; useinstead @ohos.rpc.MessageSequence.writeRawDataBuffer
let _v82: rpc.MessageSequence = {} as rpc.MessageSequence; _v82.writeRawData([], 0);
// since 9; useinstead @ohos.rpc.RemoteObject.modifyLocalInterface
let _v83: rpc.RemoteObject = {} as rpc.RemoteObject; _v83.attachLocalInterface(({} as any), '');
// since 9; useinstead @ohos.rpc.RemoteObject.getDescriptor
let _v84: rpc.RemoteObject = {} as rpc.RemoteObject; _v84.getInterfaceDescriptor();
// since 9; useinstead @ohos.rpc.RemoteObject.onRemoteMessageRequest
let _v85: rpc.RemoteObject = {} as rpc.RemoteObject; _v85.onRemoteRequest(0, ({} as any), ({} as any), ({} as any));
// since 9; useinstead @ohos.rpc.RemoteObject.getLocalInterface
let _v86: rpc.RemoteObject = {} as rpc.RemoteObject; _v86.queryLocalInterface('');
// since 9; useinstead @ohos.rpc.RemoteObject.sendMessageRequest
let _v87: rpc.RemoteObject = {} as rpc.RemoteObject; _v87.sendRequest(0, ({} as any), ({} as any), ({} as any));
// since 9; useinstead @ohos.rpc.RemoteProxy.registerDeathRecipient
let _v88: rpc.RemoteProxy = {} as rpc.RemoteProxy; _v88.addDeathRecipient(({} as any), 0);
// since 9; useinstead @ohos.rpc.RemoteProxy.getDescriptor
let _v89: rpc.RemoteProxy = {} as rpc.RemoteProxy; _v89.getInterfaceDescriptor();
// since 9; useinstead @ohos.rpc.RemoteProxy.getLocalInterface
let _v90: rpc.RemoteProxy = {} as rpc.RemoteProxy; _v90.queryLocalInterface('');
// since 9; useinstead @ohos.rpc.RemoteProxy.unregisterDeathRecipient
let _v91: rpc.RemoteProxy = {} as rpc.RemoteProxy; _v91.removeDeathRecipient(({} as any), 0);
// since 9; useinstead @ohos.rpc.RemoteProxy.sendMessageRequest
let _v92: rpc.RemoteProxy = {} as rpc.RemoteProxy; _v92.sendRequest(0, ({} as any), ({} as any), ({} as any));
// since 9; useinstead @ohos.rpc.RequestResult
let _v93: rpc.SendRequestResult = {} as rpc.SendRequestResult;
// since 9; useinstead @ohos.rpc.RequestResult.code
let _v94: rpc.SendRequestResult = {} as rpc.SendRequestResult; const _v95 = _v94.code;
// since 9; useinstead @ohos.rpc.RequestResult.data
let _v96: rpc.SendRequestResult = {} as rpc.SendRequestResult; const _v97 = _v96.data;
// since 9; useinstead @ohos.rpc.RequestResult.errCode
let _v98: rpc.SendRequestResult = {} as rpc.SendRequestResult; const _v99 = _v98.errCode;
// since 9; useinstead @ohos.rpc.RequestResult.reply
let _v100: rpc.SendRequestResult = {} as rpc.SendRequestResult; const _v101 = _v100.reply;
// since 9; useinstead @ohos.rpc.Parcelable
let _v102: rpc.Sequenceable = {} as rpc.Sequenceable;
// since 9; useinstead @ohos.rpc.Parcelable.marshalling
let _v103: rpc.Sequenceable = {} as rpc.Sequenceable; _v103.marshalling(({} as any));
// since 9; useinstead @ohos.rpc.Parcelable.unmarshalling
let _v104: rpc.Sequenceable = {} as rpc.Sequenceable; _v104.unmarshalling(({} as any));
