// Auto-generated by scripts/gen-deprecated-usage.mjs — do not edit.
// Kit: @ohos.bluetooth.connection
// Deprecated symbols: 1 (compilable real-usage corpus; expect TS 6385/6387).
// Generated: 2026-08-15T18:18:26.091Z

import connection from '@ohos.bluetooth.connection';

// Deprecated symbol usages.
// since 12; useinstead none
connection.setLocalName('');
