// Auto-generated by scripts/gen-deprecated-usage.mjs — do not edit.
// Kit: @ohos.convertxml
// Deprecated symbols: 2 (compilable real-usage corpus; expect TS 6385/6387).
// Generated: 2026-08-15T18:18:26.091Z

import xml from '@ohos.convertxml';

// Deprecated symbol usages.
// since 9; useinstead @ohos.convertxml.ConvertXML.fastConvertToJSObject
let _v0: xml.ConvertXML = {} as xml.ConvertXML; _v0.convert('');
// since 14; useinstead @ohos.convertxml.ConvertXML.fastConvertToJSObject
let _v1: xml.ConvertXML = {} as xml.ConvertXML; _v1.convertToJSObject('');
