// Auto-generated by scripts/gen-deprecated-usage.mjs — do not edit.
// Kit: @ohos.file.fileAccess
// Deprecated symbols: 1 (compilable real-usage corpus; expect TS 6385/6387).
// Generated: 2026-08-15T18:18:26.091Z

import fileAccess from '@ohos.file.fileAccess';

// Deprecated symbol usages.
// since 23; useinstead @ohos.file.fs.
// @ohos.file.fileAccess.fileAccess: module-move (kit-level); covered by the import line
