// Auto-generated by scripts/gen-deprecated-usage.mjs — do not edit.
// Kit: @ohos.continuation.continuationManager
// Deprecated symbols: 32 (compilable real-usage corpus; expect TS 6385/6387).
// Generated: 2026-08-15T18:18:26.091Z

import continuationManager from '@ohos.continuation.continuationManager';

// Deprecated symbol usages.
// since 22; useinstead none
const _v0 = continuationManager;
// since 22; useinstead none
let _v1: continuationManager.ContinuationExtraParams = {} as continuationManager.ContinuationExtraParams;
// since 22; useinstead none
let _v2: continuationManager.ContinuationResult = {} as continuationManager.ContinuationResult;
// since 22; useinstead @ohos.distributedDeviceManager.
let _v3: continuationManager.ContinuationExtraParams = {} as continuationManager.ContinuationExtraParams;
// since 22; useinstead none
const _v4 = continuationManager.ContinuationMode;
// since 22; useinstead none
const _v5 = continuationManager.ContinuationMode.COLLABORATION_MULTIPLE;
// since 22; useinstead none
const _v6 = continuationManager.ContinuationMode.COLLABORATION_SINGLE;
// since 22; useinstead @ohos.distributedDeviceManager.
let _v7: continuationManager.ContinuationResult = {} as continuationManager.ContinuationResult;
// since 22; useinstead none
const _v8 = continuationManager.DeviceConnectState;
// since 22; useinstead none
const _v9 = continuationManager.DeviceConnectState.CONNECTED;
// since 22; useinstead none
const _v10 = continuationManager.DeviceConnectState.CONNECTING;
// since 22; useinstead none
const _v11 = continuationManager.DeviceConnectState.DISCONNECTING;
// since 22; useinstead none
const _v12 = continuationManager.DeviceConnectState.IDLE;
// since 22; useinstead none
let _v13: continuationManager.ContinuationExtraParams = {} as continuationManager.ContinuationExtraParams; const _v14 = _v13.authInfo;
// since 22; useinstead none
let _v15: continuationManager.ContinuationExtraParams = {} as continuationManager.ContinuationExtraParams; const _v16 = _v15.continuationMode;
// since 22; useinstead none
let _v17: continuationManager.ContinuationExtraParams = {} as continuationManager.ContinuationExtraParams; const _v18 = _v17.description;
// since 22; useinstead none
let _v19: continuationManager.ContinuationExtraParams = {} as continuationManager.ContinuationExtraParams; const _v20 = _v19.deviceType;
// since 22; useinstead none
let _v21: continuationManager.ContinuationExtraParams = {} as continuationManager.ContinuationExtraParams; const _v22 = _v21.filter;
// since 22; useinstead none
let _v23: continuationManager.ContinuationResult = {} as continuationManager.ContinuationResult; const _v24 = _v23.id;
// since 22; useinstead none
let _v25: continuationManager.ContinuationResult = {} as continuationManager.ContinuationResult; const _v26 = _v25.name;
// since 9; useinstead @ohos.continuation.continuationManager.off
continuationManager.off('deviceConnect');
// since 9; useinstead @ohos.continuation.continuationManager.on
continuationManager.on('deviceConnect', () => {});
// since 9; useinstead @ohos.continuation.continuationManager.registerContinuation
continuationManager.register();
// since 22; useinstead none
continuationManager.registerContinuation();
// since 22; useinstead none
continuationManager.startContinuationDeviceManager(0);
// since 9; useinstead @ohos.continuation.continuationManager.startContinuationDeviceManager
continuationManager.startDeviceManager(0);
// since 22; useinstead none
let _v27: continuationManager.ContinuationExtraParams = {} as continuationManager.ContinuationExtraParams; const _v28 = _v27.targetBundle;
// since 22; useinstead none
let _v29: continuationManager.ContinuationResult = {} as continuationManager.ContinuationResult; const _v30 = _v29.type;
// since 9; useinstead @ohos.continuation.continuationManager.unregisterContinuation
continuationManager.unregister(0);
// since 22; useinstead none
continuationManager.unregisterContinuation(0);
// since 9; useinstead @ohos.continuation.continuationManager.updateContinuationState
continuationManager.updateConnectStatus(0, '', ({} as any));
// since 22; useinstead none
continuationManager.updateContinuationState(0, '', ({} as any));
