// Auto-generated by scripts/gen-deprecated-usage.mjs — do not edit.
// Kit: @ohos.app.ability.AbilityConstant
// Deprecated symbols: 1 (compilable real-usage corpus; expect TS 6385/6387).
// Generated: 2026-08-15T18:18:26.091Z

import AbilityConstant from '@ohos.app.ability.AbilityConstant';

// Deprecated symbol usages.
// since 10; useinstead @ohos.app.ability.AbilityConstant.LastExitReason.APP_FREEZE
const _v0 = AbilityConstant.LastExitReason.ABILITY_NOT_RESPONDING;
