// Auto-generated by scripts/gen-deprecated-usage.mjs — do not edit.
// Kit: @ohos.file.picker
// Deprecated symbols: 15 (compilable real-usage corpus; expect TS 6385/6387).
// Generated: 2026-08-15T18:18:26.091Z

import picker from '@ohos.file.picker';

// Deprecated symbol usages.
// since 12; useinstead @ohos.file.picker.save_button/SaveButtonOptions
const _v0 = picker.PhotoSaveOptions;
// since 18; useinstead @ohos.file.picker.save_button/SaveButtonOptions
let _v1: picker.PhotoSaveOptions = {} as picker.PhotoSaveOptions; const _v2 = _v1.newFileNames;
// since 12; useinstead @ohos.file.photoAccessHelper.PhotoSelectOptions
const _v3 = picker.PhotoSelectOptions;
// since 18; useinstead @ohos.file.photoAccessHelper.PhotoSelectOptions
let _v4: picker.PhotoSelectOptions = {} as picker.PhotoSelectOptions; const _v5 = _v4.MIMEType;
// since 18; useinstead @ohos.file.photoAccessHelper.PhotoSelectOptions
let _v6: picker.PhotoSelectOptions = {} as picker.PhotoSelectOptions; const _v7 = _v6.maxSelectNumber;
// since 12; useinstead @ohos.file.photoAccessHelper.PhotoSelectResult
const _v8 = picker.PhotoSelectResult;
// since 18; useinstead @ohos.file.photoAccessHelper.PhotoSelectResult
let _v9: picker.PhotoSelectResult = {} as picker.PhotoSelectResult; const _v10 = _v9.isOriginalPhoto;
// since 18; useinstead @ohos.file.photoAccessHelper.PhotoSelectResult
let _v11: picker.PhotoSelectResult = {} as picker.PhotoSelectResult; const _v12 = _v11.photoUris;
// since 12; useinstead @ohos.file.photoAccessHelper.PhotoViewMIMETypes
const _v13 = picker.PhotoViewMIMETypes;
// since 18; useinstead @ohos.file.photoAccessHelper.PhotoViewMIMETypes
const _v14 = picker.PhotoViewMIMETypes.IMAGE_TYPE;
// since 18; useinstead @ohos.file.photoAccessHelper.PhotoViewMIMETypes
const _v15 = picker.PhotoViewMIMETypes.IMAGE_VIDEO_TYPE;
// since 18; useinstead @ohos.file.photoAccessHelper.PhotoViewMIMETypes
const _v16 = picker.PhotoViewMIMETypes.VIDEO_TYPE;
// since 12; useinstead @ohos.file.photoAccessHelper.PhotoViewPicker
const _v17 = picker.PhotoViewPicker;
// since 12; useinstead @ohos.file.picker.save_button/SaveButton
let _v18: picker.PhotoViewPicker = {} as picker.PhotoViewPicker; _v18.save();
// since 12; useinstead @ohos.file.photoAccessHelper.PhotoViewPicker.select
let _v19: picker.PhotoViewPicker = {} as picker.PhotoViewPicker; _v19.select();
