// Auto-generated by scripts/gen-deprecated-usage.mjs — do not edit.
// Kit: @ohos.app.form.formInfo
// Deprecated symbols: 6 (compilable real-usage corpus; expect TS 6385/6387).
// Generated: 2026-08-15T18:18:26.091Z

import formInfo from '@ohos.app.form.formInfo';

// Deprecated symbol usages.
// since 20; useinstead none
const _v0 = formInfo.ColorMode;
// since 20; useinstead none
const _v1 = formInfo.ColorMode.MODE_AUTO;
// since 20; useinstead none
const _v2 = formInfo.ColorMode.MODE_DARK;
// since 20; useinstead none
const _v3 = formInfo.ColorMode.MODE_LIGHT;
// since 20; useinstead none
const _v4 = formInfo.FormDimension.Dimension_2_1;
// since 20; useinstead none
let _v5: formInfo.FormInfo = {} as formInfo.FormInfo; const _v6 = _v5.colorMode;
