// Auto-generated by scripts/gen-deprecated-usage.mjs — do not edit.
// Kit: @ohos.font
// Deprecated symbols: 3 (compilable real-usage corpus; expect TS 6385/6387).
// Generated: 2026-08-15T18:18:26.091Z

import font from '@ohos.font';

// Deprecated symbol usages.
// since 18; useinstead @ohos.arkui.UIContext.Font.getFontByName
font.getFontByName('');
// since 18; useinstead @ohos.arkui.UIContext.Font.getSystemFontList
font.getSystemFontList();
// since 18; useinstead @ohos.arkui.UIContext.Font.registerFont
font.registerFont(({} as any));
