// Auto-generated by scripts/gen-deprecated-usage.mjs — do not edit.
// Kit: @ohos.deviceInfo
// Deprecated symbols: 1 (compilable real-usage corpus; expect TS 6385/6387).
// Generated: 2026-08-15T18:18:26.091Z

import deviceInfo from '@ohos.deviceInfo';

// Deprecated symbol usages.
// since 9; useinstead none
const _v0 = deviceInfo.hardwareProfile;
