// Auto-generated by scripts/gen-deprecated-usage.mjs — do not edit.
// Kit: @ohos.uri
// Deprecated symbols: 1 (compilable real-usage corpus; expect TS 6385/6387).
// Generated: 2026-08-15T18:18:26.091Z

import uri from '@ohos.uri';

// Deprecated symbol usages.
// since 9; useinstead @ohos.uri.URI.equalsTo
let _v0: uri.URI = {} as uri.URI; _v0.equals(({} as any));
