// Auto-generated by scripts/gen-deprecated-usage.mjs — do not edit.
// Kit: @ohos.inputMethodEngine
// Deprecated symbols: 14 (compilable real-usage corpus; expect TS 6385/6387).
// Generated: 2026-08-15T18:18:26.091Z

import inputMethodEngine from '@ohos.inputMethodEngine';

// Deprecated symbol usages.
// since 23; useinstead @ohos.inputMethodEngine.InputMethodAbility
let _v0: inputMethodEngine.InputMethodEngine = {} as inputMethodEngine.InputMethodEngine;
// since 23; useinstead @ohos.inputMethodEngine.off
let _v1: inputMethodEngine.InputMethodEngine = {} as inputMethodEngine.InputMethodEngine; _v1.off('inputStart');
// since 23; useinstead @ohos.inputMethodEngine.on
let _v2: inputMethodEngine.InputMethodEngine = {} as inputMethodEngine.InputMethodEngine; _v2.on('inputStart', () => {});
// since 9; useinstead @ohos.inputMethodEngine.KeyboardController.hide
let _v3: inputMethodEngine.KeyboardController = {} as inputMethodEngine.KeyboardController; _v3.hideKeyboard();
// since 9; useinstead @ohos.inputMethodEngine.InputClient
let _v4: inputMethodEngine.TextInputClient = {} as inputMethodEngine.TextInputClient;
// since 9; useinstead @ohos.inputMethodEngine.InputClient.deleteBackward
let _v5: inputMethodEngine.TextInputClient = {} as inputMethodEngine.TextInputClient; _v5.deleteBackward(0);
// since 9; useinstead @ohos.inputMethodEngine.InputClient.deleteForward
let _v6: inputMethodEngine.TextInputClient = {} as inputMethodEngine.TextInputClient; _v6.deleteForward(0);
// since 9; useinstead @ohos.inputMethodEngine.InputClient.getBackward
let _v7: inputMethodEngine.TextInputClient = {} as inputMethodEngine.TextInputClient; _v7.getBackward(0);
// since 9; useinstead @ohos.inputMethodEngine.InputClient.getEditorAttribute
let _v8: inputMethodEngine.TextInputClient = {} as inputMethodEngine.TextInputClient; _v8.getEditorAttribute();
// since 9; useinstead @ohos.inputMethodEngine.InputClient.getForward
let _v9: inputMethodEngine.TextInputClient = {} as inputMethodEngine.TextInputClient; _v9.getForward(0);
// since 9; useinstead @ohos.inputMethodEngine.InputClient.insertText
let _v10: inputMethodEngine.TextInputClient = {} as inputMethodEngine.TextInputClient; _v10.insertText('');
// since 9; useinstead @ohos.inputMethodEngine.InputClient.sendKeyFunction
let _v11: inputMethodEngine.TextInputClient = {} as inputMethodEngine.TextInputClient; _v11.sendKeyFunction(0);
// since 9; useinstead @ohos.inputMethodEngine.getKeyboardDelegate
inputMethodEngine.createKeyboardDelegate();
// since 9; useinstead @ohos.inputMethodEngine.getInputMethodAbility
inputMethodEngine.getInputMethodEngine();
