// Auto-generated by scripts/gen-deprecated-usage.mjs — do not edit.
// Kit: @ohos.router
// Deprecated symbols: 17 (compilable real-usage corpus; expect TS 6385/6387).
// Generated: 2026-08-15T18:18:26.091Z

import router from '@ohos.router';

// Deprecated symbol usages.
// since 18; useinstead @ohos.arkui.UIContext.Router.back
router.back();
// since 18; useinstead @ohos.arkui.UIContext.Router.clear
router.clear();
// since 9; useinstead @ohos.router.hideAlertBeforeBackPage
router.disableAlertBeforeBackPage();
// since 9; useinstead @ohos.router.showAlertBeforeBackPage
router.enableAlertBeforeBackPage(({} as any));
// since 18; useinstead @ohos.arkui.UIContext.Router.getLength
router.getLength();
// since 18; useinstead @ohos.arkui.UIContext.Router.getParams
router.getParams();
// since 18; useinstead @ohos.arkui.UIContext.Router.getState
router.getState();
// since 18; useinstead @ohos.arkui.UIContext.Router.getStateByIndex
router.getStateByIndex(0);
// since 18; useinstead @ohos.arkui.UIContext.Router.getStateByUrl
router.getStateByUrl('');
// since 18; useinstead @ohos.arkui.UIContext.Router.hideAlertBeforeBackPage
router.hideAlertBeforeBackPage();
// since 9; useinstead @ohos.router.pushUrl
router.push(({} as any));
// since 18; useinstead @ohos.arkui.UIContext.Router.pushNamedRoute
router.pushNamedRoute(({} as any));
// since 18; useinstead @ohos.arkui.UIContext.Router.pushUrl
router.pushUrl(({} as any));
// since 9; useinstead @ohos.router.replaceUrl
router.replace(({} as any));
// since 18; useinstead @ohos.arkui.UIContext.Router.replaceNamedRoute
router.replaceNamedRoute(({} as any));
// since 18; useinstead @ohos.arkui.UIContext.Router.replaceUrl
router.replaceUrl(({} as any));
// since 18; useinstead @ohos.arkui.UIContext.Router.showAlertBeforeBackPage
router.showAlertBeforeBackPage(({} as any));
