// Auto-generated by scripts/gen-deprecated-usage.mjs — do not edit.
// Kit: @ohos.wifiManager
// Deprecated symbols: 3 (compilable real-usage corpus; expect TS 6385/6387).
// Generated: 2026-08-15T18:18:26.091Z

import wifiManager from '@ohos.wifiManager';

// Deprecated symbol usages.
// since 10; useinstead @ohos.wifiManager.getScanInfoList
wifiManager.getScanResults();
// since 10; useinstead @ohos.wifiManager.getScanInfoList
wifiManager.getScanResultsSync();
// since 10; useinstead @ohos.wifiManager.startScan
wifiManager.scan();
