// Auto-generated by scripts/gen-deprecated-usage.mjs — do not edit.
// Kit: @ohos.util.LightWeightSet
// Deprecated symbols: 1 (compilable real-usage corpus; expect TS 6385/6387).
// Generated: 2026-08-15T18:18:26.091Z

import LightWeightSet from '@ohos.util.LightWeightSet';

// Deprecated symbol usages.
// since 12; useinstead none
let _v0: LightWeightSet<any> = {} as LightWeightSet<any>; _v0.equal({});
