// Auto-generated by scripts/gen-deprecated-usage.mjs — do not edit.
// Kit: @ohos.data.distributedDataObject
// Deprecated symbols: 5 (compilable real-usage corpus; expect TS 6385/6387).
// Generated: 2026-08-15T18:18:26.091Z

import distributedDataObject from '@ohos.data.distributedDataObject';

// Deprecated symbol usages.
// since 9; useinstead @ohos.data.distributedDataObject.DataObject
let _v0: distributedDataObject.DistributedObject = {} as distributedDataObject.DistributedObject;
// since 9; useinstead @ohos.data.distributedDataObject.DataObject.off
let _v1: distributedDataObject.DistributedObject = {} as distributedDataObject.DistributedObject; _v1.off('change');
// since 9; useinstead @ohos.data.distributedDataObject.DataObject.on
let _v2: distributedDataObject.DistributedObject = {} as distributedDataObject.DistributedObject; _v2.on('change', () => {});
// since 9; useinstead @ohos.data.distributedDataObject.DataObject.setSessionId
let _v3: distributedDataObject.DistributedObject = {} as distributedDataObject.DistributedObject; _v3.setSessionId();
// since 9; useinstead @ohos.data.distributedDataObject.create
distributedDataObject.createDistributedObject({});
