// Auto-generated by scripts/gen-deprecated-usage.mjs — do not edit.
// Kit: @ohos.nfc.cardEmulation
// Deprecated symbols: 8 (compilable real-usage corpus; expect TS 6385/6387).
// Generated: 2026-08-15T18:18:26.091Z

import cardEmulation from '@ohos.nfc.cardEmulation';

// Deprecated symbol usages.
// since 9; useinstead @ohos.nfc.cardEmulation.hasHceCapability
const _v0 = cardEmulation.FeatureType;
// since 9; useinstead @ohos.nfc.cardEmulation.hasHceCapability
const _v1 = cardEmulation.FeatureType.ESE;
// since 9; useinstead @ohos.nfc.cardEmulation.hasHceCapability
const _v2 = cardEmulation.FeatureType.HCE;
// since 9; useinstead @ohos.nfc.cardEmulation.hasHceCapability
const _v3 = cardEmulation.FeatureType.UICC;
// since 9; useinstead @ohos.nfc.cardEmulation.HceService.transmit
let _v4: cardEmulation.HceService = {} as cardEmulation.HceService; _v4.sendResponse([]);
// since 9; useinstead @ohos.nfc.cardEmulation.HceService.start
let _v5: cardEmulation.HceService = {} as cardEmulation.HceService; _v5.startHCE([]);
// since 9; useinstead @ohos.nfc.cardEmulation.HceService.stop
let _v6: cardEmulation.HceService = {} as cardEmulation.HceService; _v6.stopHCE();
// since 9; useinstead @ohos.nfc.cardEmulation.hasHceCapability
cardEmulation.isSupported(0);
