// Auto-generated by scripts/gen-deprecated-usage.mjs — do not edit.
// Kit: @ohos.request
// Deprecated symbols: 9 (compilable real-usage corpus; expect TS 6385/6387).
// Generated: 2026-08-15T18:18:26.091Z

import request from '@ohos.request';

// Deprecated symbol usages.
// since 9; useinstead @ohos.request.suspend
let _v0: request.DownloadTask = {} as request.DownloadTask; _v0.pause();
// since 9; useinstead @ohos.request.getTaskInfo
let _v1: request.DownloadTask = {} as request.DownloadTask; _v1.query();
// since 9; useinstead @ohos.request.getTaskMimeType
let _v2: request.DownloadTask = {} as request.DownloadTask; _v2.queryMimeType();
// since 9; useinstead @ohos.request.delete
let _v3: request.DownloadTask = {} as request.DownloadTask; _v3.remove();
// since 9; useinstead @ohos.request.restore
let _v4: request.DownloadTask = {} as request.DownloadTask; _v4.resume();
// since 9; useinstead @ohos.request.delete
let _v5: request.UploadTask = {} as request.UploadTask; _v5.remove();
// since 18; useinstead @ohos.request.agent.FileSpec.contentType
let _v6: request.agent.FileSpec = {} as request.agent.FileSpec; const _v7 = _v6.mimeType;
// since 9; useinstead @ohos.request.downloadFile
request.download(({} as any));
// since 9; useinstead @ohos.request.uploadFile
request.upload(({} as any));
