// Auto-generated by scripts/gen-deprecated-usage.mjs — do not edit.
// Kit: @ohos.security.cert
// Deprecated symbols: 24 (compilable real-usage corpus; expect TS 6385/6387).
// Generated: 2026-08-15T18:18:26.091Z

import cert from '@ohos.security.cert';

// Deprecated symbol usages.
// since 10; useinstead @ohos.security.cert.X509Cert.getCertSerialNumber
let _v0: cert.X509Cert = {} as cert.X509Cert; _v0.getSerialNumber();
// since 11; useinstead @ohos.security.cert.X509CRL
let _v1: cert.X509Crl = {} as cert.X509Crl;
// since 11; useinstead @ohos.security.cert.X509CRL.getEncoded
let _v2: cert.X509Crl = {} as cert.X509Crl; _v2.getEncoded();
// since 11; useinstead @ohos.security.cert.X509CRL.getIssuerName
let _v3: cert.X509Crl = {} as cert.X509Crl; _v3.getIssuerName();
// since 11; useinstead @ohos.security.cert.X509CRL.getLastUpdate
let _v4: cert.X509Crl = {} as cert.X509Crl; _v4.getLastUpdate();
// since 11; useinstead @ohos.security.cert.X509CRL.getNextUpdate
let _v5: cert.X509Crl = {} as cert.X509Crl; _v5.getNextUpdate();
// since 11; useinstead @ohos.security.cert.X509CRL.getRevokedCert
let _v6: cert.X509Crl = {} as cert.X509Crl; _v6.getRevokedCert(0);
// since 11; useinstead @ohos.security.cert.X509CRL.getRevokedCertWithCert
let _v7: cert.X509Crl = {} as cert.X509Crl; _v7.getRevokedCertWithCert(({} as any));
// since 11; useinstead @ohos.security.cert.X509CRL.getRevokedCerts
let _v8: cert.X509Crl = {} as cert.X509Crl; _v8.getRevokedCerts();
// since 11; useinstead @ohos.security.cert.X509CRL.getSignature
let _v9: cert.X509Crl = {} as cert.X509Crl; _v9.getSignature();
// since 11; useinstead @ohos.security.cert.X509CRL.getSignatureAlgName
let _v10: cert.X509Crl = {} as cert.X509Crl; _v10.getSignatureAlgName();
// since 11; useinstead @ohos.security.cert.X509CRL.getSignatureAlgOid
let _v11: cert.X509Crl = {} as cert.X509Crl; _v11.getSignatureAlgOid();
// since 11; useinstead @ohos.security.cert.X509CRL.getSignatureAlgParams
let _v12: cert.X509Crl = {} as cert.X509Crl; _v12.getSignatureAlgParams();
// since 11; useinstead @ohos.security.cert.X509CRL.getTBSInfo
let _v13: cert.X509Crl = {} as cert.X509Crl; _v13.getTbsInfo();
// since 11; useinstead @ohos.security.cert.X509CRL.getType
let _v14: cert.X509Crl = {} as cert.X509Crl; _v14.getType();
// since 11; useinstead @ohos.security.cert.X509CRL.getVersion
let _v15: cert.X509Crl = {} as cert.X509Crl; _v15.getVersion();
// since 11; useinstead @ohos.security.cert.X509CRL.isRevoked
let _v16: cert.X509Crl = {} as cert.X509Crl; _v16.isRevoked(({} as any));
// since 11; useinstead @ohos.security.cert.X509CRL.verify
let _v17: cert.X509Crl = {} as cert.X509Crl; _v17.verify(({} as any));
// since 11; useinstead @ohos.security.cert.X509CRLEntry
let _v18: cert.X509CrlEntry = {} as cert.X509CrlEntry;
// since 11; useinstead @ohos.security.cert.X509CRLEntry.getCertIssuer
let _v19: cert.X509CrlEntry = {} as cert.X509CrlEntry; _v19.getCertIssuer();
// since 11; useinstead @ohos.security.cert.X509CRLEntry.getEncoded
let _v20: cert.X509CrlEntry = {} as cert.X509CrlEntry; _v20.getEncoded();
// since 11; useinstead @ohos.security.cert.X509CRLEntry.getRevocationDate
let _v21: cert.X509CrlEntry = {} as cert.X509CrlEntry; _v21.getRevocationDate();
// since 11; useinstead @ohos.security.cert.X509CRLEntry.getSerialNumber
let _v22: cert.X509CrlEntry = {} as cert.X509CrlEntry; _v22.getSerialNumber();
// since 11; useinstead @ohos.security.cert.createX509CRL
cert.createX509Crl(({} as any));
