// Auto-generated by scripts/gen-deprecated-usage.mjs — do not edit.
// Kit: @ohos.vibrator
// Deprecated symbols: 2 (compilable real-usage corpus; expect TS 6385/6387).
// Generated: 2026-08-15T18:18:26.091Z

import vibrator from '@ohos.vibrator';

// Deprecated symbol usages.
// since 9; useinstead @ohos.vibrator.stopVibration
vibrator.stop(({} as any));
// since 9; useinstead @ohos.vibrator.startVibration
vibrator.vibrate(0);
