// Auto-generated by scripts/gen-deprecated-usage.mjs — do not edit.
// Kit: @ohos.document
// Deprecated symbols: 3 (compilable real-usage corpus; expect TS 6385/6387).
// Generated: 2026-08-15T18:18:26.091Z

import document from '@ohos.document';

// Deprecated symbol usages.
// since 9; useinstead none
const _v0 = document;
// since 9; useinstead none
document.choose();
// since 9; useinstead none
document.show('', '');
