// Auto-generated by scripts/gen-deprecated-usage.mjs — do not edit.
// Kit: @ohos.wallpaper
// Deprecated symbols: 16 (compilable real-usage corpus; expect TS 6385/6387).
// Generated: 2026-08-15T18:18:26.091Z

import wallpaper from '@ohos.wallpaper';

// Deprecated symbol usages.
// since 9; useinstead none
let _v0: wallpaper.RgbaColor = {} as wallpaper.RgbaColor;
// since 9; useinstead none
let _v1: wallpaper.RgbaColor = {} as wallpaper.RgbaColor; const _v2 = _v1.alpha;
// since 9; useinstead none
let _v3: wallpaper.RgbaColor = {} as wallpaper.RgbaColor; const _v4 = _v3.blue;
// since 9; useinstead none
let _v5: wallpaper.RgbaColor = {} as wallpaper.RgbaColor; const _v6 = _v5.green;
// since 9; useinstead none
let _v7: wallpaper.RgbaColor = {} as wallpaper.RgbaColor; const _v8 = _v7.red;
// since 9; useinstead none
wallpaper.getColors(({} as any));
// since 9; useinstead none
wallpaper.getFile(({} as any));
// since 9; useinstead none
wallpaper.getId(({} as any));
// since 9; useinstead none
wallpaper.getMinHeight();
// since 9; useinstead none
wallpaper.getMinWidth();
// since 9; useinstead none
wallpaper.isChangePermitted();
// since 9; useinstead none
wallpaper.isOperationAllowed();
// since 9; useinstead none
wallpaper.off('colorChange');
// since 9; useinstead none
wallpaper.on('colorChange', () => {});
// since 9; useinstead none
wallpaper.reset(({} as any));
// since 9; useinstead none
wallpaper.setWallpaper(({} as any), ({} as any));
