// Auto-generated by scripts/gen-deprecated-usage.mjs — do not edit.
// Kit: @ohos.ability.particleAbility
// Deprecated symbols: 2 (compilable real-usage corpus; expect TS 6385/6387).
// Generated: 2026-08-15T18:18:26.091Z

import particleAbility from '@ohos.ability.particleAbility';

// Deprecated symbol usages.
// since 9; useinstead @ohos.resourceschedule.backgroundTaskManager.stopBackgroundRunning
particleAbility.cancelBackgroundRunning();
// since 9; useinstead @ohos.resourceschedule.backgroundTaskManager.startBackgroundRunning
particleAbility.startBackgroundRunning(0, ({} as any));
