// Auto-generated by scripts/gen-deprecated-usage.mjs — do not edit.
// Kit: @ohos.pasteboard
// Deprecated symbols: 22 (compilable real-usage corpus; expect TS 6385/6387).
// Generated: 2026-08-15T18:18:26.091Z

import pasteboard from '@ohos.pasteboard';

// Deprecated symbol usages.
// since 9; useinstead @ohos.pasteboard.pasteboard.addRecord
let _v0: pasteboard.PasteData = {} as pasteboard.PasteData; _v0.addHtmlRecord('');
// since 9; useinstead @ohos.pasteboard.pasteboard.addRecord
let _v1: pasteboard.PasteData = {} as pasteboard.PasteData; _v1.addTextRecord('');
// since 9; useinstead @ohos.pasteboard.pasteboard.addRecord
let _v2: pasteboard.PasteData = {} as pasteboard.PasteData; _v2.addUriRecord('');
// since 9; useinstead @ohos.pasteboard.pasteboard.addRecord
let _v3: pasteboard.PasteData = {} as pasteboard.PasteData; _v3.addWantRecord(({} as any));
// since 9; useinstead @ohos.pasteboard.pasteboard.getRecord
let _v4: pasteboard.PasteData = {} as pasteboard.PasteData; _v4.getRecordAt(0);
// since 9; useinstead @ohos.pasteboard.pasteboard.hasType
let _v5: pasteboard.PasteData = {} as pasteboard.PasteData; _v5.hasMimeType('');
// since 9; useinstead @ohos.pasteboard.pasteboard.removeRecord
let _v6: pasteboard.PasteData = {} as pasteboard.PasteData; _v6.removeRecordAt(0);
// since 9; useinstead @ohos.pasteboard.pasteboard.replaceRecord
let _v7: pasteboard.PasteData = {} as pasteboard.PasteData; _v7.replaceRecordAt(0, ({} as any));
// since 9; useinstead @ohos.pasteboard.pasteboard.toPlainText
let _v8: pasteboard.PasteDataRecord = {} as pasteboard.PasteDataRecord; _v8.convertToText();
// since 12; useinstead none
const _v9 = pasteboard.ShareOption.CROSSDEVICE;
// since 9; useinstead @ohos.pasteboard.pasteboard.clearData
let _v10: pasteboard.SystemPasteboard = {} as pasteboard.SystemPasteboard; _v10.clear();
// since 9; useinstead @ohos.pasteboard.pasteboard.getData
let _v11: pasteboard.SystemPasteboard = {} as pasteboard.SystemPasteboard; _v11.getPasteData();
// since 9; useinstead @ohos.pasteboard.pasteboard.hasData
let _v12: pasteboard.SystemPasteboard = {} as pasteboard.SystemPasteboard; _v12.hasPasteData();
// since 9; useinstead @ohos.pasteboard.pasteboard.setData
let _v13: pasteboard.SystemPasteboard = {} as pasteboard.SystemPasteboard; _v13.setPasteData(({} as any));
// since 9; useinstead @ohos.pasteboard.createData
pasteboard.createHtmlData('');
// since 9; useinstead @ohos.pasteboard.createRecord
pasteboard.createHtmlTextRecord('');
// since 9; useinstead @ohos.pasteboard.createData
pasteboard.createPlainTextData('');
// since 9; useinstead @ohos.pasteboard.createRecord
pasteboard.createPlainTextRecord('');
// since 9; useinstead @ohos.pasteboard.createData
pasteboard.createUriData('');
// since 9; useinstead @ohos.pasteboard.createRecord
pasteboard.createUriRecord('');
// since 9; useinstead @ohos.pasteboard.createData
pasteboard.createWantData(({} as any));
// since 9; useinstead @ohos.pasteboard.createRecord
pasteboard.createWantRecord(({} as any));
