// Auto-generated by scripts/gen-deprecated-usage.mjs — do not edit.
// Kit: @system.app
// Deprecated symbols: 2 (compilable real-usage corpus; expect TS 6385/6387).
// Generated: 2026-08-15T18:18:26.091Z

import App from '@system.app';

// Deprecated symbol usages.
// since 8; useinstead @system.app.startAbility
App.requestFullWindow();
// since 8; useinstead none
App.screenOnVisible();
