// Auto-generated by scripts/gen-deprecated-usage.mjs — do not edit.
// Kit: @system.file
// Deprecated symbols: 101 (compilable real-usage corpus; expect TS 6385/6387).
// Generated: 2026-08-15T18:18:26.091Z

import File from '@system.file';
import { FileAccessOption, FileCopyOption, FileDeleteOption, FileGetOption, FileListOption, FileListResponse, FileMkdirOption, FileMoveOption, FileReadArrayBufferOption, FileReadArrayBufferResponse, FileReadTextOption, FileReadTextResponse, FileResponse, FileRmdirOption, FileWriteArrayBufferOption, FileWriteTextOption } from '@system.file';

// Deprecated symbol usages.
// since 10; useinstead none
let _v0: FileResponse = {} as FileResponse;
// since 10; useinstead none
let _v1: FileMoveOption = {} as FileMoveOption;
// since 10; useinstead none
let _v2: FileListResponse = {} as FileListResponse;
// since 10; useinstead none
let _v3: FileListOption = {} as FileListOption;
// since 10; useinstead none
let _v4: FileCopyOption = {} as FileCopyOption;
// since 10; useinstead none
let _v5: FileGetOption = {} as FileGetOption;
// since 10; useinstead none
let _v6: FileDeleteOption = {} as FileDeleteOption;
// since 10; useinstead none
let _v7: FileWriteTextOption = {} as FileWriteTextOption;
// since 10; useinstead none
let _v8: FileReadTextResponse = {} as FileReadTextResponse;
// since 10; useinstead none
let _v9: FileReadTextOption = {} as FileReadTextOption;
// since 10; useinstead none
let _v10: FileWriteArrayBufferOption = {} as FileWriteArrayBufferOption;
// since 10; useinstead none
let _v11: FileReadArrayBufferResponse = {} as FileReadArrayBufferResponse;
// since 10; useinstead none
let _v12: FileReadArrayBufferOption = {} as FileReadArrayBufferOption;
// since 10; useinstead none
let _v13: FileAccessOption = {} as FileAccessOption;
// since 10; useinstead none
let _v14: FileMkdirOption = {} as FileMkdirOption;
// since 10; useinstead none
let _v15: FileRmdirOption = {} as FileRmdirOption;
// since 10; useinstead none
let _v16: File = {} as File;
// since 10; useinstead @ohos.file.fs.access
File.access(({} as any));
// since 10; useinstead none
let _v17: FileWriteTextOption = {} as FileWriteTextOption; const _v18 = _v17.append;
// since 10; useinstead none
let _v19: FileWriteArrayBufferOption = {} as FileWriteArrayBufferOption; const _v20 = _v19.append;
// since 10; useinstead none
let _v21: FileWriteArrayBufferOption = {} as FileWriteArrayBufferOption; const _v22 = _v21.buffer;
// since 10; useinstead none
let _v23: FileReadArrayBufferResponse = {} as FileReadArrayBufferResponse; const _v24 = _v23.buffer;
// since 10; useinstead none
let _v25: FileMoveOption = {} as FileMoveOption; const _v26 = _v25.complete;
// since 10; useinstead none
let _v27: FileListOption = {} as FileListOption; const _v28 = _v27.complete;
// since 10; useinstead none
let _v29: FileCopyOption = {} as FileCopyOption; const _v30 = _v29.complete;
// since 10; useinstead none
let _v31: FileGetOption = {} as FileGetOption; const _v32 = _v31.complete;
// since 10; useinstead none
let _v33: FileDeleteOption = {} as FileDeleteOption; const _v34 = _v33.complete;
// since 10; useinstead none
let _v35: FileWriteTextOption = {} as FileWriteTextOption; const _v36 = _v35.complete;
// since 10; useinstead none
let _v37: FileReadTextOption = {} as FileReadTextOption; const _v38 = _v37.complete;
// since 10; useinstead none
let _v39: FileWriteArrayBufferOption = {} as FileWriteArrayBufferOption; const _v40 = _v39.complete;
// since 10; useinstead none
let _v41: FileReadArrayBufferOption = {} as FileReadArrayBufferOption; const _v42 = _v41.complete;
// since 10; useinstead none
let _v43: FileAccessOption = {} as FileAccessOption; const _v44 = _v43.complete;
// since 10; useinstead none
let _v45: FileMkdirOption = {} as FileMkdirOption; const _v46 = _v45.complete;
// since 10; useinstead none
let _v47: FileRmdirOption = {} as FileRmdirOption; const _v48 = _v47.complete;
// since 10; useinstead @ohos.file.fs.copyFile
File.copy(({} as any));
// since 10; useinstead @ohos.file.fs.unlink
File.delete(({} as any));
// since 10; useinstead none
let _v49: FileMoveOption = {} as FileMoveOption; const _v50 = _v49.dstUri;
// since 10; useinstead none
let _v51: FileCopyOption = {} as FileCopyOption; const _v52 = _v51.dstUri;
// since 10; useinstead none
let _v53: FileWriteTextOption = {} as FileWriteTextOption; const _v54 = _v53.encoding;
// since 10; useinstead none
let _v55: FileReadTextOption = {} as FileReadTextOption; const _v56 = _v55.encoding;
// since 10; useinstead none
let _v57: FileMoveOption = {} as FileMoveOption; const _v58 = _v57.fail;
// since 10; useinstead none
let _v59: FileListOption = {} as FileListOption; const _v60 = _v59.fail;
// since 10; useinstead none
let _v61: FileCopyOption = {} as FileCopyOption; const _v62 = _v61.fail;
// since 10; useinstead none
let _v63: FileGetOption = {} as FileGetOption; const _v64 = _v63.fail;
// since 10; useinstead none
let _v65: FileDeleteOption = {} as FileDeleteOption; const _v66 = _v65.fail;
// since 10; useinstead none
let _v67: FileWriteTextOption = {} as FileWriteTextOption; const _v68 = _v67.fail;
// since 10; useinstead none
let _v69: FileReadTextOption = {} as FileReadTextOption; const _v70 = _v69.fail;
// since 10; useinstead none
let _v71: FileWriteArrayBufferOption = {} as FileWriteArrayBufferOption; const _v72 = _v71.fail;
// since 10; useinstead none
let _v73: FileReadArrayBufferOption = {} as FileReadArrayBufferOption; const _v74 = _v73.fail;
// since 10; useinstead none
let _v75: FileAccessOption = {} as FileAccessOption; const _v76 = _v75.fail;
// since 10; useinstead none
let _v77: FileMkdirOption = {} as FileMkdirOption; const _v78 = _v77.fail;
// since 10; useinstead none
let _v79: FileRmdirOption = {} as FileRmdirOption; const _v80 = _v79.fail;
// since 10; useinstead none
let _v81: FileListResponse = {} as FileListResponse; const _v82 = _v81.fileList;
// since 10; useinstead @ohos.file.fs.stat
File.get(({} as any));
// since 10; useinstead none
let _v83: FileResponse = {} as FileResponse; const _v84 = _v83.lastModifiedTime;
// since 10; useinstead none
let _v85: FileResponse = {} as FileResponse; const _v86 = _v85.length;
// since 10; useinstead none
let _v87: FileReadTextOption = {} as FileReadTextOption; const _v88 = _v87.length;
// since 10; useinstead none
let _v89: FileReadArrayBufferOption = {} as FileReadArrayBufferOption; const _v90 = _v89.length;
// since 10; useinstead @ohos.file.fs.listFile
File.list(({} as any));
// since 10; useinstead @ohos.file.fs.mkdir
File.mkdir(({} as any));
// since 10; useinstead @ohos.file.fs.moveFile
File.move(({} as any));
// since 10; useinstead none
let _v91: FileReadTextOption = {} as FileReadTextOption; const _v92 = _v91.position;
// since 10; useinstead none
let _v93: FileWriteArrayBufferOption = {} as FileWriteArrayBufferOption; const _v94 = _v93.position;
// since 10; useinstead none
let _v95: FileReadArrayBufferOption = {} as FileReadArrayBufferOption; const _v96 = _v95.position;
// since 10; useinstead @ohos.file.fs.read
File.readArrayBuffer(({} as any));
// since 10; useinstead @ohos.file.fs.readText
File.readText(({} as any));
// since 10; useinstead none
let _v97: FileGetOption = {} as FileGetOption; const _v98 = _v97.recursive;
// since 10; useinstead none
let _v99: FileMkdirOption = {} as FileMkdirOption; const _v100 = _v99.recursive;
// since 10; useinstead none
let _v101: FileRmdirOption = {} as FileRmdirOption; const _v102 = _v101.recursive;
// since 10; useinstead @ohos.file.fs.rmdir
File.rmdir(({} as any));
// since 10; useinstead none
let _v103: FileMoveOption = {} as FileMoveOption; const _v104 = _v103.srcUri;
// since 10; useinstead none
let _v105: FileCopyOption = {} as FileCopyOption; const _v106 = _v105.srcUri;
// since 10; useinstead none
let _v107: FileResponse = {} as FileResponse; const _v108 = _v107.subFiles;
// since 10; useinstead none
let _v109: FileMoveOption = {} as FileMoveOption; const _v110 = _v109.success;
// since 10; useinstead none
let _v111: FileListOption = {} as FileListOption; const _v112 = _v111.success;
// since 10; useinstead none
let _v113: FileCopyOption = {} as FileCopyOption; const _v114 = _v113.success;
// since 10; useinstead none
let _v115: FileGetOption = {} as FileGetOption; const _v116 = _v115.success;
// since 10; useinstead none
let _v117: FileDeleteOption = {} as FileDeleteOption; const _v118 = _v117.success;
// since 10; useinstead none
let _v119: FileWriteTextOption = {} as FileWriteTextOption; const _v120 = _v119.success;
// since 10; useinstead none
let _v121: FileReadTextOption = {} as FileReadTextOption; const _v122 = _v121.success;
// since 10; useinstead none
let _v123: FileWriteArrayBufferOption = {} as FileWriteArrayBufferOption; const _v124 = _v123.success;
// since 10; useinstead none
let _v125: FileReadArrayBufferOption = {} as FileReadArrayBufferOption; const _v126 = _v125.success;
// since 10; useinstead none
let _v127: FileAccessOption = {} as FileAccessOption; const _v128 = _v127.success;
// since 10; useinstead none
let _v129: FileMkdirOption = {} as FileMkdirOption; const _v130 = _v129.success;
// since 10; useinstead none
let _v131: FileRmdirOption = {} as FileRmdirOption; const _v132 = _v131.success;
// since 10; useinstead none
let _v133: FileWriteTextOption = {} as FileWriteTextOption; const _v134 = _v133.text;
// since 10; useinstead none
let _v135: FileReadTextResponse = {} as FileReadTextResponse; const _v136 = _v135.text;
// since 10; useinstead none
let _v137: FileResponse = {} as FileResponse; const _v138 = _v137.type;
// since 10; useinstead none
let _v139: FileResponse = {} as FileResponse; const _v140 = _v139.uri;
// since 10; useinstead none
let _v141: FileListOption = {} as FileListOption; const _v142 = _v141.uri;
// since 10; useinstead none
let _v143: FileGetOption = {} as FileGetOption; const _v144 = _v143.uri;
// since 10; useinstead none
let _v145: FileDeleteOption = {} as FileDeleteOption; const _v146 = _v145.uri;
// since 10; useinstead none
let _v147: FileWriteTextOption = {} as FileWriteTextOption; const _v148 = _v147.uri;
// since 10; useinstead none
let _v149: FileReadTextOption = {} as FileReadTextOption; const _v150 = _v149.uri;
// since 10; useinstead none
let _v151: FileWriteArrayBufferOption = {} as FileWriteArrayBufferOption; const _v152 = _v151.uri;
// since 10; useinstead none
let _v153: FileReadArrayBufferOption = {} as FileReadArrayBufferOption; const _v154 = _v153.uri;
// since 10; useinstead none
let _v155: FileAccessOption = {} as FileAccessOption; const _v156 = _v155.uri;
// since 10; useinstead none
let _v157: FileMkdirOption = {} as FileMkdirOption; const _v158 = _v157.uri;
// since 10; useinstead none
let _v159: FileRmdirOption = {} as FileRmdirOption; const _v160 = _v159.uri;
// since 10; useinstead @ohos.file.fs.write
File.writeArrayBuffer(({} as any));
// since 10; useinstead @ohos.file.fs.write
File.writeText(({} as any));
