// Auto-generated by scripts/gen-deprecated-usage.mjs — do not edit.
// Kit: @system.prompt
// Deprecated symbols: 4 (compilable real-usage corpus; expect TS 6385/6387).
// Generated: 2026-08-15T18:18:26.091Z

import Prompt from '@system.prompt';
import { ShowToastOptions } from '@system.prompt';

// Deprecated symbol usages.
// since 8; useinstead @ohos.promptAction.ShowToastOptions
let _v0: ShowToastOptions = {} as ShowToastOptions;
// since 8; useinstead @ohos.promptAction.ShowToastOptions.bottom
let _v1: ShowToastOptions = {} as ShowToastOptions; const _v2 = _v1.bottom;
// since 8; useinstead @ohos.promptAction.ShowToastOptions.duration
let _v3: ShowToastOptions = {} as ShowToastOptions; const _v4 = _v3.duration;
// since 8; useinstead @ohos.promptAction.ShowToastOptions.message
let _v5: ShowToastOptions = {} as ShowToastOptions; const _v6 = _v5.message;
