// Auto-generated by scripts/gen-deprecated-usage.mjs — do not edit.
// Kit: @system.geolocation
// Deprecated symbols: 28 (compilable real-usage corpus; expect TS 6385/6387).
// Generated: 2026-08-15T18:18:26.091Z

import Geolocation from '@system.geolocation';
import { GeolocationResponse, GetLocationOption, GetLocationTypeOption, GetLocationTypeResponse, SubscribeLocationOption } from '@system.geolocation';

// Deprecated symbol usages.
// since 9; useinstead @ohos.geoLocationManager.Location
let _v0: GeolocationResponse = {} as GeolocationResponse;
// since 9; useinstead @ohos.geoLocationManager.CurrentLocationRequest
let _v1: GetLocationOption = {} as GetLocationOption;
// since 9; useinstead none
let _v2: GetLocationTypeResponse = {} as GetLocationTypeResponse;
// since 9; useinstead none
let _v3: GetLocationTypeOption = {} as GetLocationTypeOption;
// since 9; useinstead @ohos.geoLocationManager.LocationRequest
let _v4: SubscribeLocationOption = {} as SubscribeLocationOption;
// since 9; useinstead @ohos.geoLocationManager.
let _v5: Geolocation = {} as Geolocation;
// since 9; useinstead @ohos.geoLocationManager.Location.accuracy
let _v6: GeolocationResponse = {} as GeolocationResponse; const _v7 = _v6.accuracy;
// since 9; useinstead @ohos.geoLocationManager.Location.altitude
let _v8: GeolocationResponse = {} as GeolocationResponse; const _v9 = _v8.altitude;
// since 9; useinstead @ohos.geoLocationManager.getCurrentLocation.callback
let _v10: GetLocationOption = {} as GetLocationOption; const _v11 = _v10.complete;
// since 9; useinstead none
let _v12: GetLocationTypeOption = {} as GetLocationTypeOption; const _v13 = _v12.complete;
// since 9; useinstead none
let _v14: GetLocationOption = {} as GetLocationOption; const _v15 = _v14.coordType;
// since 9; useinstead none
let _v16: SubscribeLocationOption = {} as SubscribeLocationOption; const _v17 = _v16.coordType;
// since 9; useinstead @ohos.geoLocationManager.getCurrentLocation.callback
let _v18: GetLocationOption = {} as GetLocationOption; const _v19 = _v18.fail;
// since 9; useinstead none
let _v20: GetLocationTypeOption = {} as GetLocationTypeOption; const _v21 = _v20.fail;
// since 9; useinstead none
let _v22: SubscribeLocationOption = {} as SubscribeLocationOption; const _v23 = _v22.fail;
// since 9; useinstead @ohos.geoLocationManager.getCurrentLocation
Geolocation.getLocation();
// since 9; useinstead none
Geolocation.getLocationType();
// since 9; useinstead none
Geolocation.getSupportedCoordTypes();
// since 9; useinstead @ohos.geoLocationManager.Location.latitude
let _v24: GeolocationResponse = {} as GeolocationResponse; const _v25 = _v24.latitude;
// since 9; useinstead @ohos.geoLocationManager.Location.longitude
let _v26: GeolocationResponse = {} as GeolocationResponse; const _v27 = _v26.longitude;
// since 9; useinstead @ohos.geoLocationManager.on
Geolocation.subscribe(({} as any));
// since 9; useinstead @ohos.geoLocationManager.getCurrentLocation.callback
let _v28: GetLocationOption = {} as GetLocationOption; const _v29 = _v28.success;
// since 9; useinstead none
let _v30: GetLocationTypeOption = {} as GetLocationTypeOption; const _v31 = _v30.success;
// since 9; useinstead none
let _v32: SubscribeLocationOption = {} as SubscribeLocationOption; const _v33 = _v32.success;
// since 9; useinstead @ohos.geoLocationManager.Location.timeStamp
let _v34: GeolocationResponse = {} as GeolocationResponse; const _v35 = _v34.time;
// since 9; useinstead @ohos.geoLocationManager.CurrentLocationRequest.timeoutMs
let _v36: GetLocationOption = {} as GetLocationOption; const _v37 = _v36.timeout;
// since 9; useinstead none
let _v38: GetLocationTypeResponse = {} as GetLocationTypeResponse; const _v39 = _v38.types;
// since 9; useinstead @ohos.geoLocationManager.off
Geolocation.unsubscribe();
