// Auto-generated by scripts/gen-deprecated-usage.mjs — do not edit.
// Kit: @system.battery
// Deprecated symbols: 9 (compilable real-usage corpus; expect TS 6385/6387).
// Generated: 2026-08-15T18:18:26.091Z

import Battery from '@system.battery';
import { BatteryResponse, GetStatusOptions } from '@system.battery';

// Deprecated symbol usages.
// since 6; useinstead none
let _v0: BatteryResponse = {} as BatteryResponse;
// since 6; useinstead none
let _v1: GetStatusOptions = {} as GetStatusOptions;
// since 6; useinstead none
let _v2: Battery = {} as Battery;
// since 6; useinstead @ohos.batteryInfo.chargingStatus
let _v3: BatteryResponse = {} as BatteryResponse; const _v4 = _v3.charging;
// since 6; useinstead none
let _v5: GetStatusOptions = {} as GetStatusOptions; const _v6 = _v5.complete;
// since 6; useinstead none
let _v7: GetStatusOptions = {} as GetStatusOptions; const _v8 = _v7.fail;
// since 6; useinstead none
Battery.getStatus();
// since 6; useinstead @ohos.batteryInfo.batterySOC
let _v9: BatteryResponse = {} as BatteryResponse; const _v10 = _v9.level;
// since 6; useinstead none
let _v11: GetStatusOptions = {} as GetStatusOptions; const _v12 = _v11.success;
