// Auto-generated by scripts/gen-deprecated-usage.mjs — do not edit.
// Kit: @system.request
// Deprecated symbols: 42 (compilable real-usage corpus; expect TS 6385/6387).
// Generated: 2026-08-15T18:18:26.091Z

import Request from '@system.request';
import { DownloadRequestOptions, DownloadResponse, OnDownloadCompleteOptions, OnDownloadCompleteResponse, RequestData, RequestFile, UploadRequestOptions, UploadResponse } from '@system.request';

// Deprecated symbol usages.
// since 9; useinstead @ohos.request.
let _v0: UploadResponse = {} as UploadResponse;
// since 9; useinstead @ohos.request.agent.Progress
let _v1: DownloadResponse = {} as DownloadResponse;
// since 9; useinstead @ohos.request.agent.Progress
let _v2: OnDownloadCompleteResponse = {} as OnDownloadCompleteResponse;
// since 9; useinstead @ohos.request.agent.FileSpec
let _v3: RequestFile = {} as RequestFile;
// since 9; useinstead @ohos.request.agent.FormItem
let _v4: RequestData = {} as RequestData;
// since 9; useinstead @ohos.request.agent.Config
let _v5: UploadRequestOptions = {} as UploadRequestOptions;
// since 9; useinstead @ohos.request.agent.Config
let _v6: DownloadRequestOptions = {} as DownloadRequestOptions;
// since 9; useinstead @ohos.request.agent.Progress
let _v7: OnDownloadCompleteOptions = {} as OnDownloadCompleteOptions;
// since 9; useinstead @ohos.request.agent
let _v8: Request = {} as Request;
// since 9; useinstead @ohos.request.agent.HttpResponse.statusCode
let _v9: UploadResponse = {} as UploadResponse; const _v10 = _v9.code;
// since 9; useinstead @ohos.request.agent.Task.on
let _v11: UploadRequestOptions = {} as UploadRequestOptions; const _v12 = _v11.complete;
// since 9; useinstead @ohos.request.agent.Task.on
let _v13: DownloadRequestOptions = {} as DownloadRequestOptions; const _v14 = _v13.complete;
// since 9; useinstead @ohos.request.agent.Task.on
let _v15: OnDownloadCompleteOptions = {} as OnDownloadCompleteOptions; const _v16 = _v15.complete;
// since 9; useinstead @ohos.request.agent.Progress.extras
let _v17: UploadResponse = {} as UploadResponse; const _v18 = _v17.data;
// since 9; useinstead @ohos.request.agent.Config.data
let _v19: UploadRequestOptions = {} as UploadRequestOptions; const _v20 = _v19.data;
// since 9; useinstead @ohos.request.agent.Config.description
let _v21: DownloadRequestOptions = {} as DownloadRequestOptions; const _v22 = _v21.description;
// since 9; useinstead @ohos.request.agent.create
Request.download(({} as any));
// since 9; useinstead @ohos.request.agent.Task.on
let _v23: UploadRequestOptions = {} as UploadRequestOptions; const _v24 = _v23.fail;
// since 9; useinstead @ohos.request.agent.Task.on
let _v25: DownloadRequestOptions = {} as DownloadRequestOptions; const _v26 = _v25.fail;
// since 9; useinstead @ohos.request.agent.Task.on
let _v27: OnDownloadCompleteOptions = {} as OnDownloadCompleteOptions; const _v28 = _v27.fail;
// since 9; useinstead @ohos.request.agent.FileSpec.filename
let _v29: RequestFile = {} as RequestFile; const _v30 = _v29.filename;
// since 9; useinstead @ohos.request.agent.Config.saveas
let _v31: DownloadRequestOptions = {} as DownloadRequestOptions; const _v32 = _v31.filename;
// since 9; useinstead @ohos.request.agent.Config.data
let _v33: UploadRequestOptions = {} as UploadRequestOptions; const _v34 = _v33.files;
// since 9; useinstead @ohos.request.agent.Config.headers
let _v35: UploadRequestOptions = {} as UploadRequestOptions; const _v36 = _v35.header;
// since 9; useinstead @ohos.request.agent.Config.headers
let _v37: DownloadRequestOptions = {} as DownloadRequestOptions; const _v38 = _v37.header;
// since 9; useinstead @ohos.request.agent.HttpResponse.headers
let _v39: UploadResponse = {} as UploadResponse; const _v40 = _v39.headers;
// since 9; useinstead @ohos.request.agent.Config.method
let _v41: UploadRequestOptions = {} as UploadRequestOptions; const _v42 = _v41.method;
// since 9; useinstead @ohos.request.agent.FormItem.name
let _v43: RequestFile = {} as RequestFile; const _v44 = _v43.name;
// since 9; useinstead @ohos.request.agent.FormItem.name
let _v45: RequestData = {} as RequestData; const _v46 = _v45.name;
// since 9; useinstead @ohos.request.agent.Task.on
Request.onDownloadComplete(({} as any));
// since 9; useinstead @ohos.request.agent.Task.on
let _v47: UploadRequestOptions = {} as UploadRequestOptions; const _v48 = _v47.success;
// since 9; useinstead @ohos.request.agent.Task.on
let _v49: DownloadRequestOptions = {} as DownloadRequestOptions; const _v50 = _v49.success;
// since 9; useinstead @ohos.request.agent.Task.on
let _v51: OnDownloadCompleteOptions = {} as OnDownloadCompleteOptions; const _v52 = _v51.success;
// since 9; useinstead @ohos.request.agent.Task.tid
let _v53: DownloadResponse = {} as DownloadResponse; const _v54 = _v53.token;
// since 9; useinstead @ohos.request.agent.Task.tid
let _v55: OnDownloadCompleteOptions = {} as OnDownloadCompleteOptions; const _v56 = _v55.token;
// since 9; useinstead @ohos.request.agent.FileSpec.contentType
let _v57: RequestFile = {} as RequestFile; const _v58 = _v57.type;
// since 9; useinstead @ohos.request.agent.create
Request.upload(({} as any));
// since 9; useinstead @ohos.request.agent.Task.config.saveas
let _v59: OnDownloadCompleteResponse = {} as OnDownloadCompleteResponse; const _v60 = _v59.uri;
// since 9; useinstead @ohos.request.agent.FileSpec.path
let _v61: RequestFile = {} as RequestFile; const _v62 = _v61.uri;
// since 9; useinstead @ohos.request.agent.Config.url
let _v63: UploadRequestOptions = {} as UploadRequestOptions; const _v64 = _v63.url;
// since 9; useinstead @ohos.request.agent.Config.url
let _v65: DownloadRequestOptions = {} as DownloadRequestOptions; const _v66 = _v65.url;
// since 9; useinstead @ohos.request.agent.FormItem.value
let _v67: RequestData = {} as RequestData; const _v68 = _v67.value;
