// Auto-generated by scripts/gen-deprecated-usage.mjs — do not edit.
// Kit: @system.brightness
// Deprecated symbols: 33 (compilable real-usage corpus; expect TS 6385/6387).
// Generated: 2026-08-15T18:18:26.091Z

import Brightness from '@system.brightness';
import { BrightnessModeResponse, BrightnessResponse, GetBrightnessModeOptions, GetBrightnessOptions, SetBrightnessModeOptions, SetBrightnessOptions, SetKeepScreenOnOptions } from '@system.brightness';

// Deprecated symbol usages.
// since 7; useinstead none
let _v0: BrightnessResponse = {} as BrightnessResponse;
// since 7; useinstead none
let _v1: GetBrightnessOptions = {} as GetBrightnessOptions;
// since 7; useinstead none
let _v2: SetBrightnessOptions = {} as SetBrightnessOptions;
// since 7; useinstead none
let _v3: BrightnessModeResponse = {} as BrightnessModeResponse;
// since 7; useinstead none
let _v4: GetBrightnessModeOptions = {} as GetBrightnessModeOptions;
// since 7; useinstead none
let _v5: SetBrightnessModeOptions = {} as SetBrightnessModeOptions;
// since 7; useinstead none
let _v6: SetKeepScreenOnOptions = {} as SetKeepScreenOnOptions;
// since 7; useinstead none
let _v7: Brightness = {} as Brightness;
// since 7; useinstead none
let _v8: GetBrightnessOptions = {} as GetBrightnessOptions; const _v9 = _v8.complete;
// since 7; useinstead none
let _v10: SetBrightnessOptions = {} as SetBrightnessOptions; const _v11 = _v10.complete;
// since 7; useinstead none
let _v12: GetBrightnessModeOptions = {} as GetBrightnessModeOptions; const _v13 = _v12.complete;
// since 7; useinstead none
let _v14: SetBrightnessModeOptions = {} as SetBrightnessModeOptions; const _v15 = _v14.complete;
// since 7; useinstead none
let _v16: SetKeepScreenOnOptions = {} as SetKeepScreenOnOptions; const _v17 = _v16.complete;
// since 7; useinstead none
let _v18: GetBrightnessOptions = {} as GetBrightnessOptions; const _v19 = _v18.fail;
// since 7; useinstead none
let _v20: SetBrightnessOptions = {} as SetBrightnessOptions; const _v21 = _v20.fail;
// since 7; useinstead none
let _v22: GetBrightnessModeOptions = {} as GetBrightnessModeOptions; const _v23 = _v22.fail;
// since 7; useinstead none
let _v24: SetBrightnessModeOptions = {} as SetBrightnessModeOptions; const _v25 = _v24.fail;
// since 7; useinstead none
let _v26: SetKeepScreenOnOptions = {} as SetKeepScreenOnOptions; const _v27 = _v26.fail;
// since 7; useinstead none
Brightness.getMode();
// since 7; useinstead none
Brightness.getValue();
// since 7; useinstead none
let _v28: SetKeepScreenOnOptions = {} as SetKeepScreenOnOptions; const _v29 = _v28.keepScreenOn;
// since 7; useinstead none
let _v30: BrightnessModeResponse = {} as BrightnessModeResponse; const _v31 = _v30.mode;
// since 7; useinstead none
let _v32: SetBrightnessModeOptions = {} as SetBrightnessModeOptions; const _v33 = _v32.mode;
// since 7; useinstead @ohos.window.setWindowKeepScreenOn
Brightness.setKeepScreenOn();
// since 7; useinstead none
Brightness.setMode();
// since 7; useinstead brightness/brightness.setValue
Brightness.setValue();
// since 7; useinstead none
let _v34: GetBrightnessOptions = {} as GetBrightnessOptions; const _v35 = _v34.success;
// since 7; useinstead none
let _v36: SetBrightnessOptions = {} as SetBrightnessOptions; const _v37 = _v36.success;
// since 7; useinstead none
let _v38: GetBrightnessModeOptions = {} as GetBrightnessModeOptions; const _v39 = _v38.success;
// since 7; useinstead none
let _v40: SetBrightnessModeOptions = {} as SetBrightnessModeOptions; const _v41 = _v40.success;
// since 7; useinstead none
let _v42: SetKeepScreenOnOptions = {} as SetKeepScreenOnOptions; const _v43 = _v42.success;
// since 7; useinstead none
let _v44: BrightnessResponse = {} as BrightnessResponse; const _v45 = _v44.value;
// since 7; useinstead none
let _v46: SetBrightnessOptions = {} as SetBrightnessOptions; const _v47 = _v46.value;
