// Auto-generated by scripts/gen-deprecated-usage.mjs — do not edit.
// Kit: @system.vibrator
// Deprecated symbols: 7 (compilable real-usage corpus; expect TS 6385/6387).
// Generated: 2026-08-15T18:18:26.091Z

import Vibrator from '@system.vibrator';
import { VibrateOptions } from '@system.vibrator';

// Deprecated symbol usages.
// since 8; useinstead @ohos.vibrator.VibrateTime
let _v0: VibrateOptions = {} as VibrateOptions;
// since 8; useinstead @ohos.vibrator.
let _v1: Vibrator = {} as Vibrator;
// since 8; useinstead @ohos.vibrator.startVibration
let _v2: VibrateOptions = {} as VibrateOptions; const _v3 = _v2.complete;
// since 8; useinstead @ohos.vibrator.startVibration
let _v4: VibrateOptions = {} as VibrateOptions; const _v5 = _v4.fail;
// since 8; useinstead @ohos.vibrator.VibrateTime
let _v6: VibrateOptions = {} as VibrateOptions; const _v7 = _v6.mode;
// since 8; useinstead @ohos.vibrator.startVibration
let _v8: VibrateOptions = {} as VibrateOptions; const _v9 = _v8.success;
// since 8; useinstead @ohos.vibrator.startVibration
Vibrator.vibrate();
